### ISSUE TITLE
Parameter Mappings

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#10]
When using vectors of ExpData in AmiciObjective that correspond to different cell-lines, inhibitors, etc. these may often use a subset of the full parameter vector. Would be nice to have functionality that automatically extends `pesto.Problem` and constructs index vectors to be used in `pesto.AmiciObjective`.

Proposed format:
`{'modelParameter':'newExperimentSpecificParameter',...}`

**Comment by dweindl** [comment]
Definitely a feature to include. I think `pesto.AmiciObjective` would be the place to store it, though.

**Comment by FFroehlich** [comment]
Agreed, but you need to extend the parameter vector & bounds in `pesto.Problem`.

**Comment by dweindl** [comment]
Something like `pesto.Problem.parameters = pesto.AmiciObjective.getAllParameters()` ?

**Comment by FFroehlich** [comment]
I thought about intitalizing it from `amici.Model` and then extending it based on the objective, but I guess that directly constructing from `pesto.AmiciObjective` even makes more.
