### ISSUE TITLE
Extract x_names from petab parameters file

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#101]
Either in petab or pypesto.PetabImporter, when creating an amici objective, one should try to extract parameter names from the parameters file, and only if non-existent fall back to using ids (as it's currently done).

**Comment by jvanhoefer** [comment]
Seems closed, right?

https://github.com/ICB-DCM/pyPESTO/blob/7ac53127c976f615397f6e0250725e1469bf24e8/pypesto/petab/importer.py#L346
