### ISSUE TITLE
Gradient methods in the Objective class

### ISSUE THREAD

**Issue by aidinbii** [ICB-DCM/pyPESTO#1011]
Hello, I have a question about the gradient methods in the Objective class
```
obj = importer.create_objective()

obj.amici_solver.setSensitivityMethod(amici.SensitivityMethod_none)
obj.amici_solver.setSensitivityOrder(amici.SensitivityOrder_none)

problem = importer.create_problem(obj,sensi_orders=(0,1), )
```
Then I run:
` obj.amici_solver.getSensitivityMethod() `
which returns "0".
Does it correspond to Finite Differences (FD)?

As I understood: 
1: forward sensitivity, 2: adjoint sensitivity, 3: FD ?

Thanks!

**Comment by dweindl** [comment]
Hi @aidinbii,

> As I understood:
> 1: forward sensitivity, 2: adjoint sensitivity, 3: FD ?

1,2: correct; 3 doesn't exist, and there are currently no finite differences implemented in AMICI.

You can see all options here:
```python
from amici import SensitivityMethod
for x in SensitivityMethod: print(repr(x))
```

`SensitivityMethod( obj.amici_solver.getSensitivityMethod())` will give you more informative output.

**Comment by aidinbii** [comment]
Oh, sorry then what 
`<SensitivityMethod.none: 0>` 
mean?

**Comment by dweindl** [comment]
> Oh, sorry then what `<SensitivityMethod.none: 0>` mean?

"Don't compute sensitivities."
