### ISSUE TITLE
class OptimizerHistory 

### ISSUE THREAD

**Issue by Mjvolk3** [ICB-DCM/pyPESTO#1024]
**Feature description**
I would like a function similar to `optimization_result_from_history` that can convert saved hdf5 History to an optimization result, which allow for access to all fval evaluations with its corresponding x (parameter vector). 

**Motivation/Application**
This feature is useful looking at the trajectory of a multi-start gradient descent run from a particular x. The current default behavior of `optimization_result_from_history` is to only provide `fval` with `x` which is the optimal point, and `fval0` with `x0` which is the start point for the optimization. Its clear from the csv file that this information accessible, but is just not being set to any attributes when reading in the h5. I have provided the csv and h5 output below. 

![Screenshot 2023-02-20 at 8 27 44 AM](https://user-images.githubusercontent.com/48566106/220133872-f8e0a268-5b5d-41bc-bf2f-14b159d743cf.png)

![Screenshot 2023-02-18 at 5 37 38 PM](https://user-images.githubusercontent.com/48566106/220134220-3f6a4ed5-711d-4e24-b382-897a543f128e.png)

By looking at parameter 2 in the csv file, we can see that are at least 4 unique x values, but the h5 file will only provide 2 max. 

**Proposal**

From looking over the src I think that this could be added as a class attribute to `OptimizerHistory`. either individual attributes could be added `x_{i}` , `f_{i}`, or an `nd.array` of each `x` and `fval`. 

The function `_maybe_compute_init_and_min_vals_from_trace` is called based on the boolean `generate_from_history` in the `OptimizerHistory` initialization. This function gets `x0 and fval0`. To get `x`, and `fval, this function calls `_get_optimal_point_from_history`. 

I think a function could be added similar to `_get_optimal_point_from_history`  that instead gets all history ( `_get_point_from_history`), which gets all but the start points and stores it in an `nd.array`. 

I think all this could be implemented by just adding another kwarg to `OptimizerHistory`.  Something like `generate_all_from_history`.  Then two functions each similar to `_maybe_compute_init_and_min_vals_from_trace` and `_get_optimal_point_from_history` would be added. `generate_from_history` and `generate_all_from_history` would be incompatible booleans.

I could work on it and create a merge request if that is preferred, but I figured the devs will be best suited for implementing it. Thanks!

**Comment by yannikschaelte** [comment]
Hi, I am not sure whether I understood your request correctly. You would like to store all parameters `x` and function values `fval` evaluated during an optimization, in `OptimizerHistory`? In order to look at the trajectory of an optimizer run?

This functionality is already provided, e.g. via `visualize.optimizer_history` (see  https://pypesto.readthedocs.io/en/latest/example/rosenbrock.html), by simply using the `History` object, around which `OptimizerHistory` is a wrapper.

**Comment by Mjvolk3** [comment]
Yes, this is solves my problem. I can use the `get_trace` methods on `History` to achieve the results I am looking for. Thank you for you help!

**Comment by yannikschaelte** [comment]
You're welcome! Let us know if there is other functionality you're missing or find insufficiently documented!
