### ISSUE TITLE
Multiprocessing with PyTorch Autograd

### ISSUE THREAD

**Issue by janko-petkovic** [ICB-DCM/pyPESTO#1031]
**Bug description**
Hello guys! I am currently using the PyPesto framework for my PhD project and I ran into this issue while trying to parallelize the `optimize.minimize` routine with the option `engine = pypesto.engine.MultiProcessEngine()`.
After running the routine, if one prints one of the elements of the `result.optimize_result.as_list()`, it shows 

```python
{
'id': '0',
'x': None, 
#[...]
'exitflag': <ExitFlag.DID_NOT_RUN: 0>,
'time': 0.01579761505126953,
'message': "Unable to handle autograd's threading in combination with fork-based multiprocessing. See https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork",
'optimizer': '<FidesOptimizer  hessian_update=BFGS verbose=False options={}>'
}
```
The problem seems to arise from a conflict between the `torch.autograd` package that I am using to compute the gradient of my objective function and the process instantiating method of `multiprocess.Pool`.
I tried implementing the fix suggested in the message in a forked version of pyPESTO, by editing the `execute` method of the `MultiProcessEngine` class in `pypesto.engine.multi_process.py` as 

```python
import multiprocessing as mp
# [...]

class MultiProcessEngine(Engine):
   # [...]

   def execute(self, tasks: List[Task], progress_bar: bool = True):
        # [...]

        # Experimental fix taken from https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork
        # to allow multiprocessing with Pytorch Autograd
        ctx = mp.get_context('spawn')

        with ctx.Pool(processes=n_procs) as pool:
            results = pool.map(
                work, tqdm(pickled_tasks, disable=not progress_bar)
            )

        return results

   # [...]
```

I tried rerunning it, and apparently, it works fine! It seems that this issue occurs only in Linux machines as the `fork` process instantiation method is the default one on those (MacOS and Windows rely on `spawn`, and forking is not even possible on Windows as it is nicely explained [here](https://britishgeologicalsurvey.github.io/science/python-forking-vs-spawn/#:~:text=Forking%20and%20spawning%20are%20two,they%20were%20in%20the%20parent)).

I wanted to ask you if it would be convenient for you to add this "fix" in your source or if you were relying on the `fork` method for other reasons. 
By the way, props for the clean code; it is indeed very legible and easy to understand.

**Environment**
- Operating system: EndeavourOS
- `pypesto` version: 0.2.14
- Python version: 3.10.9

**Comment by yannikschaelte** [comment]
Dear @janko-petkovic , thanks for reporting this. While spawn is safer and available on Windows, fork is faster and often sufficient. As some simulators may depend on the ability to safely parallelize (as in your case), we have now added an option to choose the method., see #1032 . I hope this works for your problem!

**Comment by janko-petkovic** [comment]
Yep, should work just fine! I will wait for the next release then, thank for the help :)
