### ISSUE TITLE
Way to parallelize dynesty

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#1033]
Hi pyPESTO team,

i currently try to parallelize dynesty with pyPESTO on a cluster.
However, OpenMPI, which is used to parallelize dynesty via schwimmbad is conflicting heavily with amici.

Do you know a way to create a pool that works with amici?

**Comment by yannikschaelte** [comment]
@dweindl @FFroehlich this question appears rather AMICI related?

**Comment by FFroehlich** [comment]
No experience with schwimmbad, but serialization will in general be tricky with AMICI. You can look at the different engines in https://github.com/ICB-DCM/pyPESTO/tree/main/pypesto/engine to get an idea how we set up parallelization in pyPESTO, but I am not sure whether all of those work with AMICI. 

Not familiar with dynesty, but I don't see a good reason why simulations in amici should be parallelized via OpenMPI since there shouldn't be any inter-process communication.

Could you provide some details about the error messages that you encounter?

**Comment by yannikschaelte** [comment]
Serialization of the AmiciObjective should be possible if it was e.g. generated via PEtab, or generally has a proper AmiciObjectBuilder, see https://github.com/ICB-DCM/pyPESTO/blob/main/pypesto/objective/amici/amici.py#L252

**Comment by shoepfl** [comment]
My basic idea was to only parallelize dynesty by parsing a pool to its sampler_args when it is called in pyPESTO. 
But maybe that was a naive approach anyways. 

The dynesty docs suggest the pool that is created with swimmbad, which uses mpi4py but I did not get a proper error in executing as already conda shows a huge load of conflicting packages with amici like libcblas. So I think this is not a good solution.

I also tried to create the pool with multiprocessing and parsing it to the sampler_args. Here is a minimal example:

`import pypesto
import pypesto.petab
import pypesto.optimize as optimize
import pypesto.sample as sample
import multiprocessing

M = 'synthetic_data'
Path = Path(__file__).parent / M

# Name of the yaml file of the PEtab Model
yaml_file = os.path.join(Path, M + '.yaml')

importer = pypesto.petab.PetabImporter.from_yaml(yaml_file)
problem = importer.create_problem(force_compile=True)

result = optimize.minimize(problem, n_starts=1)

dynesty_args = {'nlive': 100, 'sample': 'unif',
                'pool': multiprocessing.Pool(), 'queue_size':multiprocessing.cpu_count()}
sampler = sample.DynestySampler(sampler_args=dynesty_args)

result = sample.sample(problem=problem,
                       sampler=sampler,
                       n_samples=None,
                       result=result)
`
This gives me the error: "NotImplementedError: pool objects cannot be passed between processes or pickled"

Is it possible to parallelize dynesty in pypesto like this anyhow or am I completely wrong?

**Comment by FFroehlich** [comment]
We are not maintaining the conda formula and is notoriously bad at managing dependencies of C extensions, so I wouldn't recommend using it with anything AMICI related.

Regarding the issues you encountered, to me, this rather sounds like a problem on the end of dynasty or it's interface with pypesto. Are you sure that `multiprocessing.Pool()` is a valid argument for `pool`? It doesn't look like `sample.sample` uses any engine, so there shouldn't be any inherent parallelisation at the pyPESTO level and AMICI uses openMP parallelization at the C level, so I don't think the `pool` object is created by AMICI/pyPESTO and neither of them should do any passing between processes or pickling.

**Comment by shoepfl** [comment]
Regarding the argument, there are some examples with dynesty and multiprocessing however they also got a pickle error as it seems so maybe it is really the best way to use another pool.

So probably the problem is on the side of dynesty - I try to find a workaround there.

Thanks for your help!

**Comment by shoepfl** [comment]
Ok so I talked to [segasai](https://github.com/segasai) from dynesty and he said the multiprocessing pool works fine with dynesty. The problem is the wrapper of pypesto i.e. 

[(https://github.com/ICB-DCM/pyPESTO/blob/13ce29bfd32a5170284f0d7049ccffc7d1ad7b5d/pypesto/sample/dynesty.py#L134)]

which is not pickable and causes the error:

"AttributeError: Can't pickle local object 'DynestySampler.initialize..loglikelihood'"

is there another/pickable way for this? Parallelization would be very nice, especially for nested sampling.

**Comment by FFroehlich** [comment]
Ah, the likelihood object itself can be pickled (as long as it was created via petab), but the nested function definition cannot. This should be straightforward to fix by turning the nested function into a class method, right?

**Comment by shoepfl** [comment]
Yes this indeed already solved the issue.

I attached the code without nesting:
[dynesty.zip](https://github.com/ICB-DCM/pyPESTO/files/10956330/dynesty.zip)

like this dynesty can be used on multiple cores via multiprocessing, which I find very helpful.

Thanks for your help @FFroehlich @yannikschaelte

**Comment by dilpath** [comment]
> Yes this indeed already solved the issue.
> 
> I attached the code without nesting: [dynesty.zip](https://github.com/ICB-DCM/pyPESTO/files/10956330/dynesty.zip)
> 
> like this dynesty can be used on multiple cores via multiprocessing, which I find very helpful.
> 
> Thanks for your help @FFroehlich @yannikschaelte

Thanks a lot for the fix! Would you like to submit a PR to fix it? If not, I can, no problem.

Nice to hear about the parallelization! If you think this would be helpful for others, a PR or example in the docs would be appreciated! Otherwise, if you have an example script you could paste here, I could also do this.

**Comment by shoepfl** [comment]
Yes of course, I can do the PR and upload an example script here. I would also say this could be helpful in the docs as nested sampling needs a lot computational power most of the time.

**Comment by shoepfl** [comment]
Here is a minimal example of parallel nested sampling with dynesty using pyPESTO and a PEtab problem.

[Parallel_dynesty_in_pyPESTO.zip](https://github.com/ICB-DCM/pyPESTO/files/10959588/Parallel_dynesty_in_pyPESTO.zip)

Parallelization needs the installation of amici with hdf5 support and works with a multiprocessing pool.

**Comment by dilpath** [comment]
> Here is a minimal example of parallel nested sampling with dynesty using pyPESTO and a PEtab problem.
> 
> [Parallel_dynesty_in_pyPESTO.zip](https://github.com/ICB-DCM/pyPESTO/files/10959588/Parallel_dynesty_in_pyPESTO.zip)
> 
> Parallelization needs the installation of amici with hdf5 support and works with a multiprocessing pool.

Thanks! I've created a PR to doc this, in #1039 

I noticed in your script that you perform an optimization prior to sampling. It seems that dynesty cannot yet take advantage of such information (see https://github.com/joshspeagle/dynesty/issues/430 ), so you could remove that from your script, and remove `result=result` from your `sample.sample` call.

**Comment by shoepfl** [comment]
Yes, I know. However, I read in the docs that it might be used to get a good L_max for the stopping criterion in the future. So I just left it in as the optimization with just one start only takes a few seconds. But it's probably a good idea to comment on this to not get confused.

Thanks for the fast merge
