### ISSUE TITLE
Benchmarking Parameter Estimation Methods on biopredynbench Advice

### ISSUE THREAD

**Issue by Mjvolk3** [ICB-DCM/pyPESTO#1043]
I would like to be able to benchmark some parameter estimation methods we have developed against [biopredynbench](https://github.com/0u812/biopredynbench). I have been using PEtab, pyPESTO, and AMICI for all my development. The models from [biopredynbench](https://github.com/0u812/biopredynbench) have AMIGO, C, COPASI, Matlab, and SBML directories. I've been considering converting the COPASI files to PEtab filers to build the pyPESTO problem. Are you aware of a simpler way? Any suggestions would be appreciated. Thanks!

**Comment by yannikschaelte** [comment]
Given that you are already using AMICI, PEtab and pyPESTO, I agree that encoding the benchmark problems via PEtab is the way to go. Unfortunately it seems that in the repository you linked, not all formats provide the entire information, in particular the COPASI format provides the dynamics, but not the parameter estimation problem, which needs to be defined manually on the GUI. However e.g. the AMIGO one seems to do so. It should yet be straightforward to take e.g. the SBML model definition, and the parameter bounds from COPASI, and the objective function definition from wherever that is defined, and combine it to a PEtab problem.

BTW: If you are looking for benchmark problems, these here may be of interest to you -- a larger set of models already in PEtab format. https://github.com/Benchmarking-Initiative
