### ISSUE TITLE
Evaluating the symbolic form of AmiciObjective

### ISSUE THREAD

**Issue by Mjvolk3** [ICB-DCM/pyPESTO#1047]
I fear I might be missing something very simple, but when I have been running some parameter estimation schemes on one of my example models imported from PeTab, I have been getting negative objective evaluations. I have assumed that the optimization is of the sum of squared residuals, so I am unsure why there would be negative values.

$$L(x)=\Sigma\left(y_i i-f\left(x \_i\right)\right)^2$$

Is it possible to print out a symbolic form of the objective function? How can I know for certain that this function will be lower bounded by 0, meaning I am minimizing the sum of least squares? I've spent a good amount of time looking to do this, so I figure one of the experts could probably point me in the right direction. Thanks for your time.

**Comment by dweindl** [comment]
Hi @Mjvolk3, when importing a PEtab problem, the objective function value in pypesto will be the negative log-likelihood (and thus, can be negative). I guess this could be documented better in pypesto.

The actual symbolic equation is only easily available in the generated AMICI model files. By default they are located inside  `amici_models/` inside your current working directory. The loglikelihood (*not the negative* loglikelihood here) can be found in `*Jy.cpp`.
