### ISSUE TITLE
Ensemble predictions underestimate uncertainty

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#1069]
Hi,

I noticed that my ensemble predictions with 95 and 99% CI are quite narrow, even if there is a lot of 
uncertainty in my data. 

This uncertainty is also captured in the estimate of the sd (so in the error model/ likelihood).
However, by just forward simulating the paramter ensemble this uncertainty is missing somehow as the credibility intervalls
are quite narrow.

Do you have any suggestions to include this uncertainty?

Best,
Sebastian

**Comment by dilpath** [comment]
Hi Sebastian, the uncertainty in predictions is usually not expected to be the same as the uncertainty in data, so using the ensemble won't work, I think.

One way to do this is described here [1].

I'm not aware of an easy way to do this with pyPESTO's ensembles currently. I think one would need to construct an `EnsemblePrediction` manually, by using the `AmiciPredictor` to produce a single prediction result from a single vector (with `include_sigmay=True`), then adding noise to that result `n` times to produce an ensemble of `n` noisy predictions. The uncertainty in these predictions should then match the uncertainty you see in your data -- but this is trivial, and the uncertainty in your model is not seen in these predictions anymore.



[1] https://github.com/ICB-DCM/pyPESTO/blob/main/doc/example/synthetic_data.ipynb

**Comment by shoepfl** [comment]
Hi Dilan,

thanks for your comment. You are right I should distinguish between the model uncertainty and the uncertainty in the data.

The way you discribed for the uncertainty in my data will also work for me I think.

Thanks again!
