### ISSUE TITLE
objectivePriorParameters

### ISSUE THREAD

**Issue by Mjvolk3** [ICB-DCM/pyPESTO#1078]
`objectivePriorParameters` would it be possible to provide more description of this variable in the Parameter Table? I could not grasp its meaning from the [docs](https://petab.readthedocs.io/en/latest/documentation_data_format.html#id2). Thanks.

Whoops, realizing now this probably belongs in [PEtab](https://github.com/PEtab-dev/PEtab.)

**Comment by dweindl** [comment]
Hi @Mjvolk3, 

PEtab has two types of priors:

1. for sampling initial points for optimization
2. as priors to compute the posterior as objective during sampling or optimization

They are controlled via `initializationPriorType`/`initializationPriorParameters` or `objectivePriorType`/`ojectivePriorParameters`, respectively.

`{initialization,objective}PriorType` are used to choose the type of prior distribution (e.g. uniform or normal - see [1] for all options), and `{initialization,objective}PriorParameters` are used to set the relevant distribution parameters.

For example:

| objectivePriorType | ojectivePriorParameters |                                                                       |
|--------------------|-------------------------|-----------------------------------------------------------------------|
| normal             | 0;2                    | <-- $\mathcal{N}(0,2^2)$ --- a normal distribution with mean 0 and standard deviation 2       |
| uniform            | -100;100                | <-- $\mathcal{U}(-100, 100)$ --- a uniform distribution with lower bound -100 and upper bound 100  |

[1] https://petab.readthedocs.io/en/latest/documentation_data_format.html#parameter-table

**Comment by Mjvolk3** [comment]
Looking over the possible prior types makes it more clear. I guess I was looking for the explicit form to make sure I'm not fooling myself. I believe it to be:

$$
\pi(D \mid Y, \Sigma, \theta)=\pi(\theta) \prod_i \pi\left(m_i \mid y_i, \sigma_i, \theta\right)
$$

Where $\theta$ are model parameters, the prior specified by `objectivePriorType` and `objectivePriorParameters` is $\pi(\theta)$. Do you agree?

Also, I will pick your 🧠 if you don't mind. If you have a bunch of data say around one parameter in the model from literature it seems to me that you could implement either `initializationPriorType`/`initializationPriorParameters` or `objectivePriorType`/`objectivePriorParameters`. Say you model the data around this parameter as normal. Then you could either sample more frequently around this normal within the `initialization` or you could weight the `objective` by the prior. It seems the `initialization` route more conservative vs. the `objective` method and that the `initialization` method would allow you to still discover feasible solutions near the tails of the distribution, whereas the `objective` weighting method wouldn't since the tails would be down weighted so much. You views on this would be greatly appreciated, or if you have a nice resource to share that would also be helpful.

Also, @dweindl, you have now answered many of my comments and I would just say thanks, it has been very helpful! Cheers.

**Comment by dweindl** [comment]
> Where θ are model parameters, the prior specified by `objectivePriorType` and `objectivePriorParameters` is π(θ). Do you agree?

Agreed.

 
> If you have a bunch of data say around one parameter in the model from literature it seems to me that you could implement either `initializationPriorType`/`initializationPriorParameters` or `objectivePriorType`/`objectivePriorParameters`. Say you model the data around this parameter as normal. Then you could either sample more frequently around this normal within the `initialization` or you could weight the `objective` by the prior. 

Yes. Although, IIRC, the main idea behind the separate `initializationPrior` was to avoid initializing optimizers too close to the parameter bounds, which often causes trouble. 

> It seems the `initialization` route more conservative vs. the `objective` method and that the `initialization` method would allow you to still discover feasible solutions near the tails of the distribution, whereas the `objective` weighting method wouldn't since the tails would be down weighted so much.

I am not sure if we can make any general statements here. 
You could use your normal prior for initialization and for the objective, or a uniform initialization prior with the normal objective prior, or vice verse. The first two will give you a maximum a posteriori estimate, the latter a maximum likelihood estimate. Using the normal objective prior and a uniform initialization prior will probably lead to better exploration of the parameter space.


When trying to use `initializationPrior`, mind https://github.com/ICB-DCM/pyPESTO/issues/1017.
