### ISSUE TITLE
Default startpoint method, hierarchically optimized parameters

### ISSUE THREAD

**Issue by Doresic** [ICB-DCM/pyPESTO#1096]
Connected to this PR https://github.com/ICB-DCM/pyPESTO/pull/1093
A possible issue with the new implementation of  ` startpoint_method ` in pypesto. 

When not assigning the standpoint method, it will default into the `self.create_startpoint_method()` (petab sampling) while creating problem, and will not default into the `uniform` one from pypesto anymore.

In case of hierarchically optimized noise, the `uniform` startpoint method was sampling correctly only non-hierarchically optimized parameters (in case of Boehm with hierarchically optimized noise, that was 6). But the petab sampling will sample all parameters in the parameter df with estimate==1, so including the noise (9 parameters). I can imagine this occurring with any hierarchically optimized parameters.

This then breaks when appending the sampled startpoints at https://github.com/ICB-DCM/pyPESTO/blob/9a754573a7b77d30d5dc1f67a8dc1be6c29f1640/pypesto/startpoint/base.py#L104C20-L104C20

Not sure what's the best fix. Is it better if create_startpoint_method defaults into uniform, as it did in the pypesto.optimize.minimize() function? (not sure if this breaks something else)

**Comment by dweindl** [comment]
You are right, that case is not properly handled. It's concerning that zero tests failed. :thinking: 

> Is it better if create_startpoint_method defaults into uniform, as it did in the pypesto.optimize.minimize() function?

For any PEtab import, it should use what is specified in the PEtab problem. As this is mandatory in PEtab, we don't need any default there. In fact, a reason for #1093 was that so far, the PEtab settings for startpoint sampling would have been easily ignored.

> Not sure what's the best fix.

I'd say `PetabImporter.create_startpoint_method` should get a parameter IDs or parameter indices argument (optional, default to all parameters), that needs to be passed appropriately here: https://github.com/ICB-DCM/pyPESTO/blob/c7a88ead25385b043e0dea1a9b46a3bb4719c796/pypesto/petab/importer.py#L743
Would that address your concerns?
