### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#11]
- [x] pyMC3 https://docs.pymc.io
- [ ] pymcmcstat https://github.com/prmiles/pymcmcstat

**Comment by yannikschaelte** [comment]
in this context, we should consider also https://arxiv.org/pdf/1712.06006.pdf

**Comment by yannikschaelte** [comment]
next goal: provide some basic implementation of (pymc3?) sampling

**Comment by paulstapor** [comment]
Obviously, pyMC3 seems a good choice. As this is maybe currently not straight forward to implement, how about a replacement for the moment?
Might https://github.com/prmiles/pymcmcstat be an Option?

**Comment by FFroehlich** [comment]
Sounds like a reasonable first option to establish some basic support.

**Comment by FFroehlich** [comment]
http://docs.pyro.ai/en/0.2.1-release/mcmc.html

**Comment by yannikschaelte** [comment]
pymcmcstat still open

**Comment by yannikschaelte** [comment]
As I find pymcmcstat rather hard to use from the available documentation, I would not pursue this further here. If someone wants to give it a try, feel free. Closing here for the moment.
