### ISSUE TITLE
How to define Custom Objective to be optimized

### ISSUE THREAD

**Issue by Toluwa-okunola** [ICB-DCM/pyPESTO#1101]
Hi. Is it possible to define a custom objective function to be optimized with pypesto? If yes, how can I do that and does the function have to be continuous?  Thanks.

**Comment by yannikschaelte** [comment]
Hi @Toluwa-okunola , yes you can use pypesto with a custom objective function, see this example notebook: https://pypesto.readthedocs.io/en/latest/example/custom_objective_function.html

Note that for some interpretations, it is useful if the objective function bears interpretation of being a (log-) likelihood or posterior, but that is not required e.g. for simple optimization.

The objective should be a continuous inference problem, as pyPESTO's algorithms are designed for only such problems.
