### ISSUE TITLE
PEtab import & missing `nominalValue`

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#1104]
`nominalValue` in the [PEtab parametesr table](https://petab.readthedocs.io/en/latest/documentation_data_format.html#parameter-table) is

> Optional, unless estimate==0. 

However, `PetabImporter.create_problem` problems fails if `nominalValue` is missing, even if all parameters are estimated (see below).

Either pypesto needs to check if nominal values are provided in the PEtab files, or `petab.Problem.x_nominal_scaled` has to be changed to return NaNs in that case. Not sure what's preferable. 

```python
File ~/src/pyPESTO/pypesto/petab/importer.py:680, in PetabImporter.create_problem(self, objective, x_guesses, problem_kwargs, **kwargs)
    658 """Create a :class:`pypesto.Problem`.
    659 
    660 Parameters
   (...)
    677     A :class:`pypesto.Problem` for the objective.
    678 """
    679 if objective is None:
--> 680     objective = self.create_objective(**kwargs)
    682 x_fixed_indices = self.petab_problem.x_fixed_indices
    683 x_fixed_vals = self.petab_problem.x_nominal_fixed_scaled

File ~/src/pyPESTO/pypesto/petab/importer.py:437, in PetabImporter.create_objective(self, model, solver, edatas, force_compile, **kwargs)
    432 par_ids = self.petab_problem.x_ids
    434 # fill in dummy parameters (this is needed since some objective
    435 #  initialization e.g. checks for preeq parameters)
    436 problem_parameters = dict(
--> 437     zip(self.petab_problem.x_ids, self.petab_problem.x_nominal_scaled)
    438 )
    439 amici.parameter_mapping.fill_in_parameters(
    440     edatas=edatas,
    441     problem_parameters=problem_parameters,
   (...)
    444     amici_model=model,
    445 )
    447 calculator = None

File ~/src/PeriNAA/env/lib/python3.11/site-packages/petab/problem.py:687, in Problem.x_nominal_scaled(self)
    684 @property
    685 def x_nominal_scaled(self) -> List:
    686     """Parameter table nominal values with applied parameter scaling"""
--> 687     return self.get_x_nominal(scaled=True)

File ~/src/PeriNAA/env/lib/python3.11/site-packages/petab/problem.py:663, in Problem.get_x_nominal(self, free, fixed, scaled)
    644 def get_x_nominal(self, free: bool = True, fixed: bool = True,
    645                   scaled: bool = False):
    646     """Generic function to get parameter nominal values.
    647 
    648     Parameters
   (...)
    661     The parameter nominal values.
    662     """
--> 663     v = list(self.parameter_df[NOMINAL_VALUE])
    664     if scaled:
    665         v = list(parameters.map_scale(
    666             v, self.parameter_df[PARAMETER_SCALE]))

File ~/src/PeriNAA/env/lib/python3.11/site-packages/pandas/core/frame.py:3761, in DataFrame.__getitem__(self, key)
   3759 if self.columns.nlevels > 1:
   3760     return self._getitem_multilevel(key)
-> 3761 indexer = self.columns.get_loc(key)
   3762 if is_integer(indexer):
   3763     indexer = [indexer]

File ~/src/PeriNAA/env/lib/python3.11/site-packages/pandas/core/indexes/base.py:3654, in Index.get_loc(self, key)
   3652     return self._engine.get_loc(casted_key)
   3653 except KeyError as err:
-> 3654     raise KeyError(key) from err
   3655 except TypeError:
   3656     # If we have a listlike key, _check_indexing_error will raise
   3657     #  InvalidIndexError. Otherwise we fall through and re-raise
   3658     #  the TypeError.
   3659     self._check_indexing_error(key)

KeyError: 'nominalValue'
```

**Comment by dweindl** [comment]
> Either pypesto needs to check if nominal values are provided in the PEtab files, or `petab.Problem.x_nominal_scaled` has to be changed to return NaNs in that case. Not sure what's preferable.

On second thought: I would think PEtab should return NaNs in that case. This is what happens if an empty `nominalValue` column exists. The current PEtab specification isn't super clear on whether the column is optional, or whether the column is required but may be empty.

Other opinions?

**Comment by PaulJonasJost** [comment]
Also in favour of NaN 👍🏼 But if I recall correctly, if it is not specified, the value will be set to the one specified in the sbml am I correct? Should we raise an info or warning for this?

**Comment by dweindl** [comment]
> But if I recall correctly, if it is not specified, the value will be set to the one specified in the sbml am I correct? Should we raise an info or warning for this?

From the PEtab side, `nominalValue` is required, unless the parameter is estimated. Since PEtab is only concerned with parameter estimation, any missing `nominalValue` for estimated parameters doesn't matter.

Anything beyond that is undefined. E.g. what is supposed to happen if one just wants to simulate the underlying model with the (missing) nominalValues. The most plausible thing to do, would probably be using the default value from the model, agreed. However, the parameters introduced only in the PEtab files will not have any default value.

**Comment by dweindl** [comment]
Fixed via https://github.com/PEtab-dev/libpetab-python/pull/223, I'd say.
