### ISSUE TITLE
waterfall plot y limits not working

### ISSUE THREAD

**Issue by m-philipps** [ICB-DCM/pyPESTO#1108]
It is not always possible to set the y limits of a waterfall plot using the `y_limits` argument, because
this condition:

https://github.com/ICB-DCM/pyPESTO/blob/2eb0d15f4aa636f873785a3c1e9e7afce281755f/pypesto/visualize/misc.py#L173

needs to be fulfilled in order to reach this line:

https://github.com/ICB-DCM/pyPESTO/blob/2eb0d15f4aa636f873785a3c1e9e7afce281755f/pypesto/visualize/misc.py#L189

**Comment by m-philipps** [comment]
Does it make sense to set the same y limits for the zoomed-in starts? 

https://github.com/ICB-DCM/pyPESTO/blob/2eb0d15f4aa636f873785a3c1e9e7afce281755f/pypesto/visualize/waterfall.py#L170-L173

I would suggest to choose the y limits automatically here, i.e. use `y_limits=None` in the call above

**Comment by dweindl** [comment]
> It is not always possible to set the y limits of a waterfall plot using the `y_limits` argument, because

I'd say that's an identation bug at https://github.com/ICB-DCM/pyPESTO/blob/2eb0d15f4aa636f873785a3c1e9e7afce281755f/pypesto/visualize/misc.py#L188-L189 
Dedenting those lines solves the issue, right?

> Does it make sense to set the same y limits for the zoomed-in starts?

Probably not. Letting matplotlib choose limits sounds plausible.
