### ISSUE TITLE
Parameter order in parameters plot

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#111]
I always find it confusing that the parameters in the parameter plot are in the reverse order of `problem.x_names`.

**Comment by yannikschaelte** [comment]
oh, never noticed. @DantongWang can you look into this?

**Comment by paulstapor** [comment]
@DantongWang : Did you already work on that?
If not: I could take care of that on the feature_plotting branch...

**Comment by DantongWang** [comment]
no, haven't worked yet. Would be great that you can take care of it.
