### ISSUE TITLE
Saving of result object

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#113]
It would be desirable to be able to save the whole result object (apart from non-numerical stuff in result.problem. For these,  ``__rep__`` should be implemented to get at least a textual description). I propose using a SQL Database for this aim, since simply DataFrames (e.g. via numpy or pandas) have too flat a structure, and it is difficult efficiently saving large matrices there.

In addition, saving result parts (e.g. the final parameters) as human-readable csv files should be implemented.

Any opinions?

**Comment by yannikschaelte** [comment]
Basically implemented storage to SQLite now, seems to work (also able to reconstruct the result object from file).

**Comment by FFroehlich** [comment]
Hmm, isn't SQLite bad in combination with parallelization?

**Comment by yannikschaelte** [comment]
Hm, good point. You mean if ones creates separate files per multistart, then that is better to parallelize?

Definitely. I had planned the saving of objects to only take place at the end of the multistarts, in the master process, once all results are collected. Of course, it would also be possible to save results in the master branch iteratively whenever a worker has finished.

**Comment by dweindl** [comment]
Does SQLite work out of the box on windows?

**Comment by yannikschaelte** [comment]
yes, so far never had problems.

**Comment by dweindl** [comment]
Not sure what exactly will go in, but if it is about vector/matrix storage, I'd rather go for hdf5. Besides that, no strong opinion.

**Comment by yannikschaelte** [comment]
closing as overriden by #241, #244, #255
