### ISSUE TITLE
Uncertainty estimation via profiling or sampling results in unresponsive Jupyter notebook

### ISSUE THREAD

**Issue by GiacomoFabrini** [ICB-DCM/pyPESTO#1159]
**Bug description**
Uncertainty estimation via profiling (`pypesto.profile.parameter_profile`) or sampling (`pypesto.sample.sample`) results in unresponsive Jupyter notebook and need for python kernel restart.

**Expected behavior**
Correct termination of calculations without Jupyter notebook page becoming unresponsive.

**To reproduce**
Tested using the Jupyter notebook amici.ipynb found in doc/example/, on a MacBook Pro with M2 Max (12 CPU cores, 30 GPU cores) and 32 GB RAM. 
For profiling, not specifying `engine` in  `pypesto.profile.parameter_profile` results in unresponsiveness. Specifying the engine works completely fine.
For sampling, `pypesto.sample.AdaptiveMetropolisSampler()` was used as sampler. `n_samples = 1000` works fine, but `n_samples = 2000` or higher result in complete unresponsiveness (cells cannot be selected, page scrolling results in entire portions of the page turning blank). Printout mentions issues with threading.py, iostream.py and zmq/sugar/socket.py. 

**Environment**
- Operating system: macOS 14.1 (23B74)
- `pypesto` version: 0.3.3
- Python version: 3.9.6

**Comment by dweindl** [comment]
Hi @GiacomoFabrini, 

>unresponsive Jupyter notebook and need for python kernel restart

How long did you wait before restarting? 

>  For profiling, not specifying engine in pypesto.profile.parameter_profile results in unresponsiveness. Specifying the engine works completely fine.

Did I get this right: If you don't specify the `engine` argument (i.e. without any parallelization) it becomes unresponsive, whereas when using `engine = pypesto.engine.MultiProcessEngine()` (i.e. using all cores) everything works?

**Comment by GiacomoFabrini** [comment]
Hi @dweindl, 

Thanks for looking into this!

> How long did you wait before restarting?

Just tested this. For estimation via sampling, n_samples = 2000/3000 do make the notebook unresponsive, but only temporarily: the calculation completed in about 40-45 s/2 min, respectively, i.e. the Jupyter notebook became responsive again after that timeframe and I could plot the parameter distributions. 
However, with n_samples = 5000 the calculation did not complete at all, rather it forced the notebook to reload (I found it back to the previous checkpoint). Any idea what is happening? 

> Did I get this right: If you don't specify the engine argument (i.e. without any parallelization) it becomes unresponsive, whereas when using engine = pypesto.engine.MultiProcessEngine() (i.e. using all cores) everything works?

You are correct, but this is only the case for the estimation via profiling, not for sampling.

**Comment by dweindl** [comment]
Thanks for clarifying. I am able to reproduce the sampling issue. 

```
[thousands of lines omitted]
zmq.error.ZMQError: Too many open files
Exception in thread Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-6907 (flush_main), started daemon 139921294653120)>>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1047, in _bootstrap_inner
    self._invoke_excepthook(self)
  File "/usr/lib/python3.11/threading.py", line 1359, in invoke_excepthook
      File "/lib/python3.11/site-packages/ipykernel/iostream.py", line 575, in flush
    self.pub_thread.schedule(self._flush)
  File "/lib/python3.11/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/ipykernel/iostream.py", line 145, in _event_pipe
      File "/lib/python3.11/site-packages/zmq/sugar/context.py", line 362, in socket
      File "/lib/python3.11/site-packages/zmq/sugar/socket.py", line 159, in __init__
    super().__init__(
  File "zmq/backend/cython/socket.pyx", line 332, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/ipykernel/iostream.py", line 575, in flush
    self.pub_thread.schedule(self._flush)
  File "/lib/python3.11/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/ipykernel/iostream.py", line 145, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/zmq/sugar/context.py", line 362, in socket
    s: ST = socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/zmq/sugar/socket.py", line 159, in __init__
    super().__init__(
  File "zmq/backend/cython/socket.pyx", line 332, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
100%|██████████| 5000/5000 [00:13<00:00, 373.18it/s]
Elapsed time: 15.867320734
```

However, I don't think it's related to pypesto, but rather jupyter. Running the same code as a regular Python script doesn't cause any issue.

Looks similar to https://github.com/jupyterlab/jupyterlab/issues/6727

Finding the right combination of ipython/zmq/... might make it work.

**Comment by dweindl** [comment]
@GiacomoFabrini after trying a variety of environments, it seems like `ipykernel>=6.23.2` is the problem. Please run
 `python -m pip install -U ipykernel==6.23.1` and retry.
 

<details><summary>full environment</summary>
<p>


amici==0.19.0
anyio==4.0.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.1.0
Babel==2.13.1
beautifulsoup4==4.12.2
bleach==6.1.0
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.1
cloudpickle==3.0.0
cmake==3.27.7
cmake-build-extension==0.5.1
colorama==0.4.6
comm==0.1.4
contourpy==1.1.1
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
executing==2.0.1
fastjsonschema==2.18.1
fides==0.7.8
fonttools==4.43.1
fqdn==1.5.1
gitdb==4.0.11
GitPython==3.1.40
h5py==3.10.0
idna==3.4
ipykernel==6.23.1
ipython==8.17.2
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
jupyter-events==0.8.0
jupyter-lsp==2.2.0
jupyter_client==8.5.0
jupyter_core==5.5.0
jupyter_server==2.9.1
jupyter_server_terminals==0.4.4
jupyterlab==4.0.7
jupyterlab-pygments==0.2.2
jupyterlab_server==2.25.0
kiwisolver==1.4.5
MarkupSafe==2.1.3
matplotlib==3.8.0
matplotlib-inline==0.1.6
mistune==3.0.2
more-itertools==10.1.0
mpmath==1.3.0
nbclient==0.8.0
nbconvert==7.10.0
nbformat==5.9.2
nest-asyncio==1.5.8
ninja==1.11.1.1
notebook==7.0.6
notebook_shim==0.2.3
numpy==1.26.1
overrides==7.4.0
packaging==23.2
pandas==2.1.2
pandocfilters==1.5.0
parso==0.8.3
petab==0.2.4
pexpect==4.8.0
Pillow==10.1.0
platformdirs==3.11.0
prometheus-client==0.18.0
prompt-toolkit==3.0.39
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
pyparsing==3.1.1
pypesto==0.3.3
python-dateutil==2.8.2
python-json-logger==2.0.7
python-libsbml==5.20.2
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.30.2
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.10.6
scipy==1.11.3
seaborn==0.13.0
Send2Trash==1.8.2
setuptools-scm==8.0.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
terminado==0.17.1
tinycss2==1.2.1
toposort==1.10
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
tzdata==2023.3
uri-template==1.3.0
urllib3==2.0.7
wcwidth==0.2.9
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.4
wurlitzer==3.0.3


</p>
</details>

**Comment by GiacomoFabrini** [comment]
@dweindl Just tried and the calculation completed with no issues and very quickly! (tens of seconds for 10000 samples) Thanks Daniel, really appreciate this!
