### ISSUE TITLE
PetabImporter: Allow replicates

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#122]
Currently (see https://github.com/ICB-DCM/pyPESTO/blob/develop/pypesto/objective/petab_import.py#L201), if there are multiple replicates for an observable in a simulation condition, I guess only the last one is passed to the amici.ExpData. I guess that it should be possible to pass timepoints multiple times to the ExpData, i.e. to create a larger table, in which all data points can be filled, having nans for non-existing replicates.

Some of the Benchmark models, e.g. Schwen, require this.

**Comment by dweindl** [comment]
... or at least fail if anything is overriden.

**Comment by yannikschaelte** [comment]
Implemented it now in #123 such that failures are not necessary, but the data table is just enlarged accordingly and all data points are filled in iteratively
