### ISSUE TITLE
pypesto.profile.profile_next_guess.get_reg_polynomial correct?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#1224]
Hi, can somebody comment on whether the following code makes sense?

This is polynomial regression to extrapolate parameter values for parameter profiles in the adaptive stepsize case. 

https://github.com/ICB-DCM/pyPESTO/blob/223859ebff5ba9dfeb3c18f25383f359ef0840bb/pypesto/profile/profile_next_guess.py#L355-L372

In the ill-conditioned case, different parameter vectors are used than in the initial attempt. They don't include the most recent parameters. This seems wrong to me, but maybe somebody knows better.

EDIT: Well, actually both cases seem to be wrong. Both use only `reg_points - 1` points instead of the presumably intended `reg_points`. In the first case, the oldest one is omitted, in the second case the most recent one is omitted.

What I think it should look like: https://github.com/ICB-DCM/pyPESTO/pull/1226

**Comment by PaulJonasJost** [comment]
agreed, this should be changed 👍🏼
