### ISSUE TITLE
PetabImporter: Handle observable scale

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#124]
Pass observable scale like lin, log, log10 as specified in measurement_file to amici (amici can do that, right? or do we have to apply the transformation manually beforehand?)

the way to go would probably be to either pass an additional table to the AmiciObjective, or just apply the mapping on each data point in PetabImporter.create_edatas beforehand.

**Comment by FFroehlich** [comment]
Nope, currently there is no observable scale in amici.

**Comment by yannikschaelte** [comment]
done now via #159, amici 0.10.4 and petab 0.0.0a12
