### ISSUE TITLE
doc/example/store.ipynb timeout

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#1286]
There seems to be huge a variation in the run time of `doc/example/store.ipynb`. 
e.g., https://github.com/ICB-DCM/pyPESTO/actions/runs/7545948032/job/20542665352: `real	16m21.468s` 

Let's see if this happens more frequently...

**Comment by PaulJonasJost** [comment]
No frequent timeout detected by me as of recently. Will close.
