### ISSUE TITLE
Default location for AMICI model files

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#129]
When compiling an amici model in petab, the default location is currently ``./tmp/MODEL_NAME``. One might replace tmp by ``amici_models`` or something like that, since it is not really temporary files.

When doing so, also make sure to catch the folders in the gitignore.

**Comment by dweindl** [comment]
Thought about similar issues a couple of times. Not sure what would be a good choice for the model location.

- home directory: annoying
- system temp: will be gone after reboot. not sure if that is what is generally desired, especially for larger models with significant processing time.
- pypesto package directory:
  In case of system-wide installation probably not writeable, in other cases usually in some obscure path
- always asking for a path? inconvenient
- current directory?

**Comment by yannikschaelte** [comment]
I would go for current directory or home directory. The latter might be not always possible, but other tools also write folders to home, so that would not be too annoying.

**Comment by dweindl** [comment]
There are few things I hate more programs littering my home directory. Current directory, okay.

**Comment by yannikschaelte** [comment]
now put to ``amici_models`` in working directory. done in #147.
