### ISSUE TITLE
Loading result from hierachical optimisation results in `AttributeError`

### ISSUE THREAD

**Issue by arrjon** [ICB-DCM/pyPESTO#1309]
**Bug description**
When loading a result object from hierachical optimisation and calling `plot_splines_from_pypesto_result` this results in
`AttributeError: 'Objective' object has no attribute 'calculator'` even though it worked when working with the original results object.

**Expected behavior**
After loading a result object plotting functions should still work. If think this is related to #1308.

**To reproduce**
Minimal example using the example_semiquantitative petab problem:
[minimal_example.py.zip](https://github.com/ICB-DCM/pyPESTO/files/14385803/minimal_example.py.zip)
Run the script twice: first to produce a result object and store it. Everything works as expected.
Rerun it, this will create the problem in the same way, but it will load the result object instead of creating it.
The error  appears then in the last function call.

**Environment**
- Operating system: macOS 14.3.1
- `pypesto` version: todays develop branch
- Python version: Python 3.9.6

**Comment by dweindl** [comment]
This is expected and unrelated to hierarchical optimization. See also [this example](https://pypesto.readthedocs.io/en/latest/example/store.html#2.-Storing-the-result-file). The objective is not saved. You should have seen a warning when loading from file. If not, this might be due to #1252 (fixed in amici>=v0.21.0).

**Comment by arrjon** [comment]
I thought I reloaded the problem, but it turns out I forgot to assign it to the result. Thanks!
