### ISSUE TITLE
Disentangle petab from pypesto

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/pyPESTO#134]
pyPESTO should have as minimal requirements as possible: I can think of quite some cases, in which we might want to use pyPESTO without PEtab (which needs libsbml, which can in turn be problematic), so these things should not be necessarily linked.  In order to make pyPESTO usable also for non-AMICI and non-PEtab-users, we need to unlink those two things.

**Comment by yannikschaelte** [comment]
I'd suggest treating it exactly the way amici is treated, i.e. checking imports always and moving it to ``extras_require`` in setup.py. This should only affect few files, so be little overhead.
