### ISSUE TITLE
Frequent timeouts of RTD builds

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#1362]
Since 2 days, there are frequent timeouts for pypesto documentation builds on RTD. Not sure what's causing this, but I guess we'll have to reduce build time somehow.

**Comment by dweindl** [comment]
Seems to be okay again :man_shrugging:

**Comment by PaulJonasJost** [comment]
I was thinking whether switching from autodoc to autoapi might help 🤔 had it occurring once last week again as well

**Comment by dweindl** [comment]
> whether switching from autodoc to autoapi might help

I don't think so. Everything besides installing dependencies and running the notebooks is rather insignificant.
