### ISSUE TITLE
Frequent timeouts for `mac (3.11)` workflow runs

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#1383]
There are currently frequent timeouts for `mac (3.11)` workflow runs. 

The by far [slowest](https://github.com/ICB-DCM/pyPESTO/actions/runs/8782850154/job/24097808694#step:6:240) test is:
 `239.30s call     test/sample/test_sample.py::test_thermodynamic_integration`

Can this be reduced to <1min?

**Comment by PaulJonasJost** [comment]
it reliably times out at `test/profile/test_validation_intervals.py` from what I could see. will have a look 👍🏼

**Comment by dweindl** [comment]
> The by far [slowest](https://github.com/ICB-DCM/pyPESTO/actions/runs/8782850154/job/24097808694#step:6:240) test is:
> `239.30s call test/sample/test_sample.py::test_thermodynamic_integration`

I take that back. This, as well as the timeouts in general, was a consequence of the issue addressed in #1388. 
After fixing that, the duration is okayish:
`35.52s call     test/sample/test_sample.py::test_thermodynamic_integration`

**Comment by PaulJonasJost** [comment]
I think this should be fixed right now.
