### ISSUE TITLE
Frequent readthedocs timeout

### ISSUE THREAD

**Issue by PaulJonasJost** [ICB-DCM/pyPESTO#1396]
At least in my recent experience, a lot of times readthedocs seams to time out during building process. Something to keep track about.

**Comment by dweindl** [comment]
This is mostly about the increasing number of notebooks. They should be as simple and orthogonal as possible. And use cheap models as far as possible.

**Comment by PaulJonasJost** [comment]
again facing frequent timeout. Will go through the notebooks and look into it, also looking into #1460

**Comment by PaulJonasJost** [comment]
closing this for now until the timeout problem arises again
