### ISSUE TITLE
Lots of warnings in test suite

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#1425]
Currently, there are way too many warnings issued in the test suite:

base: 570 warnings
optimize: 53 warnings
hierarchical: 27 warnings
select: 205 warnings
petab: 40 warnings

Some are from third-party libraries, but many are from pypesto.

Those that can be prevented should be prevented.
The expected ones should be filtered out by the tests.

**Comment by PaulJonasJost** [comment]
addressed base in #1430

**Comment by PaulJonasJost** [comment]
closing with #1430 until more warning pop up again.
