### ISSUE TITLE
petab_import ignores amici version

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#143]
petab_import.create_model only checks whether the model has been compiled, not wether amici version of the model is still compatible with the current amici version.

**Comment by yannikschaelte** [comment]
I guess in that case, things will currently just fail cause amici throws an error. Would definitely be nicer to check version here and in that case immediately recompile. How can one find out the amici version used in a model?

**Comment by FFroehlich** [comment]
http://icb-dcm.github.io/AMICI/classamici_1_1_abstract_model.html#ae1d68e13dc35252f74b0a1f2601cd453

**Comment by yannikschaelte** [comment]
If I look at the current implementation in AMICI, it looks like a RuntimeError will be thrown every time one tries to even import the module. Is that intended? That exception can of course be caught at the moment and the model recompiled, but this could probably be done nicer.

**Comment by FFroehlich** [comment]
🤔  I think thats intended. You really don't want to work with different model/amici versions. Thinking about it, you are probably not even guaranteed that model->getAmiciVersion() will run or give you the right result, so catching that RuntimeError is probably your only option.

**Comment by yannikschaelte** [comment]
done in #147
