### ISSUE TITLE
Fitting reduced kinetic data (without time)

### ISSUE THREAD

**Issue by devoncallan** [ICB-DCM/pyPESTO#1449]
Hello, I am considering the conversion of two observable species A and B (different from the test conversion in the example as there are a few other species involved). I have created the model in SBML, created simulated conversion data for PEtab using AMICI, and I am able to use pyPESTO to fit a set of 4 kinetic parameters to A/B conversion vs. time data (see left plot). However, it is common in my field to fit reduced kinetic parameters (ratios of rate constants) to reduced kinetic data in the form of B conversion vs. A conversion (see right plot). 

This is probably not the best practice, but I can't figure out if it is possible to specify a parameter estimation problem in this way using pyPESTO/PEtab? I am curious to compare the methods.

Side note: I've really enjoyed using pyPESTO so far, and I'm excited to keep using it – it's a great tool :)

![image](https://github.com/user-attachments/assets/d84b134a-b1cf-4603-98c6-c29612da2ae9)

**Comment by m-philipps** [comment]
Hi @devoncallan, it's nice to hear that you had a good experience!

Do you want to visualize the ratio, or a also use it for parameter estimation?

It sounds like what you're looking for is another observable in the PEtab problem that describes the ratio of rate constants. The PEtab reference [1] indicates that the `observableFormula` can "contain any symbol defined in the SBML model (including model time time) or parameter table."
Can your ratio be expressed in terms of those?

To facilitate simulation with AMICI, you could consider making the ratio a species in your SBML model, then the PEtab observable can refer to that new species as the `observableFormula`.

[1] https://petab.readthedocs.io/en/stable/documentation_data_format.html#observables-table

**Comment by devoncallan** [comment]
Hi @m-philipps, thank you so much for your quick response! I apologize – I explained my issue poorly originally. My current measurement data for pyPESTO/PEtab is a few experiments of A and B conversion vs. time (left plot, one experiment shown). The SBML model will simulate in time, and A and B conversion will be outputs in the SBML model and observables in the PEtab. Then I use this data in pyPESTO to estimate my kinetic parameters.

However, I am wondering if it is possible to fit data that is not expressed directly as a function of time. In my case, I would like to be able to fit A conversion vs. B conversion (right plot, no time) as if B conversion was the independent variable (instead of time). For example, in the PEtab measurements table, this data could potentially be expressed as "measurement": A conversion, and "time": B conversion? However, I can imagine this would create some major problems for pyPESTO. If this is possible, I'm not sure if it would be best expressed in the PEtab format, or if there's some way to handle this in pyPESTO. 

This is definitely a reduction of information in expressing the data like this, which is why I was considering using ratios of kinetic parameters, but I have been able to express those using assignment rules in SBML. 

Thank you for your help!

**Comment by FFroehlich** [comment]
Hi @devoncallan, this kind of problem formulation is not directly available in PEtab. However, I think it should be possible to achieve this with event assignments where you add an sbml species per observed data point and assign the value of A when B surpasses the measured value. You use these species in petab observables. I would probably compare them at timepoint inf, but this might require setting some additional status flag in amici.

**Comment by devoncallan** [comment]
Hi @FFroehlich, thank you for your reply! I might look into your suggestion in the future, but good to know that it is not directly supported in PEtab.
