### ISSUE TITLE
Reference points not using legend

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#153]
As pointed out by codacy, the legend argument in pypesto.visuaulize.create_references is unused, probably a bug. https://github.com/ICB-DCM/pyPESTO/blob/develop/pypesto/visualize/reference_points.py#L137

**Comment by paulstapor** [comment]
wait... It worked on the rosenbrock-example-notebook when I merged it. Are you sure?

**Comment by paulstapor** [comment]
Ah, got it. Sorry, will fix that, but that's super-straight forward... Just pass it to the reference point constructor...
