### ISSUE TITLE
Optimizer traces not working as intended for models with high number of parameters

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#162]
most of the stored `x` array will be shortened by '...'

**Comment by yannikschaelte** [comment]
ah that's probably due to storing numpy arrays in a single pandas cell. I thought that shortening was only for visualization.

**Comment by yannikschaelte** [comment]
@FFroehlich do your recent changes address this sufficiently?

**Comment by FFroehlich** [comment]
Yes
