### ISSUE TITLE
Implement Hierarchical Optimization

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#167]
As started in some (little bit stale) branch already, implement hierarchical optimization covering a few standard settings (scalings, offsets, sigmas), using forward and adjoint sensis.

The idea is to define an HierarchicalAmiciCalculator, which hops inside the amici_objective call function, and which performs the actual calculation of llh, sllh, etc., and which in the default case, without static, i.e. hierarchical. parameters, just calls amici, but which can inside the amici_objective be replaced by a Calculator which does hierarchical optimization in different ways.

This way should be minimum invasive and transparent too. Will be easy to define the hierarchical problem using petab. Should also be possible to generalize to apply an ordinal hierarchical problem.

**Comment by dweindl** [comment]
There are currently 4 rather stale branches related to that :(

https://github.com/ICB-DCM/pyPESTO/tree/feature_ordinal
https://github.com/ICB-DCM/pyPESTO/tree/feature_qual_gradients
https://github.com/ICB-DCM/pyPESTO/tree/feature_hierarchical
https://github.com/ICB-DCM/pyPESTO/tree/hierarchical_with_simulation_chunks_PJ

**Comment by dweindl** [comment]
All done, right?
