### ISSUE TITLE
Global optimization toolboxes

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#170]
As existed for pesto, a few global toolboxes should be interfaced, in addition to the gradient-based local ones.

E.g.:
* PSwarm
* CMAES
* Meigo (if available)

**Comment by paulstapor** [comment]
For PSO:
https://pythonhosted.org/pyswarm/
or
https://github.com/jerrytheo/psopy

For an GA:
https://github.com/CMA-ES/pycma

Anything for MEIGO?

**Comment by dweindl** [comment]
See also #169

**Comment by yannikschaelte** [comment]
pyswarm exists. for the others: see separate issues.
