### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#173]
create a logo for (py)PESTO

**Comment by pbeart** [comment]
[A number of possible designs](https://imgur.com/a/U3HLxPG) - all are .svg

**Comment by paulstapor** [comment]
Hi pbeart, thanks for your work!
I personally think the first one (upper left), comes closest to what I had in mind. In the end, pyPESTO is a fitting tool, which optimizes a models and also does some uncertainty analysis and statistics.
Hence, the graph (possibly enriched by some data points with/without error bars) is something I find nice. And of course, it has to be green... ;)
But sure, some written (py)PESTO is also quite useful for promoting the tool...
So, please everyone else, share opinions here. :)

**Comment by JanHasenauer** [comment]
Thanks also from my side. I also like the top left one and agree with adding data.
Maybe, we can us this than as a Icon and have a version with the name "pyPESTO" next to it in a matching color?

**Comment by yannikschaelte** [comment]
We have now come up with the following logo (exists in svg), based on the previous discussion:

![path4536](https://user-images.githubusercontent.com/31767307/63429616-d861e980-c41a-11e9-95f8-53c468a86066.png)

The basil leaf and the snake together symbolize py-pesto already, so that we can use the lefthand part for thumbnails too.

@pbeart Thanks for your idea! May we mention you in the documentation as having contributed to the logo? The logo has to be under the same license as the toolbox. Is that ok for you?

**Comment by dweindl** [comment]
> The logo has to be under the same license as the toolbox.

Disagreeing there. The logo should be [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/), unless you expect everybody to include the BSD license terms in any document using the logo :).

**Comment by yannikschaelte** [comment]
valid point. agreed!

**Comment by pbeart** [comment]
Yep I'm fine with it being CC0, and being mentioned as having contributed, the main reason I put my name in the image was because I thought there might be lots of different suggestions from different people and I didn't want them to get mixed up..

**Comment by JanHasenauer** [comment]
Thanks again for the contribution. This really got us started discussion!

**Comment by paulstapor** [comment]
Isn't this one supposed to be closed by now?

**Comment by yannikschaelte** [comment]
yes :)
