### ISSUE TITLE
Approximate grad and hess

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#18]
Approximate grad using finite differences as in the matlab version in https://github.com/ICB-DCM/PESTO/blob/master/private/getFiniteDifferences.m,

and approximate hess using any of bfgs, dfp, sr1, as in https://github.com/ICB-DCM/NOODLES/blob/feature_arc/%2Bnoodles/NoodleProblem.m.

The location for this would probably be the pesto.Objective class, which will need to interpret the input for the grad and hess arguments appropriately (e.g. string 'SR1' -> use that method), and memorize maybe some values for the adaptive finite differences scheme, and for the hessian approximations.

**Comment by paulstapor** [comment]
Personally, I'd write a little standalone toolbox for this, deploy, and import it into pyPESTO. It's not unlikely that one might need some FD implementaiton elsewhere at some point...

**Comment by yannikschaelte** [comment]
A basic implementation is provided now in #666 in the `pypesto.objective` submodule. I think that an extension to "better" (=adaptive) differences would be straightforward.
Reason to have it directly as a `pypesto.Objective` is to maintain the efficiency in calling, e.g. to not have superfluous function calls when calculating both grad and hess.
