### ISSUE TITLE
PEtab import: species in condition table not handled properly 

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#184]
In [PEtab](https://github.com/ICB-DCM/PEtab/blob/master/doc/documentation_data_format.md#condition-table), at some point we allowed to specify species IDs in the condition table. This should set the concentration of the respective species to the specified value. This is not handled correctly in `pypesto/objective/petab_import.py` and results in "KeyError: 'Cannot make **** a constant parameter: Parameter does not exist.' during AMICI model import.

EDIT: This may also be a chance to reduce the redundancy of `pypesto/objective/petab_import.py` and https://github.com/ICB-DCM/AMICI/blob/master/python/bin/amici_import_petab.py.

**Comment by yannikschaelte** [comment]
Not sure exactly what is meant. The species concentration value should be replaced by the corresponding parameter's value at runtime? (Where) has this been done in amici/parpe already?

**Comment by dweindl** [comment]
> Not sure exactly what is meant. The species concentration value should be replaced by the corresponding parameter's value at runtime? 

Independently of how it is implemented exactly, all occurrences of the respective species should be replaced by the provided value from the condition table.

> (Where) has this been done in amici/parpe already?

I did it here by converting the species to parameters:
https://github.com/ICB-DCM/AMICI/blob/master/python/bin/amici_import_petab.py#L127 ff
This felt like the easiest way.

**Comment by paulstapor** [comment]
If nobody manages it by tonight and if I get Speedy5 running, I will try it...

**Comment by paulstapor** [comment]
Working on it from now...
