### ISSUE TITLE
Add setup.py extras_require for building documentation

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#191]
seems like we need: sphinx, nbsphinx, sphinx_rtd_theme

**Comment by dweindl** [comment]
+ nbconvert, ideally nbconvert>=5.5.0 to prevent a long list of 
```
  nbconvert.utils.pandoc.check_pandoc_version()
..../nbsphinx.py:1173: RuntimeWarning: You are using an unsupported version of pandoc (2.2.1).
Your version must be at least (1.12.1) but less than (2.0.0).
Refer to http://pandoc.org/installing.html.
Continuing with doubts...
```

**Comment by yannikschaelte** [comment]
that list should be complete, I think

**Comment by dweindl** [comment]
Actually, this should be covered by `.rtd_pip_reqs.txt`, `.travis_pip_reqs.txt` and pypesto package dependencies - and maybe `setup.py` is not the right place for that.
