### ISSUE TITLE
Make rdatas -> simulation df fool safe

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#195]
Currently, in https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/petab_import.py#L400 we rely on the extraction of the condition ids in pandas to always happen in the same order, which is strictly not correct (though probably safe enough). It would be easier, and easier to generalize, to pass the conditions as an additional parameter to the objective function instead. All other information should be contained in the edatas already, so that the petab importer is not necessary to create a simulation df from rdatas, the objective suffices.

**Comment by MerktSimon** [comment]
also linked to https://github.com/ICB-DCM/AMICI/blob/master/python/amici/petab_objective.py#L625

**Comment by yannikschaelte** [comment]
rewritten, moved to amici, thus closing here.
