### ISSUE TITLE
Update to PEtab 0.0.0a18

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#207]
- [x] Update requirement (petab + amici)
~- [ ] Handle changes in observableTransformation~ No adaptations required, right?
- [x] Handle changes in parameterScale + nominalValue + bounds + starting points
- [x] Replace use of `pypesto.petab_import._merge_preeq_and_sim_pars` by `petab.merge_preeq_and_sim_pars`
- [x] Add support for PEtab-YAML `pypesto.petab_import.PetabImporter.from_yaml`
- [x] Use PEtab-YAML in example
- [x] Use `amici.petab_import.petab_noise_distributions_to_amici` instead of `pypesto.petab_import._to_amici_noise_distributions`
- [x] Replace `pypesto.petab_import.PetabImporter.compile_model` by `amici.petab_import.import_model`

**Comment by yannikschaelte** [comment]
1) note that regarding yaml import, there existed already something in https://github.com/ICB-DCM/pyPESTO/compare/feature_config_file, but I think that must be completely rewritten anyway
2) maybe we can directly add support for aggregated petab problems

**Comment by dweindl** [comment]
>     1. note that regarding yaml import, there existed already something in https://github.com/ICB-DCM/pyPESTO/compare/feature_config_file, but I think that must be completely rewritten anyway

It's about YAML, but rather related to optimizer and simulator settings (#117). This is orthogonal to what I meant here. Planned to only add `pypesto.petab_import.PetabImporter.from_yaml` in addition to `pypesto.petab_import.PetabImporter.from_folder`. I think the rest still needs more discussion.

>     2. maybe we can directly add support for aggregated petab problems

Happy to have that in soon, but this will require some more non-trivial adaptations in `petab` first.

**Comment by yannikschaelte** [comment]
> It's about YAML, but rather related to optimizer and simulator settings (#117). This is orthogonal to what I meant here. Planned to only add `pypesto.petab_import.PetabImporter.from_yaml` in addition to `pypesto.petab_import.PetabImporter.from_folder`. I think the rest still needs more discussion.

right. the only connection will be that it will read from the same file.

**Comment by yannikschaelte** [comment]
done in #229
