### ISSUE TITLE
issue with petab_import on 207 branch

### ISSUE THREAD

**Issue by fbergmann** [ICB-DCM/pyPESTO#212]
After all the updates of PEtab and AMICI after the hackathon, i'm almost at a point where i can run a first test model. However, I do get an error now when i run `importer.create_problem`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-326a21ba536e> in <module>
----> 1 importer.create_problem(obj)

/mnt/e/Development/ubuntu/pyPESTO/pypesto/objective/petab_import.py in create_problem(self, objective)
    293             ub=self.petab_problem.ub_scaled,
    294             x_fixed_indices=self.petab_problem.x_fixed_indices,
--> 295             x_fixed_vals=self.petab_problem.x_nominal_fixed_scaled,
    296             x_names=self.petab_problem.x_ids)
    297 

AttributeError: 'Problem' object has no attribute 'x_nominal_fixed_scaled'
```

as indicated in the petab_import notebook. This problem goes away if i run using: 

```
petab_problem.x_nominal_fixed_scaled = petab_problem.x_fixed_vals 
problem = importer.create_problem(obj)
```

**Comment by yannikschaelte** [comment]
x_fixed_vals will unfortunately only work if there are not parameters with ESTIMATE=0 in the parameters file, also scaling is not applied. Have you updated to the latest petab/develop? There, x_nominal_fixed_scaled should exist ...

**Comment by fbergmann** [comment]
ok that worked! ... sorry for the noise
