### ISSUE TITLE
start_indices not working as documented in visualize.parameters

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#213]
Claims I can pass an `int`, but throws an `TypeError: iteration over a 0-d array` when I do so. Naming is also a bit misleading in case of passing an `int`.

**Comment by paulstapor** [comment]
Does it work if you pass it as list?

**Comment by paulstapor** [comment]
Can you say in which line the 0-d error comes up?

**Comment by paulstapor** [comment]
turns out cisualize.parameters is not well enough tested. Will change that.

**Comment by FFroehlich** [comment]
`start_indices=range(10)` works, `start_indices=10` doesn't. Error is thrown in line 250: https://github.com/ICB-DCM/pyPESTO/blob/dca625328b3d1200b2d4dd18f7be97468b651aed/pypesto/visualize/parameters.py#L250

**Comment by paulstapor** [comment]
Agree that it should work.
I'll do that tomorrow.
