### ISSUE TITLE
odd yscale in waterfall plot

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#215]
[waterfall__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda3162.2776601683795.pdf](https://github.com/ICB-DCM/pyPESTO/files/4234122/waterfall__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda3162.2776601683795.pdf)

automatic yticks arent too helpful in this plot ... fvals were 

1506.4343438452800
1506.434343845640
1506.4343438457200
1506.4343438457900
1506.434343845870
1506.4343438459300
1506.4343438463400
1506.4343438467900
1506.4343438470200
1506.4343438474300

so optimizer convergence is wonderful ;)

**Comment by paulstapor** [comment]
agreed... :joy:
will be done
