### ISSUE TITLE
interface ipopt

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#220]
there exists a cython wrapper for ipopt, so it should be possible to include this optimizer.

**Comment by dweindl** [comment]
>  @yannikschaelte yannikschaelte added this to To do in scrum hackathon March-May 2020 on Mar 19 

Did anybody already look into that?

**Comment by paulstapor** [comment]
Not that I know... But would be pretty awesome being able to compare Ipopt to SciPy routines...

**Comment by dweindl** [comment]
Various wrappers are available:

* https://github.com/matthias-k/cyipopt
  recent activity, looks most promising
* https://gitlab.com/g-braeunlich/ipyopt
  recent activity, but at first glance, doesn't seem like there is much windows support (personally don't care, but...)
* https://github.com/xuy/pyipopt
  looks a bit stale

**Comment by yannikschaelte** [comment]
No-one has done this yet, but will definitely need to happen soon. If someone volunteers, very welcome ;). I suggest trying the first one first, which is also used in the pypi package https://pypi.org/project/ipopt/.

**Comment by dweindl** [comment]
Yeah, works out of the box (Ubuntu 20.04).

 @plakrisenko: Want to give it a look?

**Comment by yannikschaelte** [comment]
done that now

**Comment by yannikschaelte** [comment]
> Yeah, works out of the box (Ubuntu 20.04).

@dweindl It does not seem to be available via pip though, only conda (thus currently also fails on travis). ipyopt seems to require an installation of c++ ipopt, so this may too be not the most convenient installation. any suggestions what is best?

**Comment by dweindl** [comment]
I thought i installed via pip. Need to double check.
C++ libraries are required yes. At least on linux not a problem. I prefer installing them externally then building the whole thing during package installation. I think that's fine for a start.

**Comment by yannikschaelte** [comment]
If you successfully installed via pip without anaconda, can you post the dependencies / modify the travis build? :grin:

**Comment by dweindl** [comment]
Can have a look sometime this week

**Comment by dweindl** [comment]
> can you post the dependencies / modify the travis build? grin

done in #373

**Comment by yannikschaelte** [comment]
@dweindl great, thanks!

**Comment by yannikschaelte** [comment]
done in #387
