### ISSUE TITLE
Implement adaptive metropolis algorithm

### ISSUE THREAD

**Issue by dilpath** [ICB-DCM/pyPESTO#232]
- [x] Independently
- [x] Integrated with the result of #231

**Comment by elbaraim** [comment]
@dilpath you can base your implementation on https://github.com/ICB-DCM/PESTO/blob/master/private/performPT.m
Adaptive Metropolis is basically when taking `nTemps = 1` https://github.com/ICB-DCM/PESTO/blob/3949f150108a051ec0e627c467644290061fc494/private/performPT.m#L105
