### ISSUE TITLE
Basic visualizations for Sampling

### ISSUE THREAD

**Issue by erikadudki** [ICB-DCM/pyPESTO#234]
- sampler trajectory per parameter

**Comment by FFroehlich** [comment]
would be great to have something reusable based on https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/history.py, would allow to also plot trajectories for optimization.

**Comment by yannikschaelte** [comment]
good point to reuse the history here. @FFroehlich there already exists visualizae.optimizer_history, e.g. shown here https://pypesto.readthedocs.io/en/latest/example/rosenbrock.html

I'm not something sampling-specific needs to be done, if not one can maybe directly reuse that here for trajectories.

**Comment by FFroehlich** [comment]
> good point to reuse the history here. @FFroehlich there already exists visualizae.optimizer_history, e.g. shown here https://pypesto.readthedocs.io/en/latest/example/rosenbrock.html

Right, but thats only for function values, not parameters.

**Comment by yannikschaelte** [comment]
> > good point to reuse the history here. @FFroehlich there already exists visualizae.optimizer_history, e.g. shown here https://pypesto.readthedocs.io/en/latest/example/rosenbrock.html
> 
> Right, but thats only for function values and gradient norm, not parameters.

Ah right. We discussed having both. So @erikadudki for fvals maybe the existing one can be reused, for parameters one can be written that works with the history directly and thus applies to optimization and sampling alike.

**Comment by elbaraim** [comment]
Hi @erikadudki 
These are examples of a collection of basic visualizations used for MCMC:
- **MCMC samples trajectories**: Here exchange the X axis label with the Y axis label. X axis label should be "# iterations" or "# samples".
![samplesSS_long](https://user-images.githubusercontent.com/10628853/77405067-ee6dc900-6db2-11ea-9c63-7f3c666d15d5.png)
- **Parameter/Samples correlations**: See [here](https://seaborn.pydata.org/examples/scatterplot_matrix.html).
- **Parameter marginal distributions**: Here the Y axis could be in the beginning just the occurrence (default by histograms). Then one could thing of, e.g., normalizing values.
![histSS_long_new](https://user-images.githubusercontent.com/10628853/77405277-37be1880-6db3-11ea-8502-fe748573d622.png)

For later (not necessary as a first step, just leaving it here for reporting):
- **Parameter confidence intervals based on percentiles as projectile plot**: See [here](https://seaborn.pydata.org/examples/large_distributions.html), this could be used for also plotting profile likelihood-based confidence intervals.

**Comment by yannikschaelte** [comment]
done in #305
