### ISSUE TITLE
Waterfall plot: strange y axis

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#236]
all 1? occurs sometimes for conversion_reaction notebook.

![image](https://user-images.githubusercontent.com/31767307/77257668-16a3dd80-6c76-11ea-97c1-ea4e9606113b.png)

**Comment by JanHasenauer** [comment]
perfect convergence. in matlab we enforced a minimal difference of 1 between lower and upper limit of the y-axis. i would suggest to also do this here.

**Comment by FFroehlich** [comment]
duplicate of #215

**Comment by yannikschaelte** [comment]
> duplicate of #215

true, did not check the appended figure.

**Comment by paulstapor** [comment]
ok, will address, sorry to let it open so long.
