### ISSUE TITLE
NLLH vs LLH

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#237]
We need proper handling of both. optimization (minimization) needs nllh (->min), for sampling llh (->max) makes more sense. It is straightforward to flip to sign in the Objective class, however one must decide what to store then afterwards.

In PESTO (@paulstapor), the objective was always the llh, only for optimization the nllh was used, and the sign the flipped later before storing things. Thus, we would save an LLH value, and also SLLH, not snllh. For waterfalls, one could then just show the llh too and ignore that nllh was used in optimization. Does that seem sound, or anyone any alternative ideas? Should avoid confusion as much as possible.

**Comment by paulstapor** [comment]
Hm...
I like that fact that we plot nllh in waterfalls now...
In PESTO, you could specify what type of objetive you have, and it flipped signs accordingly to what was to be done by the wrapper/decorator. 
Maybe, it's even best to show optimization as nllh, the rest as llh, because more convenient? However, I see that using llh and nllh may be confusing...
Maybe just passing flags to visualization, which does the sign thing?

**Comment by yannikschaelte** [comment]
I would also say passing flags to visualization is good. in general, I think maintaining llh, not nllh, everywhere is good, because it is a statistical toolbox after all. the idea here would be to pass it to ``Objective(..., obj_type=OBJ_TYPE_LLH)`` as an attribute, and then flip whenever needed.

**Comment by yannikschaelte** [comment]
Another question arises when we have priors modifying the objective function, so that it is not a likelihood, but a posterior, so one can't use llh as default name ...

**Comment by paulstapor** [comment]
> Another question arises when we have priors modifying the objective function, so that it is not a likelihood, but a posterior, so one can't use llh as default name ...

Solved by always calling it a posterior, because we always have box constraints...

**Comment by yannikschaelte** [comment]
the box contraints would add an offset to the likelihood, which we by default do not compute ... maybe we should? ...

**Comment by paulstapor** [comment]
> I would also say passing flags to visualization is good. in general, I think maintaining llh, not nllh, everywhere is good, because it is a statistical toolbox after all. the idea here would be to pass it to `Objective(..., obj_type=OBJ_TYPE_LLH)` as an attribute, and then flip whenever needed.

This is definitely one possible solution and the one we had in PESTO, so it's also fine for me...
How it's called internally is mostly important to make contribution and development simple, but not as crucial as what's displayed on the plots (as those go to publications)...

**Comment by yannikschaelte** [comment]
so in pesto the prior offset was always added?

**Comment by paulstapor** [comment]
> the box contraints would add an offset to the likelihood, which we by default do not compute ... maybe we should? ...

You mean in the sense: "volume of box and normalize probability mass to one"?
Sounds actually good...

**Comment by paulstapor** [comment]
> so in pesto the prior offset was always added?

PESTO didn't a likelihood by itself...

**Comment by yannikschaelte** [comment]
After discussion with Paul, it would seem reasonable to me to **only allow for passing a negative log likelihood or negative log posterior** (if exists prior), which are for minimization in the form of a "CostFunction", but not a log likelihood / posterior. this would make maintenance much easier, e.g. how to sort values, i.e. if large or small values are better.

Adding a prior would need to be added as part of the objective / problem.

In sampling, and depending on the implementation in profiling, then one would once need to **flip** the sign. still, the nllh would be stored in the history. in visualization, flags should be added whether to plot cost or gain function style.

Any comments/concerns? Anyone a real interest in being able to specify an objective as positive llh?

**Comment by JanHasenauer** [comment]
negative log likelihood and negative log posterior is fine. just needs to be clearly specified.
