### ISSUE TITLE
Define storage format

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#241]
done preliminarily here: https://github.com/ICB-DCM/pyPESTO/blob/feature_storage_hdf5/doc/storage_format.md

**Comment by dweindl** [comment]
> done preliminarily here: https://github.com/ICB-DCM/pyPESTO/blob/feature_storage_hdf5/doc/storage_format.md

Would be good to also specify the dimensions / ordering there
