### ISSUE TITLE
documentation for parameter_mapping AmiciObjective is inexistent

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#242]
`parameter_mapping` is supposed to be created by `amici.petab_objective.create_parameter_mapping`. 

- I think I have complained about this a couple of times now, but I don't think AMICI is the right place to define pypesto API
- `List of the parameter mappings.` is really insufficient in terms of documentation. 
- I don't think that with the current state of petab it is in any way sustainable to continuously break non-petab functionality.

**Comment by yannikschaelte** [comment]
docs updated via amici class exposure
