### ISSUE TITLE
Different behaviour for singleCoreEngine and MultiProcessEngine

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#246]
I tried optimizing the Salazar-Cavazos model from the benchmark collection with adjoint sensitivities for single and multi core engine. Optimization works with `singleCoreEngine` but fails with `MultiProcessEngine` because of AMICI integration errors. I get the same errors when using `singleCoreEngine` and forward sensitivities. Might it be, that `MultiProcessEngine` ignores the sensitivity method set in `obj.amici_solver.setSensitivityMethod`?

**Comment by yannikschaelte** [comment]
you have to set the sensitivity method outside pypesto, right? Yes, that information is likely to be currently lost. Easiest would be to provide the method as an input to the objective I think :thinking:

**Comment by LeonardSchmiester** [comment]
What do you mean by outside pypesto? It is set in the pypesto objective function with `obj.amici_solver.setSensitivityMethod`, which works fine for `singleCoreEngine`.

**Comment by yannikschaelte** [comment]
yes, that is what I meant. In multiprocessing, if I remember correctly, a copy of the object is created, implemented here https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/petab_import.py#L434. So the question would be whether when one copies the SolverPtr, the method is recorded.

**Comment by FFroehlich** [comment]
`other.amici_solver = amici.SolverPtr(self.amici_solver.clone())` should copy over the `SensitivityMethod`.

See 

https://github.com/ICB-DCM/AMICI/blob/f92127899b2e7ad64d2b6149b7331afc2348a026/src/solver.cpp#L21 

and 

https://github.com/ICB-DCM/AMICI/blob/f92127899b2e7ad64d2b6149b7331afc2348a026/src/solver_cvodes.cpp#L208



On a seperate note, why does `PetabObjective` reimplement `__deepcopy__` instead of inheriting from `AmiciObjective`? Looks like the two have already diverged.

**Comment by yannikschaelte** [comment]
> On a seperate note, why does PetabObjective reimplement __deepcopy__ instead of inheriting from AmiciObjective? Looks like the two have already diverged.

Good point, that needs to be adapted.

**Comment by yannikschaelte** [comment]
the problem is that multiprocessing uses serialization, and here not all solver options are maintained. we are looking into what can be done.

**Comment by yannikschaelte** [comment]
@LeonardSchmiester The behavior on MultiProcessEngine is yet to be fixed, but in the meantime you can check out MultiThreadEngine, which should maintain all necessary solver options on the parallel workers.

**Comment by yannikschaelte** [comment]
done via #305
