### ISSUE TITLE
Pickling of results

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#25]
For distributed computing it would be great to have a way to pickle result files. Currently, the attached `Problem` instance cannot be pickled if `AmiciObjective` is used as `SwigPy` objects cannot be pickled. 

Current workaround is to only pickle the `OptimizerResult` data.

**Comment by yannikschaelte** [comment]
why does the problem occur when pickling the result object? i would think that one parallelizes the multi-starts which then return pypesto.OptimizerResult objects, but that the result object remains in the master thread only.
but the same problem would occur when pickling the objective contained in the pypesto.Problem object passed to the multi-start workers / samplers etc., right? so same problem.

**Comment by yannikschaelte** [comment]
looks like one would need to define the ``__setstate__`` and ``__getstate__`` methods, preferably in the C++ source code. Don't know if that is possible here.
See also https://stackoverflow.com/questions/9310053/how-to-make-my-swig-extension-module-work-with-pickle%29 and related discussions. Pickling the objective would definitely be good.

**Comment by dweindl** [comment]
@FFroehlich There is serialization support for `amici::Model` in `serialization.h`.

**Comment by dweindl** [comment]
> Current workaround is to only pickle the OptimizerResult data.

Is this really a limitation? For me that would be fine. For parallel simulations I would also not start serializing model, and solver, but serialize factory functions and instantiate them in place.

**Comment by yannikschaelte** [comment]
factory methods for instatiation sounds like a good idea :) I think we will need serialization e.g. for pt-mcmc methods later, which are not that trivial to parallelize, so let's keep that in mind.

**Comment by yannikschaelte** [comment]
future note: pickling is not always the best idea (https://www.benfrederickson.com/dont-pickle-your-data/). If we need it though, at least codacy must be silenced in this regard.

**Comment by dweindl** [comment]
I would use pickle only for communicating between different threads processes. Not for anything that is written to disk. There we should go for csv, hdf5, json that can be accessed from practically any other language/tool.

**Comment by yannikschaelte** [comment]
sure, for long-time storage pickling is no option.

**Comment by yannikschaelte** [comment]
I thought about not putting the full Problem into the Result, but only some ProblemInfo object, which inf particular contains not the full Objective, but only a representation. Then the full Result could be saved to file.
?

**Comment by FFroehlich** [comment]
obsolete with hdf5 storage support
