### ISSUE TITLE
Effective sample size for MCMC

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#251]
first, just a function to calculate it. later, integrate it in some sort of "diagnostics"

**Comment by elbaraim** [comment]
@yannikschaelte  it would be good to add convergence tests, e.g., Geweke, to this since the ESS (or auto-correlation) is mostly calculated from already converged MCMC chains.

**Comment by yannikschaelte** [comment]
sure, at some point we also have to implement / make accessible those :grimacing:

**Comment by JanHasenauer** [comment]
a nice overview: https://pymc-devs.github.io/pymc/modelchecking.html
