### ISSUE TITLE
Remove history.obj

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#253]
It would be cleaner and avoid the circular reference (potentially leading to copying problems) if the ObjectiveHistory did not hold a reference to the objective function fun method. Can this be circumvented?

**Comment by FFroehlich** [comment]
`fval2chi2_offset` could be precomputed and passed to `__init__` when initializing the history. Would require some guesswork to only compute when necessary though.

**Comment by yannikschaelte** [comment]
problem would be that at ``__init__`` "good" parameter values are not known yet, and potentially some parameters have not yet been fixed. one could pass the objective every time when updating in the ``objective.__call__`` method though.

**Comment by FFroehlich** [comment]
Yes, I didn't see a good way of implementing the functionality while avoiding the circular reference.

**Comment by yannikschaelte** [comment]
@FFroehlich would #254 work?

**Comment by FFroehlich** [comment]
It should for now, a bit worried that it might break in the future. But as long as we don't do anything funky with rebinding, this should be fine.

**Comment by yannikschaelte** [comment]
Is the offset actually required? Indeed causes a little headache to keep the whole binding and updating of fixed parameters in mind. For me, it would be sufficient to have only the non-offsetted chi2 value as fval.

**Comment by FFroehlich** [comment]
I would rather not set `fval` than setting `fval` as `chi2`. Can easily lead to a lot of confusion when comparing results from different optimizers. Can also easily mess up confidence intervals from profile calculation or sampling.

**Comment by yannikschaelte** [comment]
Ok, should work now for the moment. Yet an alternative approach would be to just always compute the fval in the objective function and fill it in here (or None, if it cannot be computed). That is just changing one line in the AmiciObjective.

**Comment by FFroehlich** [comment]
True, thinking about it more the initial value is currently always computed using fval, and I would guess that all nlsq evaluates initially evaluate at that point again, so we could also try to use that info :)

**Comment by yannikschaelte** [comment]
done via #305
