### ISSUE TITLE
Fill result from history

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#259]
When a run crashes, there should be a function to fill a result from history (if such a one has been saved to file via csv/hdf5, that is). Partly exists already in the pypesto.optimize.optimizer.full_result_from_history function, but the rest of the workflow, both from csv and hdf5, should be added, to create the result object and finally store everything in the result hdf5 file.

**Comment by PaulJonasJost** [comment]
> more specifically referring to https://github.com/ICB-DCM/pyPESTO/blob/main/pypesto/optimize/optimizer.py#L206

in there the function `read_result_from_file` only reads a single run and returns a single OptimizerResult. Wouldn't we want something that returns the whole `optimizeResult`?

**Comment by FFroehlich** [comment]
> > more specifically referring to https://github.com/ICB-DCM/pyPESTO/blob/main/pypesto/optimize/optimizer.py#L206
> 
> in there the function `read_result_from_file` only reads a single run and returns a single OptimizerResult. Wouldn't we want something that returns the whole `optimizeResult`?

https://github.com/ICB-DCM/pyPESTO/pull/517
