### ISSUE TITLE
Plotting of many forward simulation in one window

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/pyPESTO#27]
If I understood correctly, it is an aim for Amici to have plotting routines for the model simulation. The question is, if we want to use those in pyPESTO or build other routines in pyPESTO for plotting the forward simulation.

No matter how we decide on this: 
We should keep in mind to have it flexible enough to visualize many trajectories for many parameter samples in one plot, since we may want to visualize MCMC results later.

**Comment by dweindl** [comment]
I discussed with @DantongWang that all plotting routines should take a `matplotlib.axes.Axes` as optional input. This allows to extend the respective plot and should make it also pretty simple to add additional trajectories.

**Comment by FFroehlich** [comment]
can we please use http://ggplot.yhathq.com instead of matplotlib? The plotting routines really aren't something one should dread when switching from matlab and the grammar of graphics is such a neat concept.

**Comment by dweindl** [comment]
I don't have too much experience with ggplot. Anybody here using this in python? The repository hasn't been updated in 2 years...

**Comment by yannikschaelte** [comment]
matplotlib is the default plotting routine though, so worked on by more developers, so less risk of running into issues at some point/date, and more functionality I would guess ...
(and i think the syntax is close to but still better than matlab, in particular more object-oriented) ...
