### ISSUE TITLE
Saving results to HDF5 fails for Hessian

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#272]
Error message is:
`TypeError: Can't broadcast (21, 21) -> (21,)` in `write_string_array` in `hdf5.py`.

The problem is line 44. It should be `np.shape(values)` instead of `(len(values),)`.

**Comment by JanHasenauer** [comment]
What's the status of this? Fits to the recent scrum.

**Comment by LeonardSchmiester** [comment]
Was fixed by #273. Just not in the master yet.
