### ISSUE TITLE
Wrong x0 in optimization result

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#279]
For e.g. `L-BFGS-B` and `SLSQP` in the result object `x0` is always equal to `x`. This doesn't happen for other optimizers like `TNC` and `Newton-CG`.

**Comment by paulstapor** [comment]
Okay.... "weird" is putting it mildly... But likely to be a typo-like error somewhere in the optimization output routine...
Can look at this at some point this or rather next week... Or is it urgent right now?

**Comment by LeonardSchmiester** [comment]
Not super urgent. Just needed it to confirm, that I really use the same starting points for optimizer benchmarking. But I think for using x_guesses nothing goes wrong and it's only saving the wrong vectors.

**Comment by paulstapor** [comment]
How is it if you use `ls_trf`?

**Comment by LeonardSchmiester** [comment]
`x` and `x0` seem to be different for `ls_trf`. But `n_fval=0` and cost function values returned from pyPESTO differ from the ones reported from `ls_trf`:
```
Function evaluations 870, initial cost 7.8819e+05, final cost 4.9266e+03, first-order optimality 5.01e+01.
Final fval=5262.9138, time=54.9387s, n_fval=0.
```

**Comment by yannikschaelte** [comment]
cost function values in pyPESTO also take into account the offset, not only the sum of squares, thus these are different. n_fval=0 looks like an obvious mistake. maybe it's not tracked properly in the history? It has a function _update_counts, which should do this. Or, it could be written wrongly into the result object at the end. of the run. That happens in the optimize.optimizer.fill_result_from_objective_history function.

**Comment by yannikschaelte** [comment]
@LeonardSchmiester is this still an issue? a related problem was recently resolved.

**Comment by LeonardSchmiester** [comment]
Seems to be fixed :+1:
