### ISSUE TITLE
Some options are ignored for scipy least squares optimizers

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#282]
Seems like `max_nfev` and some other options that can be set for the least squares optimizers in Scipy are ignored by pyPESTO. Would be good to be able to set these options (or at least print a warning, that it is ignored).

**Comment by yannikschaelte** [comment]
agreed, should be easy to fix, similar to how it's done for the non-ls optimizers, or the samplers.
