### ISSUE TITLE
Announcing future developments

### ISSUE THREAD

**Issue by paulflang** [ICB-DCM/pyPESTO#286]
I noticed that pyPESTO is being rapidly developed. Is there a good resource to stay informed about what features are soon to be released and perhaps worthwhile waiting for?

**Comment by paulstapor** [comment]
We're mostly developing pyPESTO to match our needs for modeling and parameter estimation and have quite some ideas, what to implement next. However, this always depends to a certain degree on our current application projects... So announcing a strict list which will be fulfilled in a specific order is unlikely to work for us...
However, we could provide a rough plan what will come at some point, I think...
Opinions of the other developers?

**Comment by paulstapor** [comment]
Addendum:
We previously used PESTO, written in Matlab, for most of our projects. So, quite some features have been implemented in Matlab-Pesto and in the Matlab-part of Amici, which haven't made it into the Python versions yet.
However, many of the features, which were around in Matlab, will be implemented at some point in pyPESTO as well. What will definitely come soonish:
Events and more stuff on steady-state solver in Amici, a routine which merges profile likelihoods in pyPESTO, some more routines for profile likelihoods (e.g. integration based computation) in pyPESTO, and routines for approximate uncertainty analysis (local approximations and ensemble-based ideas) in pyPESTO...

**Comment by FFroehlich** [comment]
I think for new features it would be good to maintain a list of what is currently being worked + associated issues as milestones.

**Comment by PaulJonasJost** [comment]
as an idea we could just open a draft PR whenever we start working on something? would efficiently not only be a list of what is worked on + issues but also milestones (sometimes) as well as current progress.
