### ISSUE TITLE
L1/elastic net regularisation

### ISSUE THREAD

**Issue by paulflang** [ICB-DCM/pyPESTO#287]
Does pyPESTO support L1 or elastic net regularization in combination with adjoint sensitivity based gradients? I would find this useful for model reduction and selection.

**Comment by JanHasenauer** [comment]
We just discussed this last week. The plan is to add this soon, in combination with some additional model selection and reduction approaches

**Comment by paulflang** [comment]
Great. Thank you very much! Looking forward to seeing these new features.

**Comment by jvanhoefer** [comment]
Update on that: 

Priors are implemented now and you should be able to include an L1 regularization as a Laplace Prior (e.g. via the PEtab import) and an elastic net regularization as a sum of an Normal + Laplace prior for the same parameter (not via PEtab but defined directly in pyPESTO). 

If you have any questions: We are happy to help :)

**Comment by paulflang** [comment]
That's great news! Thank you very much., @jvanhoefer .

**Comment by jvanhoefer** [comment]
One more update: 
You now can find an example, that demonstrates the definition of priors in the `develop` branch. Thinking more about that: I would probably not go via prior, but define an `Objective`, that computes the L1/elastic net part and add this to your `AmiciObjective`. (This is shown in the prior-example.) In the definition of the `Objective`, you only have to define your regularization term and it's gradient (eventually Hessian). 
You can write me, if you have any questions :)

**Comment by paulflang** [comment]
Thank you very much for adding this example, @jvanhoefer ! My current test problem is specified in PEtab, but it will take a few months until I get real data from our experimental collaborators. For the time being using either L1 or L2 regularisation will probably do. Otherwise I will happily accept your offer to get in touch with further questions.

**Comment by jvanhoefer** [comment]
I will close this issue now. Feel free to re-open if something is not clear/new questions arise.
