### ISSUE TITLE
Implement Prior Class

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#294]
We want to include priors in pyPesto. Currently open points are

- [ ] Include analytical gradients

- [ ] `objective` should by default include the prior, if one is specified

- [ ] Still it should be possible to evaluate the `objective` without prior (PriorFlag)

- [ ] Define priors via lists and dicts...

**Comment by FFroehlich** [comment]
What speaks against implementing the prior via `AggregatedObjective`? should make point 2 and 3 pretty straightforward and would reduce the anyways already high complexity of objective?

**Comment by yannikschaelte** [comment]
Sounds reasonable. In that case, have Prior derived from Objective (it should have a similar API anyway).

**Comment by yannikschaelte** [comment]
done in #387
