### ISSUE TITLE
Document/rework OptimizerHistory

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#311]
The `OptimizerHistory` derives from `HistoryBase`, but only implements the update() method, not the getters in particular. This was because the objective needs to get a `HistoryBase` object as attribute, however the getters are never called directly. Further, the current form allows to use different backups like CSV/HDF5/... quite easily. Question: Can this be written in a cleaner form? One way would be to just have the minimum value stored as part of the `History` class already, even though it is not needed e.g. in sampling.

At least, the purpose of `OptimizerHistory` must be documented more cleanly.

**Comment by PaulJonasJost** [comment]
is this still the current state @yannikschaelte ? As far as I see, OptimizerHistory now is not derived anymore from HistoryBase but as stated 
`Objective call history. Container around a History object, which keeps track of optimal values.`

**Comment by yannikschaelte** [comment]
Thanks for pointing this out. I think the current solution is clean enough, so can close here.
