### ISSUE TITLE
Update CI build

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#318]
I think it makes sense to always test against the latest stuff (can ask users to upgrade, but not to downgrade :))

* [x] python version currently 3.6 (not supported by AMICI) -> 3.8?
* [x] test system ubuntu 16.04 -> 18.04? (or newer, once available)

**Comment by dweindl** [comment]
>     * [ ]  python version currently 3.6 (not supported by AMICI) -> 3.8?

Not maintained, but should be supported, except for a couple of lines in the test suite.
 
>     * [ ]  test system ubuntu 16.04 -> 18.04? (or newer, once available)

20.04 by now

**Comment by yannikschaelte** [comment]
> 
> 20.04 by now

Not on Travis i think ...

**Comment by dweindl** [comment]
> > 20.04 by now
> 
> Not on Travis i think ...

Ah, newest on travis. You are right then. And shouldn't use Ubuntu 16 anymore https://ubuntustudio.org/2019/04/ubuntu-studio-16-04-lts-reaches-end-of-life-eol/. Unfortunately travis is rather slow there...
