### ISSUE TITLE
Axis labels for parameter profile plots

### ISSUE THREAD

**Issue by mhhoog** [ICB-DCM/pyPESTO#321]
I'm making grateful use of the build in option to plot the parameter profiles. However reading the plots and presenting them to others is a bit cumbersome due to the labels on the x-axis. The plots give the parameter numbers instead of the parameter names.

Would it maybe be possible to plot the parameter names on the x-axis? I couldn't find a way to change this myself. And is there also a possibility to scale the plots in a way that the labels are always visible?

Thank you! 

![image](https://user-images.githubusercontent.com/61467487/81541545-8def1700-9373-11ea-9715-046fe3df7591.png)

**Comment by JanHasenauer** [comment]
I also think that it would be good to update this. Indeed, some parameter names are not even shown.
@erikadudki @MerktSimon Could on of you take care of this?

**Comment by MerktSimon** [comment]
So `pypesto.visualize.profiles()` now has the additional optional argument `x_labels`. If you pass it a list of strings it will use them as x-labels for the plots.
Moreover labels should now be always visible.
Until merging this only works on the branch https://github.com/ICB-DCM/pyPESTO/tree/fix321

**Comment by MerktSimon** [comment]
now merged to develop branch
(including new default labels taken from pypesto.Problem.x_names instead of just numbering)

**Comment by mhhoog** [comment]
Thank you! It looks very nice now :)
![image](https://user-images.githubusercontent.com/61467487/81942215-239bd800-95fa-11ea-9d55-8e855f5571e6.png)

**Comment by paulstapor** [comment]
Just a comment from personal experience:
Looks like profiling for X_0 didn't work, or crashed right away... The others look good, but the profile of x_0, I wouldn't trust... ;)
