### ISSUE TITLE
Parameter profiles to hdf5

### ISSUE THREAD

**Issue by mhhoog** [ICB-DCM/pyPESTO#333]
At the moment I'm saving the parameter estimation results and corresponding problem to hdf5. This helps to recall the waterfall and parameter plot. However I noticed that it isn't possible to save enough data to recall the parameter profiles plot. Would it be possible to get this implemented? 

This is the error I get after reading the saved data and trying to get the three plots:
```
Traceback (most recent call last):

  File "/home/maartje/Documents/Helmholtz_ICB/mainICB.py", line 313, in <module>
    result1 = pypesto.parameter_profile(problem=problem,result=result,optimizer=optimizer)#,profile_options=profile_options)

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/profile/profile.py", line 147, in parameter_profile
    profile_index = np.ones(problem.dim_full)

AttributeError: 'Result' object has no attribute 'dim_full'
```

**Comment by yannikschaelte** [comment]
Hi @mhhoog you are right, parameter profiles are not saved to HDF5 yet at all.  @paulstapor you know the format best, would this be straightforward to implement?

Regarding your error output above: Could you say in more detail what you did? Did you load the optimization result from hdf5 to a result object and then try to generate profiles? The code looks like there might be a bug with restoring dim_full though, it is strange that "problem" should be of type "Result" (it should be of type "Problem").

**Comment by mhhoog** [comment]
Hi @yannikschaelte it is indeed weird that the problem and result types are not correspondent.

I save the data by:
```
if save_output == 'yes' and task == 'optimize':
    
    fn = '/home/maartje/Documents/Helmholtz_ICB/Collectdata/Results/'+ savename +'.hdf5'
    
    # Write result
    hdf5_resultwriter = save_to_hdf5.OptimizationResultHDF5Writer(fn)
    hdf5_resultwriter.write(result)
    
    # Write problem
    hdf5_problemwriter = save_to_hdf5.ProblemHDF5Writer(fn)
    hdf5_problemwriter.write(problem)
```
and afterwards read them back in via:
```
elif task == 'plot_results':
    print('No parameter optimization performed')
    fn = '/home/maartje/Documents/Helmholtz_ICB/Collectdata/Results/'+ savename +'.hdf5'
    
    hdf5_result = read_from_hdf5.OptimizationResultHDF5Reader(fn)
    result = hdf5_result.read()
    hdf5_problem = read_from_hdf5.ProblemHDF5Reader(fn)
    problem = hdf5_result.read()
    
```

Accordingly I use the result and problem to make the plots again. I have to say that the plots I get from this are somehow doubled in their data. So I saved a result with 100 starts but I get a figure back after reading the save hdf5 with 200 starts.

**Comment by mhhoog** [comment]
Writing this out I see the bug in `problem = hdf_result.read()` ...

**Comment by mhhoog** [comment]
This at least resolved the problem of the doubled starts. 
Now this is left for trying to get the parameter profiles:

```
 File "/home/maartje/Documents/Helmholtz_ICB/mainICB.py", line 360, in <module>
    result1 = pypesto.parameter_profile(problem=problem,result=result,optimizer=optimizer)#,profile_options=profile_options)

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/profile/profile.py", line 193, in parameter_profile
    current_profile = walk_along_profile(current_profile,

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/profile/profile.py", line 271, in walk_along_profile
    x_next = create_next_guess(x_now, i_parameter, par_direction,

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/profile/profile.py", line 162, in create_next_guess
    return next_guess(x, par_index, par_direction, profile_options,

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/profile/profile_next_guess.py", line 59, in next_guess
    return adaptive_step(x, par_index, par_direction, profile_options,

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/profile/profile_next_guess.py", line 153, in adaptive_step
    problem.fix_parameters(par_index, x[par_index])

  File "/home/maartje/anaconda3/envs/envICB/lib/python3.8/site-packages/pypesto/problem.py", line 194, in fix_parameters
    self.x_fixed_indices.append(i_parameter)

AttributeError: 'numpy.ndarray' object has no attribute 'append'
```

**Comment by yannikschaelte** [comment]
Ah I see. I suspect this is because `problem.fix_parameters` assumes `x_fixed_indices` to be of type `List`, which it usually is, but hdf5 creates an `np.ndarray`, so this is a bug. I would say we should internally allow both representations, the appending needs to be fixed accordingly.

**Comment by yannikschaelte** [comment]
Another point: The problem is completely not yet completey restored (see https://github.com/ICB-DCM/pyPESTO/pull/334), we are working on that. Further, there will be some problems with recreating the problem.objective correctly. I think that soon it will work so that you can corretly do plots using a recreated problem, but if you want to do profiling, it is better to create a problem you use as input there the usual way (we still need to sort that out, admittedly).

**Comment by yannikschaelte** [comment]
This problem here should be resolved. Profiles cannot yet be saved to hdf5, that is handled in #410
