### ISSUE TITLE
Result: Do not store objective

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#350]
The objective function itself cannot be save (except serialization, which makes no sense), so it should not be part of the result. I.e. not the full problem should be part of the result. What's needed from the problem are anyway only the vectors, e.g. parameter names and fixed parameters.

Suggesting to save a "ProblemInfo" (or a nicer name) to the result, which contains all vectors, but instead of the objective just a string representation.

**Comment by PaulJonasJost** [comment]
As different objectives have different attributes, I would suggest either having a save function for each objective type or a ObjectiveInfo which would be what type of objective it is and what is needed to create it again?
