### ISSUE TITLE
Geweke test fails with empty spectrum for small sample numbers

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#354]
Not completely sure why yet. @elbaraim can you have a look? Added test case documenting the error in https://github.com/ICB-DCM/pyPESTO/tree/fix_geweke.

**Comment by elbaraim** [comment]
True, @yannikschaelte thanks for checking! I will have a look.

**Comment by elbaraim** [comment]
@yannikschaelte I have one point here, why should be computed geweke test for short chains? Does that conceptually make sense?
I have been checking the matlab code and there also fails for shorter chains (<800 samples)

**Comment by yannikschaelte** [comment]
it may not make sense, but it should not produce an error such that your whole pipeline fails.

**Comment by elbaraim** [comment]
I see the point, so adding something like a warning and return burn in index zero?

**Comment by yannikschaelte** [comment]
sounds both good. preferable if the algorithm worked for any input though, so if the error can be pinpointed to a function that operates badly under small input, welcome.

**Comment by yannikschaelte** [comment]
please only close when merged to master
