### ISSUE TITLE
pyPESTO namespace: flat or modularized?

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#355]
Currently, most functionality from `pypesto.{optimize,sampling,profile}` is put into the `pypesto` namespace. This makes things shorter to call, however can lead to confusion as the number of classes and functions in pypesto keeps growing. Alternatively, one could enforce calling it always as `pypesto.{optimize,sampling,profile,visualization,...}.xyz` (or maybe shortenings `pypesto.{op,sa,pf,vi}.xyz`). On the other hand, I would not expect that the modules offer similar functions which cannot go into one namespace. Opinions?

**Comment by JanHasenauer** [comment]
Is there a big disadvantage of modularisation?

**Comment by yannikschaelte** [comment]
longer names, e.g. `pypesto.optimize.minimize` instead of `pypesto.minimize` and `pypesto.sampling.sample` instead of `pypesto.sample`

**Comment by dweindl** [comment]
Voting for modular. pypesto already accumulated quite some dependencies, that will be imported everytime if we have it flat. I don't want to wait a minute when i `import pypesto` :)

**Comment by yannikschaelte** [comment]
What would you like for module names? Currently it is `pypesto.optimize`, `pypesto.profile`, `pypesto.sampling`. The latter was for technical reasons, could be changed to `pypesto.sample` to, i.e. use a verb for all of them, similar to scipy.

**Comment by yannikschaelte** [comment]
The decision has been to go for "optimize, profile, sample" etc., and to not automatically include these potentially large submodules
