### ISSUE TITLE
pymc3 sampler very slow

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#359]
**The problem**
Compared to the self-imlemented samplers, pymc3 is rather slow. Due to tuning (400 samples usually), it performs a few more samples, but that does not explain an increase from 5s to 1min on 1000 samples. When using a gradient-free pymc3 sampler (`pymc3.Slice`), it's down to 40s, still considerably more.

**Potential reasons**
* Not ideal theano translation. It's quite close to https://docs.pymc.io/notebooks/ODE_with_manual_gradients.html though, so should be fine ...

**To replicate**
Can be replicated in the https://github.com/ICB-DCM/pyPESTO/blob/develop/doc/example/sampler_study.ipynb sampler study notebook.

**Comment by FFroehlich** [comment]
what does the pstat dump look like, i.e., where is compute time spent? Might also be problem dependent and benefit only exists for larger or more nonlinear examples.

**Comment by yannikschaelte** [comment]
It was tested on an 1d simple test model and a 2d amici model. I agree one should look into a bigger amici model (any from the benchmark collection should go). pstat not performed yet, but should definitely be done first when looking into this.

**Comment by yannikschaelte** [comment]
Here we go: 1000 samples, 1 chain. Reason seems to be that pymc3 has a funny concept of what chain length is -- with 24000 amici simulations. So I'd say we need to figure out what we understand wrong there, but effectively it should be not slower then (60s * 1000 / 24000 = 2.5s).

AdaptiveMetropolisSampler:

```
755110 function calls (738910 primitive calls) in 2.383 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     9009    0.371    0.000    0.371    0.000 {method 'acquire' of '_thread.lock' objects}
     1001    0.342    0.000    0.342    0.000 {built-in method amici._amici.runAmiciSimulations}
     1000    0.055    0.000    0.259    0.000 {method 'multivariate_normal' of 'numpy.random.mtrand.RandomState' objects}
     2002    0.052    0.000    0.052    0.000 {built-in method _thread.start_new_thread}
     9010    0.051    0.000    0.121    0.000 {built-in method numpy.array}
     1001    0.050    0.000    0.056    0.000 numpy.py:155(__init__)
     1001    0.050    0.000    0.170    0.000 arrayprint.py:883(fillFormat)
     8008    0.049    0.000    0.049    0.000 {method 'reduce' of 'numpy.ufunc' objects}
    19780    0.047    0.000    0.047    0.000 {built-in method numpy.core._multiarray_umath.dragon4_positional}
    10010    0.041    0.000    0.066    0.000 arrayprint.py:967(__call__)
```

Pymc3Sampler (slice sampler, no tuning):

```
 17290239 function calls (17035381 primitive calls) in 59.103 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   217496   11.242    0.000   11.242    0.000 {method 'acquire' of '_thread.lock' objects}
    23776    9.603    0.000    9.603    0.000 {built-in method amici._amici.runAmiciSimulations}
    23776    1.497    0.000    4.652    0.000 arrayprint.py:883(fillFormat)
    23776    1.454    0.000    1.606    0.000 numpy.py:155(__init__)
    47553    1.417    0.000    1.417    0.000 {built-in method _thread.start_new_thread}
    24782    1.370    0.000   55.474    0.002 function_module.py:743(__call__)
155393/155389    1.323    0.000    3.174    0.000 {built-in method numpy.array}
   473400    1.214    0.000    1.214    0.000 {built-in method numpy.core._multiarray_umath.dragon4_positional}
   237760    1.125    0.000    1.773    0.000 arrayprint.py:967(__call__)
   784608    0.967    0.000    0.967    0.000 {built-in method _libsbml.SwigPyIterator___next__}
```

**Comment by FFroehlich** [comment]
Yes, as far as I remember pymc3 automatically performs thinning.

**Comment by FFroehlich** [comment]
pymc doesn't perform thinning (see https://github.com/pymc-devs/pymc/issues/23). I suppose whats happening is that every sampling step requires multiple gradient/function value evaluations as NUTS automatically tunes the number of integration steps per sample, see https://docs.pymc.io/api/inference.html?highlight=nuts#pymc3.step_methods.hmc.nuts.NUTS

**Comment by FFroehlich** [comment]
Depending on where the bulk of these evaluations are done burn-in/sampling, the it may perform better at high sample numbers where the NUTS step size is well-tuned. Changing defaults may also help.

**Comment by yannikschaelte** [comment]
yes, I also could not find it does thinning (which also would not make any sense, only storage related). That it uses multiple evaluations per sample is unfortunate as it makes planning of maximum evaluation time more difficult. I think there is no option in pymc3 to limit the number of evaluations (one could ask for it, but unlikely). Thus, I would say it is important that we implement the ability to continue a started run.

**Comment by FFroehlich** [comment]
Overall limiting wall time would be a great feature, also for optimization.

**Comment by yannikschaelte** [comment]
closing here as this got clarified. for potential follow-up see https://discourse.pymc.io/t/limit-number-of-function-evaluations/5175
