### ISSUE TITLE
Allow assert

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#36]
Currently codacy complains about assert statements. Would it be possible to allow assert statements at least in the test folder? Or is there a way to without much ado change those assert statements? See also the discussion in https://github.com/fossasia/query-server/issues/332.

**Comment by dweindl** [comment]
I think generally we want to have the assertions also in the optimized code. I don't think we have any performance-critical ones. 

Just replace `assert`s by (the slightly longer) [`if not expression: raise AssertionError`](https://docs.python.org/2/reference/simple_stmts.html#the-assert-statement).

Inside tests, don't use `assert` but the checking/assertion functions of the test framework.

**Comment by dweindl** [comment]
Let's keep `assert` usage in non-testing code to minimum. They should be replaced by `raise` and appropriate errors.

**Comment by yannikschaelte** [comment]
yes agree, you can enable bandit again if you think that is better. I will use Exceptions instead of assert in real code, and in the tests use the unittest environment, giving assertEqual etc. that is fine for me.
