### ISSUE TITLE
Variable used before assignment warnings in plotting routines

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#364]
At least in: parameters, profiles.
Probably harmless, but can indicate wrong programming logic, should be avoided.

**Comment by plakrisenko** [comment]
For parameters plot was fixed in #418

**Comment by stephanmg** [comment]
Is this resolved yet and could be closed possibly?

**Comment by yannikschaelte** [comment]
true ... given the number of referencing commits let's pretend it's fixed. if someone opens pycharm and sees "variable used before assignment" warnings in the corresponding visualization routines, make a pr ^^
