### ISSUE TITLE
pypesto log level

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#367]
Often, we have useful information to print on screen. Currently, all is done via the `logging` module. The default is to only show `warning` and `error`, `info` is not shown. I would rather not print "information" on "warning" level. One could in pypesto centrally enable showing `info` as well. Then the level `debug` would remain for everything that is only to be shown when e.g. searching for bugs. Opinions?

Alternatively, one could employ `print` for info, but that I would rather not do, as this has a bunch of disadvantages.

**Comment by dweindl** [comment]
Let's not mix print and logging, can lead to weird output. 
In favor of showing `info` by default. Changing loglevel globally should be made easily accessible.

**Comment by elbaraim** [comment]
In favour of displaying `logging.info` as well.
