### ISSUE TITLE
Cannot use least squares optimizers

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#377]
I tried to use the least squares optimizer `ls_trf` for a model, where we have measured noise (i.e. numeric values in the `noiseParameter` column in the PEtab measurement file), because of:
`Cannot use least squares solver withparameter dependent sigma!`
The noise parameters are not in the parameter sheet, but the `noiseParameter1_...` is in the `noiseFormula` of the observable table. 
Discussed with @yannikschaelte that this might be, because gradients are still calculated for the noiseParameters. But as far as I understand it, it should be fine to use the least squares optimizers like this, right?

**Comment by yannikschaelte** [comment]
What does `rdatas[i]['ssigmay']` look like?

**Comment by LeonardSchmiester** [comment]
```
ret['rdatas'][0]['ssigmay']
array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.]],
....
```

**Comment by yannikschaelte** [comment]
`model.getParameterIds()`?

**Comment by LeonardSchmiester** [comment]
```
>>> model.getParameterIds()
('d1', 'm', 'd2', 'c', 'x_0', 'y_0', 'noiseParameter1_observable_x_t', 'noiseParameter1_observable_y_t')
```

**Comment by FFroehlich** [comment]
I assume this is due to the fact that parameters are fixed in pypesto but this is not reflected in `edata.plist` so amici doesn't know anything about it and computes nonzero sigmas which trigger the above message. can be solved by either implementing the correct `edata.plist` or subsetting `ret['rdatas'][0]['ssigmay']` in the respective check accordingly.

**Comment by yannikschaelte** [comment]
I agree this can be solved by using plist, see also https://github.com/ICB-DCM/pyPESTO/issues/226

**Comment by FFroehlich** [comment]
Fixed in https://github.com/AMICI-dev/AMICI/pull/1487 / https://github.com/ICB-DCM/pyPESTO/pull/621
