### ISSUE TITLE
OptimizeResult: Strictly enforce sorting, or not at all

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#378]
1) Currently, the `OptimizeResult.append()` method does not sort entries, this has to be done manually by `OptimizeResult.sort()`, as done as the end of `optimize.minimize()`. To be on the safe side, one could always sort when something gets appended. Or, one could not assume sorting at all, but then the visualization functions would need to account for sorting themselves.

2) When loading a result from file this is currently not checked imho. So if sorting is assumed, this needs to be enforced there as well.

**Comment by plakrisenko** [comment]
In waterfall plot there is a bug related to this. There seems to be sorting before waterfall plot (pypesto.visualize.waterfall line 159), however it's only applied to plotting the markers (lines 170 -197 ), not the line (lines 163 - 167). Can be observed, if one passes unsorted result to the `test_waterfall`.
