### ISSUE TITLE
Visualization: Number of steps per start

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#379]
just a line plot may suffice for starters

**Comment by plakrisenko** [comment]
I have started working on this (branch pl_visualization). Currently I've implemented plotting number of steps per start and wall-clock time per start. For both it's possible to plot a line plot or a histogram. Sorting is done by `fval` value and colors for the line plot are assigned the same way as it's done for the waterfall plot.

**Comment by yannikschaelte** [comment]
Sounds good, great!

**Comment by plakrisenko** [comment]
Are there any additional requests? Does anyone need to plot some other result attributes, besides `time` and `n_fval`?

**Comment by yannikschaelte** [comment]
We had the idea of being able to plot the waterfall plot and the number of function evaluations in one plot (@paulstapor @LeonardSchmiester ), using two different y axes. But I think that may be unnecessarily complex compared to just plotting the waterfall plot above the n_fval plot, so fine for me atm.

**Comment by yannikschaelte** [comment]
Would it be easy to plot also e.g. the number of gradients n_grad instead, or n_hess, n_res, n_sres? That may be of interest.

**Comment by paulstapor** [comment]
Hm... usually, number of function evaluations and number of gradient evaluations should go in line. But it might be interesting to either pass a flag to plot these different things one by one, or plot them at the same time... (using different colors)

**Comment by FFroehlich** [comment]
> Hm... usually, number of function evaluations and number of gradient evaluations should go in line. But it might be interesting to either pass a flag to plot these different things one by one, or plot them at the same time... (using different colors)

`n_fval` and `n_grad` will differ when there is active line-search. In my experience, they usually agree early on but may strongly deviate when optimization is close to convergence. I think having line plots of the history of `n_fval` vs `n_grad` or `n_res` vs `n_sres` may be interesting. Similarly line plots of time vs `n_fval`/`n_grad` may be interesting.

Not sure how relevant this is for everyday analysis though, could be helpful when comparing optimizers or evaluating home-cooked methods. Accordingly, its plausible to add these plots at a later time.

**Comment by yannikschaelte** [comment]
@plakrisenko Would you say this issue is addressed? Then please close.
