### ISSUE TITLE
Parameter and confidence interval plots: Rescale axes to bounds

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#394]
Add an option to rescale all bounds to cover the same interval, e.g. [0,1], on arbitrary units. This would
* allow to jointly plot variables that have very different domains
* inspect small intervals better, as then all intervals cover the full plot range.

**Comment by dweindl** [comment]
Completed in https://github.com/ICB-DCM/pyPESTO/pull/693
