### ISSUE TITLE
Keep track of minimum version numbers of dependencies

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#40]
Install-time dependencies should be listed with version numbers in setup.py

Optional / run-time dependency versions should be checked on import to provide more informative error messages than "... is not defined". See e.g. 
https://github.com/ICB-DCM/AMICI/issues/426.

**Comment by yannikschaelte** [comment]
so we just extract the current version of all used packages, and insert that as minimum requirement in setup.py? then it should be automatically updated if an existing version is not recent enough.

**Comment by dweindl** [comment]
Yes for those packages we want to list there, this would be the way to go. If these are too new for some reasons, we can check for the true minimum requirement.

For those packages we want to keep as optional it needs to be checked somewhere else.

**Comment by yannikschaelte** [comment]
there is the possibility to in setup.py specify optional requirements ``extra_requires = {'amici': ['amici']}``, installation would the be via ``pip3 install pypesto[amici]``

**Comment by dweindl** [comment]
Good point to add it there as well, but I would guess that this not how most people will install optional packages.
