### ISSUE TITLE
Store profiles in HDF5

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#410]
Store the profile results as part of the HDF5 result file.

**Comment by jvanhoefer** [comment]
@PaulJonasJost is this closed in the new release?

**Comment by PaulJonasJost** [comment]
> 
> 
> @PaulJonasJost is this closed in the new release?

Probably have to restore the branch and merge again?

**Comment by PaulJonasJost** [comment]
> 
> 
> @PaulJonasJost is this closed in the new release?

Yes, should be closed.
