### ISSUE TITLE
Profiling fails when having fixed indices and using the profile_index argument

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/pyPESTO#433]
Just found out that `profile_index` expects the reduced parameter vector. However, I think that's rather counter-intuitive. We should really make the user specify everything in the full dimension of the problem and I think, this is also the case for most of the API already. However, profile computation is lagging behind a little... :/

**Comment by paulstapor** [comment]
Argh, sorry, think I was wrong. Forget this issue...

**Comment by FFroehlich** [comment]
I think generally the most user-friendly thing to do is permit specification via parameter names. This would also have the advantage that code doesn't need to be updated if the model is updated.

**Comment by paulstapor** [comment]
Agree here... Would probably be the better api for users...
