### ISSUE TITLE
Doing predictions with pyPESTO

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/pyPESTO#435]
Hi,

I wanted to run forward simulations using pyPESTO, based on a PEtab problem and an optimization result from parPE.
So I would be happy, if I could write some class for pyPESTO, which creates simulations based on either a PEtab input, or a pyPESTO results file, or something similar (indeed, I will also need to create an interface for importing actually an ensemble of parameter vectors from a tsv, and either convert it into a pyPESTO results object or something similar pyPESTO can work with).

However, I want to simulate and plot predictions. Those predictions are not simply an AMICI or PEtab output, but somthing more complex... In my case: The ratio out of two simulations...
So a prediction should call amici simulations, and then apply some possible (user defined) postprocessing step... Or be defined by a callable function, which the user provides... 
So I would be happy to write something like a prediction class, which builds on top of the objective class or whatever is useful. I think a model prediction should be able to return a function value and a gradient, such that it can be at some later point used for prediction profiling or similar things... 

Any ideas on that? Stuff I should avoid? Dos and don'ts to be considered?

**Comment by FFroehlich** [comment]
Why is pyPESTO the right place to do this, I thought pyPESTO should primarily doing optimization and sampling? It sounds like all information you need from pypesto is some array of parameter values. My gut feeling is that the specification of the postprocessing is something that probably belongs in petab as thats where we currently also specify everything else related to plotting.

**Comment by paulstapor** [comment]
For the aim I currently have, yes, I do not need much from pyPESTO, that's true.
So maybe it makes sense to rather go for some add-on in PEtab. However, I think it makes sense to give pyPESTO an interface for that: If pyPESTO can deal with predictions, we can implement prediction profiles into pyPESTO, which is also a reasonable thing to have...

**Comment by dweindl** [comment]
May be outside of core parameter estimation, but agreeing with Paul, that prediction profiles or any kind of prediction uncertainty analysis would fit in here. True, could implement it as a separate library, but I am not sure whether the overhead will be worth the benefit. If we want to split things up, then in my opinion, it would be more sensible to extract a pypesto-amici-(petab) adapter.
Tthe visualizations, yes, they could go into PEtab.

**Comment by FFroehlich** [comment]
Okay, I agree. Wasn't trying to suggest a new library, just thinking whether it makes sense to have respective functionality in AMICI, but I now do agree that the best place is probably pyPESTO. The specification format probably makes sense to ultimately put this in PEtab, but I would suggest to first implement an API in pyPESTO and then see what exact requirements/pitfalls are.

**Comment by FFroehlich** [comment]
In terms of considerations, as this is something that I have already implemented to a certain degree for my applications: Consider parallelization using the task engine that is already implemented in pypesto. Specifically, it would be great if there is an API that permits the user to run individual simulations by specifying parameter index + simulation types, but also provides simple functions that implement loops that run over all parameters + simulation types. This would also make it simpler to parallelize externally using nextflow/snakemake.

**Comment by FFroehlich** [comment]
In my experience it was also pretty useful to build this around the existing objective as you get all of the parameter mapping etc for free, which can be quite relevant for complex setups.

**Comment by dweindl** [comment]
@paulstapor : This will also be very relevant for @plakrisenko, maybe the two of you can have a chat about required functionality and plan for implementation.

**Comment by dweindl** [comment]
@LarsFroehling : Probably also good for you to follow here.

**Comment by jvanhoefer** [comment]
@paulstapor This was closed with the new release, right?
