### ISSUE TITLE
PySB-PEtab importer

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#436]
With https://github.com/ICB-DCM/AMICI/pull/1175, AMICI will be able to handle PySB-based PEtab problems. Would be great to support PySB then also in pyPESTO.

I guess easiest would be adding `class PetabImporterPysb(PetabImporter)` to `pypesto.petab.pysb_importer`. Shouldn't introduce too much new code, as most of `PetabImporter` can be used as is and less than a handful of functions need to be overridden.

**Comment by jvanhoefer** [comment]
@dweindl this is closed with the new release, right?
