### ISSUE TITLE
Question: Steadystate prediciton

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/pyPESTO#440]
Question: how is steadystate prediciton defined? Is it default, and how can I specify if and when steadystate prediciton  is used?
I am getting the following error:
```
Exception has occurred: ValueError
Steadystate prediciton is not supported formodels with conservation laws!
```
in
`site-packages\pypesto\petab\importer.py", line 267, in create_objective`
after running this code:
```
petab_problem = petab.Problem.from_yaml('configuration.yaml')
testOut = petab_problem.get_optimization_to_simulation_parameter_mapping()
importer = pypesto.petab.PetabImporter(petab_problem)
model = importer.create_model()
import libsbml
converter_config = libsbml.SBMLLocalParameterConverter().getDefaultProperties()
petab_problem.sbml_document.convert(converter_config)
obj = importer.create_objective()
```

**Comment by jvanhoefer** [comment]
To me, this does not seem to be an issue related to pyPESTO, but to your model: As the Error Message suggests, your model has a conservation law and such systems do not have an unique steady state... (so there is no steady state to predict...). If you want to preequilibrate/use steady state data, I would suggest to change your model accordingly, so that it does not contain a conservation law any more.  

(Here some reason for the error: Conservation law = some quantity is preserved over time, i. e. some protein only gets (de)phosphorylated, but not generated/degraded in your model. Then [Protein] + [pProtein] = const. If you now wish to compute a steady state, your steady state will not only depend on the parameters, but also on the total amount of Protein (in both states). Hence no steady state can be defined/computed.).

**Comment by thomassligon** [comment]
Hello Jan, thanks for the quick response!

The model I am using here was formulated in matPESTO and later converted to pyPESTO and PETab. I didn't get this error in matPESTO. At that time, preequibrilation was done in a very naïve way, by simply running the simulation for something like 10**6 seconds.

You say "If you want to preequilibrate/use steady state data", so you may be assuming that I want to use it. Clearly, pyPESTO is assuming that I want to use steadystate prediction. But why does it assume that? Where is it coded? I didn't find that when I read the API documentation, so I formulated a question. In other words, I am not suggesting that this is an issue in pyPESTO but that I don't understand how to specify whether steadystate prediction should be used or not.

Now for your explanation. It is definitely helpful. But, I could just create a parameter and use it for the initial concentration of Protein. That way [Protein]+[pProtein]=P0, which is a constant parameter. Then, the steady state will depend only on the parameters. So, I don't understand the explanation.

On the other hand, exactly this kind of behavior is a big problem in the original model. There were many proteins that were neither created nor degraded, but sometimes phosphorylated. Similarly, there was a lot of complex formation involving substances that were neither created nor degraded. This is because the original model was created as a kind of big "cartoon" that was supposed to cover all known reactions, and things like degradation were treated as obvious, and not included. I put a lot of work into defining creation and degradation reactions, but I am probably not finished with it yet.

**Comment by yannikschaelte** [comment]
Hi @thomassligon !

in pyPESTO you can specifiy whether to use steady state guesses via the `pypesto.AmiciObjective(guess_steadystate=False)` option. If you use PEtab, you should be able to pass `guess_steadystate=False)` to the `pypesto.petab.PetabImporter.{create_objective;create_problem}` functions. Then this error should occur no longer.

**Comment by yannikschaelte** [comment]
Unfortunately, when using PEtab these options are really well hidden, thanks for pointing that out. We may add a hint that all of the options of AmiciObjective can be used.

**Comment by dweindl** [comment]
> Unfortunately, when using PEtab these options are really well hidden, thanks for pointing that out. We may add a hint that all of the options of AmiciObjective can be used.

I'd vote for defaulting to `False`. The default should be generally applicable.

**Comment by thomassligon** [comment]
@yannikschalte I changed the last line of my code to
`obj = importer.create_objective(guess_steadystate=False)`
That works and I no longer get the error.
I've also added a task for myself to look at all conservation laws in the model.

**Comment by yannikschaelte** [comment]
> > Unfortunately, when using PEtab these options are really well hidden, thanks for pointing that out. We may add a hint that all of the options of AmiciObjective can be used.
> 
> I'd vote for defaulting to `False`. The default should be generally applicable.

But default = True can save considerable simulation time. Both fine for me. @FFroehlich I think we discussed this at some point. Any opinions?

**Comment by dweindl** [comment]
> But default = True can save considerable simulation time. 

Not arguing with that. But I'd prefer something that is running slow by default over something that is not running at all ;).

**Comment by thomassligon** [comment]
I would like to make a trivial change. The only way I know is

- clone a copy
- create a new branch
- make the change as a pull request

Is there an easier way?
The change is:
in:
`https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/amici.py`
old:
```
                raise ValueError('Steadystate prediciton is not supported for'
                                 'models with conservation laws!')
```
new:
```
                raise ValueError('Steadystate prediction is not supported for '
                                 'models with conservation laws!')
```

**Comment by dweindl** [comment]
> > But default = True can save considerable simulation time.
> 
> Not arguing with that. But I'd prefer something that is running slow by default over something that is not running at all ;).

P.S.: Why not make the default model dependent? If supported, switch it on, if not switch it off. If requested by the user, but not supported, raise.

**Comment by yannikschaelte** [comment]
> I would like to make a trivial change. The only way I know is
> 
> * clone a copy
> * create a new branch
> * make the change as a pull request
> 
> Is there an easier way?

@thomassligon that is the way to go, yes. you can omit the creating of a new branch and directly create a pull request from thomassligon:develop -> icb-dcm:develop.

Thanks in advance!

**Comment by thomassligon** [comment]
Thanks to everyone who helped.
