### ISSUE TITLE
pypesto.ScipyOptimizer()

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/pyPESTO#443]
This line of code
`optimizer = pypesto.ScipyOptimizer()`
as suggested here
[https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example/petab_import.ipynb](https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example/petab_import.ipynb)
leads to this exception
```
Exception has occurred: AttributeError
module 'pypesto' has no attribute 'ScipyOptimizer'
```
Could it be that something has been moved?

**Comment by yannikschaelte** [comment]
You have to import via
```python
import pypesto.optimize as optimize
optimizer = optimize.ScipyOptimizer()
```

**Comment by thomassligon** [comment]
Good, that fixed this one. Then, I also guessed that I need
`import pypesto.engine as engine`
and, instead of
`engine = pypesto.MultiProcessEngine()`
I need
`engine = engine.MultiProcessEngine()`
meaning that there are two small document errors in
[https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example/petab_import.ipynb](https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example/petab_import.ipynb)
But then I get a new problem:
`AttributeError: ("module 'amici.amici_without_hdf5' has no attribute 'writeSolverSettingsToHDF5'", 'Pickling the AmiciObjective requires an AMICI installation with HDF5 support.')`

**Comment by yannikschaelte** [comment]
Thanks for pointing out the documentation errors, we will fix those. About the hdf5: In order to use the MultiProcessEngine, AMICI must have been installed with hdf5 support (see the amici INSTALL.md for instructions). This is because we need to copy it here internally, which only works via hdf5 currently. If non-parallel execution is fine for you for the moment, consider using pypesto.engine.SingleCoreEngine instead.

**Comment by thomassligon** [comment]
Good. I'm starting with the single-core engine and will install hdf5 and use the multi-core engine as a later step.
Now, I'm getting a lot of AMICI errors, including
`Steady state computation failed. First run of Newton solver failed: No convergence was achieved. Simulation to steady state failed. Second run of Newton solver failed: No convergence was achieved.`
I think that the Newton solver was added after what I last used in MATLAB.
This is progress and certainly solved the issue originally reported here.
