### ISSUE TITLE
keyword argument x_guesses is not passed to pypesto problem

### ISSUE THREAD

**Issue by stobiblum** [ICB-DCM/pyPESTO#445]
Hey,

I wanted to use the keyword argument `x_guesses` to set some customised parameter start points for the optimization, using 
```
obj = importer.create_objective(model=amici_model)
problem = importer.create_problem(obj, x_guesses=x_guesses)
```
This failed because `x_guesses` as keyword argument is only passed to the objective and not to the problem. 

I could fix it by adding `x_guesses = None` before `**kwargs` in line 311 of pyPESTO/petab/importer.py (https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/petab/importer.py#L311) and adding `x_guesses=x_guesses` in line 349.

I think it would be good to fix it in the develop version as well, so that customised start points for parameter estimation can easily be set. Thank you in advance.

**Comment by yannikschaelte** [comment]
Agreed! In general, we should allow all arguments in problem/objective constructors in the petab factory methods as well, if they make sense.

**Comment by paulstapor** [comment]
> Hey,
> 
> I wanted to use the keyword argument `x_guesses` to set some customised parameter start points for the optimization, using

No, I don't think you really want that... pyPESTO creates x_guesses automatically based on the last optimization step, I think. Please correct me if I'm wrong, @yannikschaelte . However, I would strongly guess that these x_guesses will be better than any x_guesses you can provide prior to optimization... ;)

**Comment by LeonardSchmiester** [comment]
> pyPESTO creates x_guesses automatically based on the last optimization step

What do you mean with last optimization step? `x_guesses` are just the initial parameters, which are per default randomly sampled.

**Comment by paulstapor** [comment]
> > pyPESTO creates x_guesses automatically based on the last optimization step
> 
> What do you mean with last optimization step? `x_guesses` are just the initial parameters, which are per default randomly sampled.

Sorry, I mean "previous" optimization step

**Comment by paulstapor** [comment]
At least, if pyPESTO creates those guesses automatically, then I would discourage using x_guesses yourself. However, I'm not 100% sure if it does so...

**Comment by stobiblum** [comment]
Per default pyPESTO creates `x_guesses` automatically for all starts before starting with the following optimization steps. 
But pyPESTO also offers the possibility to apply customised `x_guesses`, which are passed to the objective and not the problem. Because they are currently not passed to the problem itself, the customised `x_guesses` wont be recognized as start points for the optimization.

**Comment by yannikschaelte** [comment]
@stobiblum is right. @paulstapor what you mean is also interesting as part of "intelligent Startpoints", but not implemented yet.

**Comment by paulstapor** [comment]
> @stobiblum is right. @paulstapor what you mean is also interesting as part of "intelligent Startpoints", but not implemented yet.

I just see that I might have totally mistaken the actual point of the conversation... :sweat_smile: 
You're talking abut guesses for optimization. Due to all the preequilibration discussion, I thought you're talking about guesses for the steady state solver (which are afaik implemented) for preequilibration.

totally different topic. Just forget what I've said, I'm sorry for the confusion....
