### ISSUE TITLE
bug in petab importer

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#447]
pretty sure that 

https://github.com/ICB-DCM/pyPESTO/blob/8951c3992aa031524a6e62ca6a28e058937f699c/pypesto/petab/importer.py#L288

is not doing whatever it is intended to do. If `prior_type_entry == 'uninformative'` then `np.isnan(prior_type_entry)` will fail with a TypeError.

**Comment by FFroehlich** [comment]
Moreover 'uninformative' is not a valid petab identifier for petab.OBJECTIVE_PRIOR_TYPE.

**Comment by yannikschaelte** [comment]
Agreed, "uninformative" is the suggestion for PEtab 2.0, current standard is "parameterScaleUniform". @jvanhoefer could you have a look at this issue?

**Comment by jvanhoefer** [comment]
:+1: I am on vacation until next Wednesday, might have to wait until then :)

**Comment by FFroehlich** [comment]
ping @jvanhoefer

**Comment by jvanhoefer** [comment]
> Agreed, "uninformative" is the suggestion for PEtab 2.0, current standard is "parameterScaleUniform". @jvanhoefer could you have a look at this issue?

You are right, I implemented only an import for PEtab 2.0 and not for the current version, I change that :)
