### ISSUE TITLE
Example notebooks cause CI timeout

### ISSUE THREAD

**Issue by dilpath** [ICB-DCM/pyPESTO#450]
[Example](https://travis-ci.com/github/ICB-DCM/pyPESTO/builds/181652018)

Timeout occurs because all notebooks are run from a [single script](https://github.com/ICB-DCM/pyPESTO/blob/master/test/run_notebook.sh), which is required to return within 10 minutes.

Could be fixed by splitting this up into multiple files, changing CI options if possible, or changing settings in example notebooks to reduce their individual run times.

The [model selection notebook](https://github.com/ICB-DCM/pyPESTO/blob/feature_ms/doc/example/model_selection.ipynb) takes some time to run, as optimisations for many models are performed.
`n_starts` was set to 3 for all optimisations in this notebook a while ago to pass CI, but the notebook now fails CI again after merging develop into the branch.

**Comment by dweindl** [comment]
> Timeout occurs because all notebooks are run from a [single script](https://github.com/ICB-DCM/pyPESTO/blob/master/test/run_notebook.sh), which is required to return within 10 minutes.

Easy (temporary) fix: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by yannikschaelte** [comment]
I think that not necessarily all notebooks need to run as part of CI. It is good to frequently check most to see if changes break them accidentally (and not caught by unit tests), but some notebooks will just take some time to run, and one should not artificially reduce their runtime to make them fit for CI. Therefore, I think a positive/negative list may be good, as in https://github.com/ICB-DCM/pyABC/blob/master/test/run_notebooks.sh.

Of course, in addition one can parallelize the notebook run into e.g. 2 chunks, as this already takes quite long.

**Comment by yannikschaelte** [comment]
Rather a negative list than a positive one to make sure new notebooks are added by default.

**Comment by yannikschaelte** [comment]
Long fixed
