### ISSUE TITLE
Support automatic generation of MCMC-based prediction and validation confidence intervals

### ISSUE THREAD

**Issue by elbaraim** [ICB-DCM/pyPESTO#458]
I think it would be good to have implemented the calculation of percentile-based confidence intervals for the model states and observables after a MCMC run is finished.
Probably not as a default option (such as geweke convergence test) but having the option already built-in in pyPESTO would make things easier.
Also would be good to add the corresponding visualization routine, but that may be not a priority atm.

Any thoughts contrary to this?

**Comment by jvanhoefer** [comment]
Regarding validation intervals: @dilpath is currently implementing functionality to compute synthetic data. Can probably be reused here... :)

**Comment by dilpath** [comment]
> Regarding validation intervals: @dilpath is currently implementing functionality to compute synthetic data. Can probably be reused here... :)

Currently in draft PR's. Let me know if you would like something specific implemented for this feature.

Implementation in AMICI: [PR](https://github.com/AMICI-dev/AMICI/pull/1283)
Example optimisation with synthetic data: [notebook](https://github.com/ICB-DCM/pyPESTO/blob/feature_synthetic_data/doc/example/synthetic_data.ipynb), [PR](https://github.com/ICB-DCM/pyPESTO/pull/482)
PEtab base class: [code](https://github.com/PEtab-dev/PEtab/blob/feature_synthetic_data/petab/simulate.py), [PR](https://github.com/PEtab-dev/PEtab/pull/472)
