### ISSUE TITLE
Automatic generation of PEtab visualization tables from fitting results

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#461]
I think, it would be great, to have a function, that takes the result of a parameter optimization run from a _PEtab-problem_ and creates a _PEtab visualization table_ (+necessarily a simulation table). E.g. for each condition  a subplot, that contains  trajectories of the observables + data points (+ (fitted) std.dev...).

**Comment by jvanhoefer** [comment]
(I know, that visualization is potentially problem dependent, but this should still be a rather standard plot)

**Comment by plakrisenko** [comment]
Which information from the optimization result should be used for visualization table generation? I mean, is there a reason why you think in should be implemented in pyPESTO?
Have you tried `save_vis_spec` function from `petab.visualize`?
