### ISSUE TITLE
Non-unique x_names crash history tracing

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#488]
Should probably ensure that `pypesto.Problem.x_names` only contains unique values.

**Comment by yannikschaelte** [comment]
Agreed. I am not sure whether we had that discussion somewhere already, but do we want to (like for PEtab) define a new field x_ids, which defaults to the names (and vice versa)? Names for visualization, e.g. including latex, and ids for unique, simple identification? If we use no ids but use names as ids, would there be any problems?

**Comment by FFroehlich** [comment]
> Agreed. I am not sure whether we had that discussion somewhere already, but do we want to (like for PEtab) define a new field x_ids, which defaults to the names (and vice versa)? Names for visualization, e.g. including latex, and ids for unique, simple identification? If we use no ids but use names as ids, would there be any problems?

Sounds good! The issue here is that multindexing [(col, math.nan)] doesn't work if the level 2 column contains non-unique values (which probably generally isn't a good idea, but apparently is possible).

**Comment by yannikschaelte** [comment]
Huu, so much stuff left open far too long already ........ will have a look soon if I work on pyPESTO next (and not on pyABC again ...).

**Comment by yannikschaelte** [comment]
For simplicity, for the moment I would just ensure that x_names are unique here, as I wouldn't see why the could be allowed to not be. x_ids as non-readable variants can be introduced later then.
