### ISSUE TITLE
nan values in cov during sampling

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#499]
Seems to happen rather rarely, but did happen in

https://travis-ci.com/github/ICB-DCM/pyPESTO/builds/199846428

> 1374    pypesto/sample/sample.py:68: in sample
1375    sampler.sample(n_samples=n_samples)
1376pypesto/sample/metropolis.py:56: in sample
1377    x, lpost, lprior = self._perform_step(
1378pypesto/sample/metropolis.py:110: in _perform_step
1379    self._update_proposal(x, lpost,
1380pypesto/sample/adaptive_metropolis.py:87: in _update_proposal
1381    self._cov = regularize_covariance(
1382pypesto/sample/adaptive_metropolis.py:152: in regularize_covariance
1383    eig = np.linalg.eigvals(cov)
1384<__array_function__ internals>:5: in eigvals
1385    ???
1386../../../virtualenv/python3.8.1/lib/python3.8/site-packages/numpy/linalg/linalg.py:1063: in eigvals
1387    _assert_finite(a)
1388_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
1389
1390arrays = (array([[nan]]),), a = array([[nan]])
1391
1392    def _assert_finite(*arrays):
1393        for a in arrays:
1394            if not isfinite(a).all():
1395>               raise LinAlgError("Array must not contain infs or NaNs")
1396E               numpy.linalg.LinAlgError: Array must not contain infs or NaNs
1397
1398../../../virtualenv/python3.8.1/lib/python3.8/site-packages/numpy/linalg/linalg.py:209: LinAlgError
1399----------------------------- Captured stderr call -----------------------------
1400

**Comment by dilpath** [comment]
It might be that (e.g. AMICI) errors are not handled during sampling, like they are for optimization, and so the error propagates.

[Comment on similar issue in optimizer](https://github.com/ICB-DCM/pyPESTO/pull/13#discussion_r211108904)

[Current fix in optimizer](https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/optimize/optimizer.py#L63)
