### ISSUE TITLE
Plotting of sampling results

### ISSUE THREAD

**Issue by stobiblum** [ICB-DCM/pyPESTO#502]
Hey,

the function `sampling_parameters_trace()` defined in visualize/sampling.py has a return statement in line 192. There is just `ax` returned, meaning that you can only access information about the last subplot. I think you could simply return `axes` instead of `ax` to solve this.

Also, the function defines the argument `ax` (line 103). However, the parameter `ax` is overwritten in line 171 without using the supplied `ax`.

Best,
Tobi

**Comment by yannikschaelte** [comment]
Agreed, this is still a bug.
