### ISSUE TITLE
Rtf fails

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#504]
Since a few merges to develop (2 weeks?). Did not check details, but before next release Rtf needs to be fixed again.
Maybe good opportunity to check doc unit testing.

**Comment by yannikschaelte** [comment]
e.g. https://readthedocs.org/projects/pypesto/builds/12352164/ (fides?)

**Comment by FFroehlich** [comment]
Yes, thats fides, either needs to be mocked or imported for rtd. Adding RTD as check for PRs would help. Can be done after building for PRs is enabled in the RTD preferences.

**Comment by yannikschaelte** [comment]
I assume that the same will lead to pypesto failing on any system where fides is not installed, therefore that should be fixed? Maybe one could also add a test system where amici+pymc3+... are not installed, to check whether a simple optimization using scipy works there.

**Comment by FFroehlich** [comment]
> I assume that the same will lead to pypesto failing on any system where fides is not installed, therefore that should be fixed? Maybe one could also add a test system where amici+pymc3+... are not installed, to check whether a simple optimization using scipy works there.

Oh thats a good point. Using a forward reference in the typehint should fix that issue. Not sure whether thats already sufficient for RTD, but it might be.

**Comment by FFroehlich** [comment]
looks like forward reference was sufficient.
