### ISSUE TITLE
normalize() accidentally overwrites bounds

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#515]
When fixing #509, I found, that we accidentally overwrite the bounds in the `normalize()` function `problem`: If the bounds do not contain the fixed values, we overwrite `self.ub_full`:

https://github.com/ICB-DCM/pyPESTO/blob/8275751eba87efedd6ad1e6923a94d7de0603ddd/pypesto/problem.py#L174

We then set `self.ub_full[self.x_free_indices] = self.ub`, which looks like it recovers the values from `self.ub`, BUT it doesn't: `self.ub` is a `@property` function, that itself only returns the corresponding values of `self.ub_full`. 

Those were lost, when initializing/overwriting these values with `np.empty`.

**Comment by yannikschaelte** [comment]
Right. Solution would be to use a local varaible, also for lb.

**Comment by jvanhoefer** [comment]
That's what my PR does :)
