### ISSUE TITLE
Output Mapping

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#52]
The current implementation of the output mapping is a overly complicated. The empirical result of this complexity is that everytime I check the code, it is not doing what is supposed to, but still miraculously passing the testcases. 

We either need better tests for better coverage or substantially reduce the complexity of the output mapping.

**Comment by yannikschaelte** [comment]
You mean the Objective class? Can you specify what is too complicated? I agree that in particular the AmiciObjective output is too complicated, bc there are mappins from dict to tuple and back. There are a few things to consider: The input and output have to be mapped to exclude fixed parameters. Let me shortly try to explain how I devised the objective to work (if this is not what you meant, I wanted to write this down anyway):

Eventually, everything goes through ``__call__`` https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/objective.py#L470, where the parameter mappings happen and the history object is updated. ``_call_mode_fun`` and ``_call_mode_res`` should not be called directly, but only ``__call__`` and the ``get_``... funtions. The ``has_``... functions (https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/objective.py#L446) can be used in the Optimizer class to see what the Objective can calculate.
The real fun happens in ``_call_unprocessed`` (https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/objective.py#L514), where fval, grad etc. are evaluated. To update the history correctly and return the correct values, here everywhere dictionaries are used.
The method ``call_amici`` (https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/amici_objective.py#L87) puts itself into the center of this and calculates within call_unprocessed fval, grad etc..

Goal was to disentangle the objective value calculations and the jotting down of history data etc.. If there is a simpler way, it shall be welcome :) .

**Comment by FFroehlich** [comment]
I think the part you described is mostly fine for me. The stuff that always causes trouble for me is how `_call_mode_fun` and `_call_mode_res` interface to `fun`, `grad`, `res`, `sres`.

The problems I identified this time were:

I) AmiciObjective was not using the vectorised return, so the call to `map_to_output` was not necessary (and calling it upstream and downstream of `_call_unprocessed` was essentially asking for trouble) and we were effectively making additional calls to compute derivatives below the maximum order (which is a particularly poor idea when computing second order sensitivities ...)

II) The call to `map_to_output` at the end of `AmiciObjective` was wrong, because `fun` is expected to return `(nllh, snllh, ssnllh)` or `(res, sres)` but `map_to_output` would already do a subselection these vectors according to the specified `sensi_orders`.

This miraculously fixes some really weird issues that I had with the finite difference calculations in check_grad, but I honestly have no idea why.

I will post a PR that fixes these issues soon.
