### ISSUE TITLE
OptimizationResultHDF5Writer fails to overwrite existing results

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#529]
```
writer = OptimizationResultHDF5Writer(rfile)
writer.write(result, overwrite=True)
```

Will fail with a broadcasting error if the dimension of the problem changed between saving of results.

**Comment by PaulJonasJost** [comment]
Is this bug still existent? could be that it was fixed (at least i testetd saving two optimization results with different `n_starts` and it worked.

**Comment by FFroehlich** [comment]
As far as I recall, it's not about changing `n_starts`, but `dim` in the problem.

**Comment by PaulJonasJost** [comment]
> 
> 
> As far as I recall, it's not about changing `n_starts`, but `dim` in the problem.

If you are referring to `dim/dim_full` from the problem, i just tried two different models (first `dim=3, dim_full=8`, then `dim=dim_full=17`). Still worked for me.

**Comment by FFroehlich** [comment]
> > As far as I recall, it's not about changing `n_starts`, but `dim` in the problem.
> 
> If you are referring to `dim/dim_full` from the problem, i just tried two different models (first `dim=3, dim_full=8`, then `dim=dim_full=17`). Still worked for me.

Yes, okay, then I guess this is already fixed and can be closed! Thanks for checking!
