### ISSUE TITLE
Support PEtabs initializationPrior

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#534]

**Comment by jvanhoefer** [comment]
I see two ways to proceed here: 
* adding a `startpoint_method` as an additional property of the `pypesto.Problem`. (This would mostly be `None` and hence handled as it is now)
* adding a `create_startpoint_method` as part of the `petab.importer`, which can be used to generate such a method.

I see disadvantages in both approaches: For the first one, we would make the start `startpoint_method` part of the problem, which it technically is not. The second solution would still as default not sample from PEtabs `initializationPrior`. Hence I am in favor of solution 1.

Of course I would use the functionality of PEtabs sampling routines.

@yannikschaelte, @dweindl @FFroehlich any suggestions? :)

**Comment by FFroehlich** [comment]
Well if `initializationPrior` is part of the petab problem, then I would argue that it makes sense to also have it as part of the pypesto problem. `ub_init` and `lb_init` are also part of the pypesto problem, so I don't see why `startpoint_method` shouldn't be. One could rename it to `optimization_startpoint_method` or is it also possible to initialize sampling in the same way?

**Comment by yannikschaelte** [comment]
I agree, can  be seen as part of the problem. No need to rename to optimization_... . If we ever have a sampling method that can use such startpoints (currently it is supposed to come from previous optimization or manually), it would use the same.

**Comment by dweindl** [comment]
Would also see it as part of the problem, agreeing with going for your first suggestion.
