### ISSUE TITLE
OptimizationResultHDF5Writer deletes history from results

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#549]
The HDF5 writer may not be able to write the history, but I don't think thats a valid reason to delete it ;)

**Comment by yannikschaelte** [comment]
A typical stress overreaction.

**Comment by PaulJonasJost** [comment]
I Think this was resolved (at least in develop)?

**Comment by PaulJonasJost** [comment]
should have been PR #564 in `save_to_hdf5.py` l. 152+153
