### ISSUE TITLE
Waterfall plot with multiple results doesn't handle unsorted optimizer results well 

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#569]
[Chen_MSB2009_all_starts_adjoint.pdf](https://github.com/ICB-DCM/pyPESTO/files/6025931/Chen_MSB2009_all_starts_adjoint.pdf)

**Comment by PaulJonasJost** [comment]
@FFroehlich just a question as you said unsorted: Would you want it to be displayed as a sorted waterfall or unsorted?

**Comment by FFroehlich** [comment]
I think a waterfall plot should always be sorted.

**Comment by yannikschaelte** [comment]
There is generally no information in unsorted waterfall plots, so they should always be sorted. For debugging purposes of e.g. startpoint index vs final value, unsorted may make sense, but that is a different topic then.
