### ISSUE TITLE
parameter plot does not work if fixed_parameters are used

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#58]
pypesto.visualize.parameters fails if because dimensions of ub and lb (?) doe not agree with the numbers of parameters

```
~/Documents/GitHub/src/pypesto/pypesto/visualize/parameters.py in parameters(result, ax)
     31 
     32     return parameters_lowlevel(xs=xs, fvals=fvals, lb=lb, ub=ub,
---> 33                                x_labels=None, ax=ax)
     34 
     35 

~/Documents/GitHub/src/pypesto/pypesto/visualize/parameters.py in parameters_lowlevel(xs, fvals, lb, ub, x_labels, ax)
     88     parameters_ind = np.array(parameters_ind).flatten()
     89     if lb is not None:
---> 90         ax.plot(lb.flatten(), parameters_ind, 'k--', marker='+')
     91     if ub is not None:
     92         ax.plot(ub.flatten(), parameters_ind, 'k--', marker='+')

/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1865                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1866                         RuntimeWarning, stacklevel=2)
-> 1867             return func(ax, *args, **kwargs)
   1868 
   1869         inner.__doc__ = _add_data_doc(inner.__doc__,

/usr/local/lib/python3.7/site-packages/matplotlib/axes/_axes.py in plot(self, *args, **kwargs)
   1526         kwargs = cbook.normalize_kwargs(kwargs, _alias_map)
   1527 
-> 1528         for line in self._get_lines(*args, **kwargs):
   1529             self.add_line(line)
   1530             lines.append(line)

/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py in _grab_next_args(self, *args, **kwargs)
    404                 this += args[0],
    405                 args = args[1:]
--> 406             for seg in self._plot_args(this, kwargs):
    407                 yield seg
    408 

/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs)
    381             x, y = index_of(tup[-1])
    382 
--> 383         x, y = self._xy_from_xy(x, y)
    384 
    385         if self.command == 'plot':

/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py in _xy_from_xy(self, x, y)
    240         if x.shape[0] != y.shape[0]:
    241             raise ValueError("x and y must have same first dimension, but "
--> 242                              "have shapes {} and {}".format(x.shape, y.shape))
    243         if x.ndim > 2 or y.ndim > 2:
    244             raise ValueError("x and y can be no greater than 2-D, but have "

ValueError: x and y must have same first dimension, but have shapes (61,) and (66,)
```

**Comment by JanHasenauer** [comment]
Dear Dantong, could you please correct this?

**Comment by FFroehlich** [comment]
After dealing a bit more with the free index code, the problem seems to be that `ub` and `lb` are shortened after application of `x_free_indices`, but parameters are stored in full in the results.
Options are to either
- store full `lb` and `ub` and use them for plotting
- only plot free parameters in parameter plot

**Comment by yannikschaelte** [comment]
yep, that is correct. the bounds are stored only in the reduced space, because bounds on fixed parameters don't really make sense. Since x0, the gradient and so on in the result are however stored in full dimension, i now think that it makes sense to store something like lb_full, ub_full.
On whether to plot only the estimated parameters, or also the fixed ones, I have no particular opinion about. Any preferences? One could also implement a flag, should not be too complicated.

**Comment by DantongWang** [comment]
So if we want to store also the lb_full and ub_full, then there would not be too much change in the visualization part. I will wait for a final decision to start changing. ; )
For me personally, it would be more flexible to have a flag.

**Comment by FFroehlich** [comment]
I suppose it is probably confusing to plot fixed parameters by default, but an option to also show them would probably make sense.

**Comment by yannikschaelte** [comment]
Ok, so let's add an option. @DantongWang Could you do that? When you have questions on how to extract the fixed/all parameters and bounds, please just ask me (I think that is not so well documented yet).

**Comment by DantongWang** [comment]
Sure, just started working on it, will probably finish until tomorrow.

**Comment by yannikschaelte** [comment]
@DantongWang: looks good to me, just one more conceptual question to all: when we want to plot also the fixed parameters, what to do in the fixed dimensions? options would be to 1) lb=ub=the fixed value (meaning the boundaries converge to a point and then diverge again), 2) just don't draw (meaning the lines would be interrupted, can look bad if many parameters are fixed), 3) something else?

**Comment by dweindl** [comment]
> 2)

I don't see how including fixed parameters in this kind of visualization does make sense. The main point is to see the distribution (or any correlations) of parameter estimates over multiple optimizer runs. For the optimizations we plot together, I think the fixed parameters are always fixed to the same value. They just add visual clutter.

**Comment by DantongWang** [comment]
@yannikschaelte I just pushed a pre-version as a branch 'fixed_par_visualization' for plotting fixed parameters. What it does now is as your 2nd option. But it looks indeed not so good because of the interruption. I am also thinking about plotting the lb and ub at the same point as the fixed value, it should look better.

**Comment by dweindl** [comment]
> It makes sense when combining results from multiple fitting runs with varying fixed parameter values

Yes, then, and only then. Yet, I am not sure, if that is not too much information to include in `problem` (aka "optimization problem", with which the fixed parameters don't have too much to do).

**Comment by FFroehlich** [comment]
I agree. Thus my recommendation was not to plot them by default and include an option to plot them if requested (It's not a strong opinion, but I would rather plot the boundaries as provided by the user)

**Comment by JanHasenauer** [comment]
I agree. The default should be to not plot them. If plotted the user provided boundaries should be used. If no boundaries are provided the lines for lb and ub should be interrupted.

**Comment by yannikschaelte** [comment]
yep, that's exactly how we implemented it now, i think.
