### ISSUE TITLE
Profiling: pypesto_result.profile_result.list is empty after saving/loading as hdf5 file

### ISSUE THREAD

**Issue by IvaEwert** [ICB-DCM/pyPESTO#581]
Hi, 

I tried to save my profiling result in a hdf5-file, but when I load the file, the `pypesto_result.profile_result.list`
is somehow empty. Do you have an idea what might be the problem?

My scripts for saving/loading, the corresponding optimization result and the PEtab files are attached.

Best,
Iva
[Example.zip](https://github.com/ICB-DCM/pyPESTO/files/6108915/Example.zip)

**Comment by PaulJonasJost** [comment]
so I think u need to use `develop` and change the the following lines:
* OptimizationResultHDF5Reader –> ProfileResultHDF5Reader
* OptimizationResultHDF5Writer –> ProfileResultHDF5Writer

**Comment by IvaEwert** [comment]
Ah okay, thank you!
