### ISSUE TITLE
Decrease stochastic test failure

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#583]
As @dweindl suggested, for all tests that can stochastically fail with some probability >0 (e.g. sampling, optimization): Rerun, and only if twice failed, consider a failure. This way, a failure probability of say 0.01 would be 0.0001.

Easy to realize via a decorator.

**Comment by dweindl** [comment]
https://github.com/pytest-dev/pytest-rerunfailures

**Comment by yannikschaelte** [comment]
done now for a few tests, needs to be dynamically adjusted if tests are observed to fail.
