### ISSUE TITLE
Single load/save function for all pyPESTO result attributes

### ISSUE THREAD

**Issue by dilpath** [ICB-DCM/pyPESTO#588]
e.g.
```python
pypesto.store.write_result(pypesto_result: pypesto.Result, 'pypesto_result.hdf5')
pypesto_result = pypesto.store.read_result('pypesto_result.hdf5')
```
Should save all results if available i.e. optimization/profiling etc.

Can emit a warning for results that cannot be saved completely (e.g. `pypesto.Problem.objective`)

Possibly also optional toggles to not save certain attributes, e.g.
```python
write_result(pypesto_result, 'pypesto_result.hdf5', profile=False)
```

For the separate HDF5 files from optimization/profiling/etc, maybe generate them using pre-existing methods then combine into a e.g. ZIP archive?

**Comment by PaulJonasJost** [comment]
Do we want separate HDF5 files or one that contains all?

**Comment by yannikschaelte** [comment]
I think for common applications one file to contain them all may be preferable, as it enables easier sharing. a reason to end up with multiple files would only be if e.g. the traces consume a lot of memory (does someone have intel on typical file sizes?)

**Comment by PaulJonasJost** [comment]
Not sure but traces cannot be saved right now unless we use SingleCores so might be not as relevant right now? Or am I not up to date?
