### ISSUE TITLE
wrong bounds are chosen in parameter plot when not all parameters are plotted

### ISSUE THREAD

**Issue by ToniKoe** [ICB-DCM/pyPESTO#595]
the desired parameter indices are related to the full x vector. 
in the handle_inputs() function the vectors ub and lb contain only the bounds of the free parameters. 
That leads to wrong bounds in the plot, I guess.

**Comment by ToniKoe** [comment]
Hey, 

It does throw an error if I want to plot a parameter whose index is larger than the number of free parameters ('IndexError: index 12 is out of bounds for axis 0 with size 12'). But otherwise not.

I attached a minimal example. Parameters with indices 1 & 2 are fixed. Parameters with indices 0 & 3 are within [-0.1 , 0.69] and the other parameters are within [-10,10].

[Example.zip](https://github.com/ICB-DCM/pyPESTO/files/6159453/Example.zip)

**Comment by yannikschaelte** [comment]
I agree that this is a bug, lb_full and ub_full should be used.

**Comment by yannikschaelte** [comment]
@ToniKoe This should be fixed now in the develop branch.

**Comment by ToniKoe** [comment]
@yannikschaelte Thanks!
