### ISSUE TITLE
Basic framework

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#6]
Create the basic structure of the pesto objects, e.g. what does a result contain and look like? What format? What does the problem contain? This can then be used when implementing the specific optimization, sampling etc. routines.

**Comment by dweindl** [comment]
Will provide some comments tomorrow or Friday

**Comment by yannikschaelte** [comment]
kind of done, also optimization possible already, changes to the formats of course still possible if we find better usable or efficient ones.
