### ISSUE TITLE
gradient for fixed parameters

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#60]
I think the gradient for fixed parameters should be set to 0 instead of NaN. They are constant after all.

**Comment by JanHasenauer** [comment]
hm, we discussed this an decided to use NaN. The simple reason is that we do not know. Setting them to zero might be misunderstood. There could obviously still be improvement in this direction.

**Comment by FFroehlich** [comment]
Could you elaborate when a zero value be misleading?
I do not agree that we do not know. The parameter is specified to be fixed/constant. The derivative of the objective function wrt a constant should be 0. We do not know what the derivative wrt to the parameter as a free parameter would be, but if what was of interest, the parameter should not have been specified as fixed parameter.

**Comment by JanHasenauer** [comment]
I would argue that for fixed parameter their is no sensitivity, as there is no change you can evaluate. Accordingly, the sensitivity is not zero bur undefined.

This is obviously to a certain degree a philosophical question.

**Comment by FFroehlich** [comment]
Okay, I see your point.
