### ISSUE TITLE
LS Optimizers report nan as optimal point if objective does not provide fval

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#614]
**Problem description**

If the objective does not internally provide fval (AMICI does that, so likely never noticed), nan is reported as optimal point.

**Possible solution**

The history is updated in https://github.com/ICB-DCM/pyPESTO/blob/develop/pypesto/objective/base.py#L152, based on whatever the model internally provides, in the line after that outputs are reduced to what was requested by the call routine. 

The updating then happens in https://github.com/ICB-DCM/pyPESTO/blob/625c41911fdee2608e736321d9e9050ac90f7ba4/pypesto/optimize/optimizer.py#L142, and by the given logic seems to overwrite everything with nans. Should probably use res2chi2 like used for trace, directly in https://github.com/ICB-DCM/pyPESTO/blob/13c09dd6b19dff8be2ba3b8b13fbf27ac5387e8e/pypesto/objective/history.py#L1069.

**Comment by FFroehlich** [comment]
fixed in https://github.com/ICB-DCM/pyPESTO/pull/628
