### ISSUE TITLE
Result-Object is not complete

### ISSUE THREAD

**Issue by LaraFuhrmann** [ICB-DCM/pyPESTO#625]
Using PyPesto I am fitting an ODE model that I implemented with FiPy. 
Weirdly, the result object (that the function `optimize.minimize` returns) does  not give values for x although the optimization seems to have converged:
```
'id': '0',
  'x': None,
  'fval': inf,
  'grad': array([-1.24053517e-09,  6.13698037e-10]),
  'hess': None,
  'res': None,
  'sres': None,
  'n_fval': 0,
  'n_grad': 0,
  'n_hess': 0,
  'n_res': 36,
  'n_sres': 0,
  'x0': array([2.44899402, 1.34697749]),
  'fval0': None,
  'history': <pypesto.objective.history.CsvHistory at 0x7fadbfb1d400>,
  'exitflag': 1,
  'time': 3.1208178997039795,
  'message': '`gtol` termination condition is satisfied.'}
```
I used the option to save the optimization history, i.e. `history_options = pypesto.HistoryOptions(trace_record=True, storage_file='history.csv')`, to investigate better what is happening. 
When checking the history-file, I found that the optimal value for x was actually derived. 

Can you think of a reason why the optimal value that occures in the history file does not occur in the result-object?  

I attached here [code](https://github.com/ICB-DCM/pyPESTO/files/6292688/fit_fipy_model_example.py.txt) with a small example.

**Comment by yannikschaelte** [comment]
Hi @LaraFuhrmann , the problem is most likely that least squares optimization is used, but the function value is not tracked correctly. This is a known bug of pyPESTO, #614.

**Comment by LaraFuhrmann** [comment]
Hi Yannik, 
thanks for the fast reply.
Indeed, I am using least squares optimization. 
For now I will continue working with the history file then :)

**Comment by LaraFuhrmann** [comment]
Hi @yannikschaelte :) Just wanted to let you know that with version `0.2.6` this problem is solved for me. Meaning that the result object is complete with all fields filled.
