### ISSUE TITLE
Handle missing sub-results in `write_result`

### ISSUE THREAD

**Issue by dilpath** [ICB-DCM/pyPESTO#636]
Running `pypesto.store.save_to_hdf5.write_result(result)` if `result` has no sample sub-result causes an exception. Could specify `sample=False` but then adding additional sub-result objects (e.g. maybe ensembles) to `write_result` may break backwards compatibility in future, as the additional sub-result objects would be "missing" too.

Possible options:
- warn on missing sub-results (possibly in `SamplingResultHDF5Writer`) instead
- try/except in `write_result` for each sub-result type
- change all options in `write_result` to be `False` by default instead

**Comment by PaulJonasJost** [comment]
Also Noticed a problem when loading files with `read_result()` if some directories are non existent within the file.

**Comment by jvanhoefer** [comment]
@dilpath and @PaulJonasJost This is closed with the new release, right? I am wondering a bit why this was not closed automatically... (otherwise please reopen :) )
