### ISSUE TITLE
Make AmiciObjective save simulation results in benchmark collection format

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#68]
This data can e.g. be used as input for visualizing goodness of fit

**Comment by yannikschaelte** [comment]
missing here: the mapping back from a list of rdatas to a measurement_df (probably in the pypesto.objective.PetabImporter)

**Comment by yannikschaelte** [comment]
exists from 07cd7e00383079b0a14fc04aba623ba9b97c2a9a onwards

**Comment by dweindl** [comment]
This seems to be sufficiently addressed. Closing.
