### ISSUE TITLE
Parameter plots y axis

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#70]
When there are many variables, the parameter plot y axis becomes not so fun to read. I would suggest that we simply allow the user to specify in the parameters plot arguments ``par_labels=None|'automatic'``, where when 'automatic' is passed, we just use matplotlib's default axis labeling, and use the result.problem.x_labels only otherwise (or when x_labels=['a','b','c'] is some list).

Or some other implementation.

![image](https://user-images.githubusercontent.com/31767307/48979211-9720f100-f0b7-11e8-96a4-6ec62de705dd.png)

**Comment by FFroehlich** [comment]
would also help to allow customized figure sizes

**Comment by FFroehlich** [comment]
I think this should be adressd in e9999763c1a356ac1954e012dc16c19047d965aa
