### ISSUE TITLE
No output or plot for visualize.parameters(result) in pycharm

### ISSUE THREAD

**Issue by harshitaojha** [ICB-DCM/pyPESTO#700]
I ran the following command in pycharm and got nothing as output.
pypesto.visualize.parameters(result)

where result = optimize.minimize(problem,
                           optimizer=optimizer,
                           n_starts=10)

**Comment by dweindl** [comment]
Hi @harshitaojha, do you see something if you run `import matplotlib.pyplot as plt; plt.show()` after ` pypesto.visualize.parameters(result)`?

**Comment by harshitaojha** [comment]
Yes, it shows the expected plot now. Thanks. Also, is there a way to find out the exact value of these parameters?

**Comment by dweindl** [comment]
> Yes, it shows the expected plot now. Thanks. 

Great

> Also, is there a way to find out the exact value of these parameters?

`optimized_parameters = result.optimize_result.get_for_key('x')`

[This notebook](https://pypesto.readthedocs.io/en/latest/example/rosenbrock.html) gives some further examples of how to work with the result object.

**Comment by harshitaojha** [comment]
Thanks a lot:)
