### ISSUE TITLE
ValueError: tuple.index(x): x not in tuple while running problem = importer.create_problem()

### ISSUE THREAD

**Issue by harshitaojha** [ICB-DCM/pyPESTO#701]
Traceback (most recent call last):
  File "/home/harshita/PycharmProjects/Project_ICL_pyPESTO/pypesto_opti.py", line 23, in <module>
    problem = importer.create_problem()
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/petab/importer.py", line 447, in create_problem
    objective = self.create_objective(**kwargs)
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/petab/importer.py", line 242, in create_objective
    edatas = self.create_edatas(
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/petab/importer.py", line 197, in create_edatas
    return amici.petab_objective.create_edatas(
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/amici/petab_objective.py", line 466, in create_edatas
    edata = create_edata_for_condition(
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/amici/petab_objective.py", line 540, in create_edata_for_condition
    y, sigma_y = _get_measurements_and_sigmas(
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/amici/petab_objective.py", line 638, in _get_measurements_and_sigmas
    observable_ix = observable_ids.index(measurement[OBSERVABLE_ID])
ValueError: tuple.index(x): x not in tuple

Measurement_Table_Petab.tsv
observableId	simulationConditionId	measurement	time	noiseParameters
Fungal_clearance	condition1	0.1		0	0.1
Fungal_clearance	condition1	0.3		1	0.1
Fungal_clearance	condition1	0.4		2	0.1
Fungal_clearance	condition1	0.7		3	0.1
Fungal_clearance	condition1	0.74		4	0.1
Fungal_clearance	condition1	0.4		6	0.1
Fungal_clearance	condition1	0.1		8	0.1

4 odes, and 13 parameters

**Comment by FFroehlich** [comment]
Hey, this looks like it could be due to some errors in the petab problem specification. Specifically, it looks like `Fungal_clearance` might not be a valid observable id (specified in the observable table).

Did you use the linter (https://petab.readthedocs.io/projects/libpetab-python/en/latest/build/_autosummary/petab.lint.html#petab.lint.lint_problem) to check whether for errors in the petab problem?

**Comment by harshitaojha** [comment]
How can I conclude if an observable id is valid?
Some additional info:
Extended .yml file-File_petab.yml
odes:
    - stateId: F
      rightHandSide: beta * F - k_NF * N * F - d_MF * M * F
      initialValue: 1e6
    
    - stateId: C
      rightHandSide: k_C * M * F + k_CD * D - delta_C * C
      initialValue: 0
    
    - stateId: N
      rightHandSide: alpha * Nv * C - k_NF * N * F - delta_N *N
      initialValue: 0
    
    - stateId: D
      rightHandSide: alpha_D_Dv * C - k_ND * N * D - delta_D * D
      initialValue: 0

parameters: 
    - parameterId: alpha
      nominalValue: 0.0017
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: beta 
      nominalValue: 0.28
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_NF 
      nominalValue: 1.2e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: d_MF 
      nominalValue: 0.32e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_C 
      nominalValue: 0.38e-12
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_CD 
      nominalValue: 0.31e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: delta_C 
      nominalValue: 0.066
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: delta_N 
      nominalValue: 0.061
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: alpha_D_Dv
      nominalValue: 0.017e+6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_ND
      nominalValue: 0.0069e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: delta_D
      nominalValue: 0.1
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: Nv
      nominalValue: 1.5e+8
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: M
      nominalValue: 0.3e+6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

observables:
    - observableId: Fungal_clearance
      observableFormula: log10(F)
      observableTransformation: lin
      noiseFormula: noiseParameter1_Fungal_clearance
      noiseDistribution: normal

conditions:
    - conditionId: condition1

**Comment by harshitaojha** [comment]
odes:
    - stateId: F
      rightHandSide: beta * F - k_NF * N * F - d_MF * M * F
      initialValue: 1e6
    
    - stateId: C
      rightHandSide: k_C * M * F + k_CD * D - delta_C * C
      initialValue: 0
    
    - stateId: N
      rightHandSide: alpha * Nv * C - k_NF * N * F - delta_N *N
      initialValue: 0
    
    - stateId: D
      rightHandSide: alpha_D_Dv * C - k_ND * N * D - delta_D * D
      initialValue: 0

parameters: 
    - parameterId: alpha
      nominalValue: 0.0017
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: beta 
      nominalValue: 0.28
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_NF 
      nominalValue: 1.2e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: d_MF 
      nominalValue: 0.32e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_C 
      nominalValue: 0.38e-12
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_CD 
      nominalValue: 0.31e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: delta_C 
      nominalValue: 0.066
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: delta_N 
      nominalValue: 0.061
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: alpha_D_Dv
      nominalValue: 0.017e+6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: k_ND
      nominalValue: 0.0069e-6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: delta_D
      nominalValue: 0.1
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: Nv
      nominalValue: 1.5e+8
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

    - parameterId: M
      nominalValue: 0.3e+6
      parameterScale: log10
      lowerBound: 0.01
      upperBound: 100
      estimate: 1

observables:
    - observableId: Fungal_clearance
      observableFormula: log10(F)
      observableTransformation: lin
      noiseFormula: noiseParameter1_Fungal_clearance
      noiseDistribution: normal

conditions:
    - conditionId: condition1

**Comment by harshitaojha** [comment]
> Did you use the linter (https://petab.readthedocs.io/projects/libpetab-python/en/latest/build/_autosummary/petab.lint.html#petab.lint.lint_problem) to check whether for errors in the petab problem?

No, haven't checked it yet as I am unable to create the problem(problem=importer.create_problem()) which acts as input in this.

**Comment by dweindl** [comment]
> > Did you use the linter (https://petab.readthedocs.io/projects/libpetab-python/en/latest/build/_autosummary/petab.lint.html#petab.lint.lint_problem) to check whether for errors in the petab problem?
> 
> No, haven't checked it yet as I am unable to create the problem(problem=importer.create_problem()) which acts as input in this.

Note the difference between `petab.Problem` and `pypesto.Problem`. The former is what you will need for validation.

```
import petab
# ...
petab_problem = petab.Problem.from_yaml(path_to_petab_yaml_file)
petab.lint_problem(petab_problem)
pypesto_petab_importer = pypesto.petab.PetabImporter(petab_problem)
pypesto_problem = pypesto_petab_importer.create_problem()
# ... 
```

**Comment by harshitaojha** [comment]
Getting this error:

Traceback (most recent call last):
  File "/home/harshita/PycharmProjects/Project_ICL_pyPESTO/val_petab.py", line 7, in <module>
    petab.lint_problem(petab_problem)
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/petab/lint.py", line 736, in lint_problem
    check_measurement_df(problem.measurement_df, problem.observable_df)
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/petab/lint.py", line 130, in check_measurement_df
    raise ValueError(f"Observables {observables_undefined} used in "
ValueError: Observables {'condition1'} used in measurement table but not defined in observables table.

**Comment by yannikschaelte** [comment]
The error message in this case is rather informative: You seem to use an observable "condition1" in the measurement table (which however rather sounds like a condition id, maybe something is mixed up in your measurement file?).

**Comment by harshitaojha** [comment]
"condition1" in measurement table lies under "simulationConditionId" label as we can see below.

> Measurement_Table_Petab.tsv
> observableId simulationConditionId measurement time noiseParameters
> Fungal_clearance condition1 0.1 0 0.1
> Fungal_clearance condition1 0.3 1 0.1
> Fungal_clearance condition1 0.4 2 0.1
> Fungal_clearance condition1 0.7 3 0.1
> Fungal_clearance condition1 0.74 4 0.1
> Fungal_clearance condition1 0.4 6 0.1
> Fungal_clearance condition1 0.1 8 0.1

(I tried to keep it very simple by changing the necessary odes and conditions in Lotka Volterra)

**Comment by yannikschaelte** [comment]
Something must be wrong there then. Can you post the files?

**Comment by harshitaojha** [comment]
> Something must be wrong there then. Can you post the files?

I have shared the necessary files

**Comment by dweindl** [comment]
>  File "[...]/site-packages/amici/petab_objective.py", line 638, in _get_measurements_and_sigmas
> observable_ix = observable_ids.index(measurement[OBSERVABLE_ID])
> ValueError: tuple.index(x): x not in tuple

Based on other experience, I would say that this occurs if an AMICI model is imported and then another (or same) model is imported with the same name in the same Python session. The former one is not properly unloaded. To my knowledge there is no way to handle that in a clean way. Therefore, models should be imported with different names or in a new Python session.

Closing.
