### ISSUE TITLE
To use or not to use typing.Literal

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#706]
**Bug description**
Since recently we use `Literal` in some type hints in the objective base class. I.e.

https://github.com/ICB-DCM/pyPESTO/blob/3e0cc23075f35ca07850afda752bd0891a6654b9/pypesto/objective/base.py#L6

Since `Literal` is only available for python 3.8 onwards, we would loose python 3.6 & 3.7 support (completely. One can't even import `pypesto` any more...)

**Possible solution:**

1) Get rid of the type hint. Even though it is wise to always use a current python version, we do not want to scare off users for the sake of a type hint.

2) Leave the type hint, delete python 3.6/7 support e.g. in the `setup.cfg`
https://github.com/ICB-DCM/pyPESTO/blob/72488fbb3eaa91dd163f88bac71a1a165a0da70f/setup.cfg#L37

Currently I am in favor of solution 1 (since we do not even use the `Literal` in the way I would guess it is intended to be used for, even though it could be useful at many places). Any opinions?

@yannikschaelte @stephanmg @dweindl

**Comment by stephanmg** [comment]
I agree with option 1 @jvanhoefer.

**Comment by dweindl** [comment]
For AMICI we decided to support the two most recent stable minor versions of Python. I think something similar would make sense for pypesto. It's easy enough to install a custom python version on most system, so I think we don't need to support a particularly wide range of versions. I would certainly drop Python 3.6 support (pandas already did so), which will reach its EOL end of this year.

I would rather go for option 2. Although I agree that the benefit of using `Literal` alone is probably not the most pressing reason to drop Python3.7 support. But more new features will come and it makes sense to have some Python support policy in place. All officially supported Python versions should then be tested on GHA to recognize these issues early on.

**Comment by stephanmg** [comment]
@dweindl: I see, Python 3.6 reaches EOL on 23 Dec 2021. In that case I would shift towards option 2 as well.

**Comment by dweindl** [comment]
P.S.: with https://github.com/ICB-DCM/pyPESTO/blob/72488fbb3eaa91dd163f88bac71a1a165a0da70f/setup.cfg#L52 Python 3.6 support is effectively already a thing of the past.
