### ISSUE TITLE
objective.check_grad uses wrong parameter names

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#712]
`objective.check_grad` uses objective `x_names`, which includes fixed and free parameter names, while the provided x, and thus the argument x_indices is subsetted to free parameters.

Not sure what a good way to fix this would be, I guess we want to change x_names when setting the pre/postprocessor?

**Comment by yannikschaelte** [comment]
currently, x_names is just a List[str]. I guess it would make sense to implement it similarly to the problem, via attributes with stored full representation, and free_ids (via preprocessor) governing which to output.
