### ISSUE TITLE
pypesto.petab.PetabImporter.rdatas_to_simulation_df does not rename column 'measurement'

### ISSUE THREAD

**Issue by C-Peiter** [ICB-DCM/pyPESTO#719]
I noticed that the column names in the created data frame are not renamed. I tried to reproduce this and think that my problem is simply the following:
In the source code the simulationDf is created with `importer.rdatas_to_measurement_df(rdatas, model).rename({petab.MEASUREMENT:petab.SIMULATION})`. However, this did not rename column `petab.MEASUREMENT`. 
Inserting the keyword `columns` worked for me: `importer.rdatas_to_measurement_df(rdatas, model).rename(columns={petab.MEASUREMENT:petab.SIMULATION})`

It might only be caused by different pandas versions (I have v1.2.4 installed), but I don't know that.

**Comment by yannikschaelte** [comment]
Hi @C-Peiter , thanks for reporting. I'm not sure if I completely understood: Are you saying that the output dataframe has column name "measurement", but should have "simulation"?

**Comment by C-Peiter** [comment]
Yes, exactly.

**Comment by yannikschaelte** [comment]
Ok, got it then :) Seems indeed like pandas changed their API there slightly. Do you want to make a pull request to develop branch with that change, or shall we?

**Comment by C-Peiter** [comment]
It's done :-)
