### ISSUE TITLE
AmiciObjective: Return full simulation results

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#72]
Enable Amici to return aside nllh and snllh also the full rdata(s), i.e. the simulation results. This is useful for verifications and plotting.
How to do it: E.g. We could finally switch to having our objectives return a dict instead of a tuple, and then simply return the rdatas as an additional entry. This should not take more time, since the results will be stored minimally longer I guess.
Alternative: Create an additional function which works like _call_amici (and can be used by it).

**Comment by dweindl** [comment]
Agreed. Memory-wise, this is will only be a problem if we are dealing with large numbers of simulations of large models. I think we can ignore that for now.

Note that `amici.runAmiciSimulations()` mostly does what you are describing. The difference is that `AmiciObjective` allows to use the same preequilibration results for all condition, `amici.runAmiciSimulations()` will run preequilibration for each individual condition.

Using the same preequilibration results for all condition, should be implemented in AMICI, ideally in the C++ part. This will be more reusable and clean up `AmiciObjective`.

**Comment by yannikschaelte** [comment]
exists from 07cd7e00383079b0a14fc04aba623ba9b97c2a9a onwards. Note: the preequilibration efficiency has been removed from AmiciObjective for the moment, because we also need to take into account that there might be different parameter mappings, even if the preeq conditions coincide. This should be easy to implement, see the TODO in AmiciObjective.run_preequilibration().

**Comment by paulstapor** [comment]
Already closed by @yannikschaelte in PR #83
