### ISSUE TITLE
Help: How to hide AMICI/CVODEs warnings in python? 

### ISSUE THREAD

**Issue by willov** [ICB-DCM/pyPESTO#724]
I have been trying to get into using pyPESTO/AMICI for parameter estimation. 
However, it is hard to keep track of the progress when all these warnings gets printed. 
Is there any way to hide these warnings but still get the progress of the optimization solver? 
[See for example here in the Boehm example (block [17])](https://pypesto.readthedocs.io/en/latest/example/amici_import.html#Run-optimization-using-pyPESTO). 
Essentially I want to keep the bar but block the `[Warning] AMICI:CVODES:CVode:ERR_FAILURE: AMICI ERROR: in module CVODES in function CVode : At t = 27.1575 and h = 3.02895e-06, the error test failed repeatedly or with |h| = hmin.` warnings. 

Thanks!

**Comment by dweindl** [comment]
Hi @willov, there is currently no straightforward way to achieve that. In case you are running AMICI from within a Jupyter notebook, the following might work (untested):

```
import amici
from contextlib import nullcontext
amici._capture_cstdout = nullcontext
```

**Comment by willov** [comment]
Thanks! I am currently running my script through VS code's interactive mode (ipython based) and unfortunately the suggestion does not work there, assuming i implemented it correctly. 
It's comforting to hear that I have not missed some obvious solution though. I guess I will continue using my current workaround by capturing the stderr output. I'm attaching the code below, just in case anyone else stumbles upon this. 

```
from contextlib import contextmanager, redirect_stderr
from os import devnull

@contextmanager
def silent_errors():
    with open(devnull,'w') as fnull:
        with redirect_stderr(fnull) as err:
            yield err

with silent_errors():
    result = optimize.minimize(...)
```
