### ISSUE TITLE
Use information as default from problem in `ensemble.from_sample`

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#727]
When calling `ensemble.from_sample(result=result)`, we could take `x_names`, and parameter bounds as default value for the ensemble, in case no other values for these arguments are defined...

@PaulJonasJost what do you think about that?

https://github.com/ICB-DCM/pyPESTO/blob/fb2be819b41411dc1686d8429ce5efa6c535b70b/pypesto/ensemble/ensemble.py#L343

**Comment by PaulJonasJost** [comment]
yes, sounds very reasonable to me.
