### ISSUE TITLE
Parameter bounds cannot be passed as a list to visualize.parameters_lowlevel

### ISSUE THREAD

**Issue by C-Peiter** [ICB-DCM/pyPESTO#728]
Hey, I think I found an issue here:
https://github.com/ICB-DCM/pyPESTO/blob/fb2be819b41411dc1686d8429ce5efa6c535b70b/pypesto/visualize/parameters.py#L290-L295

I passed `lb` and `ub` to `pypesto.visualize.parameters_lowlevel` as a `list` but got an Attribute error ```AttributeError: 'list' object has no attribute 'flatten'```.
According to the documentation, one should be able to use a list, correct?
https://github.com/ICB-DCM/pyPESTO/blob/fb2be819b41411dc1686d8429ce5efa6c535b70b/pypesto/visualize/parameters.py#L194-L198

I am using Python v3.8.11 with pyPESTO v0.2.7.

**Comment by yannikschaelte** [comment]
agreed. the documentation suggests both ndarray and list are fine. as the implementation seems to use ndarray functions like flatten, the easiest thing may be to internally transform lb, ub to ndarray at the beginning. do you want to do that?

**Comment by C-Peiter** [comment]
Sure, I can do that some time this week.
