### ISSUE TITLE
Drop python 3.7 support

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#737]
As 3.10 is up and coming and 3.8 has long been stable, we could drop support of 3.7. Anyone against?

Currently, we would need to drop it due to use of Literal type indicators (which would obviously not be a necessity though).

**Comment by yannikschaelte** [comment]
update: removed literal for the moment, as major platforms still rely on 3.7, so waiting a little longer.

**Comment by dweindl** [comment]
Note that numpy dropped Python 3.7 support in [1.22.0](https://numpy.org/devdocs/release/1.22.0-notes.html). Would make sense to follow...

**Comment by yannikschaelte** [comment]
following :woman_dancing:

**Comment by yannikschaelte** [comment]
dropped it
