### ISSUE TITLE
Parallelization of MCMC sampling

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#763]
**Feature description**
Maybe I missed something but optimization and ensemble creation can be easily parallelized, while this is missing for the MCMC sampling. Especially for the adaptive parallel tempering sampler this would be interesting for me (sample.AdaptiveParallelTemperingSampler). Is there currently a way to do this parallelized?

**Motivation/Application**
The MCMC sampling is currently the bottleneck for the runtime of my workflow in pypesto as optimization and ensemble creation can be parallelized, while sampling cannot. Parallelized sampling would speed up my workflow a lot.

**Comment by JanHasenauer** [comment]
Parallelisation of parallel tempering would indeed by nice to have and should not be too challenging. Unfortunately, we did so far not have the resources to implement it.

There are some very nice approach which even how for asynchron sampling between the chain, which enhances par efficiency further.

**Comment by yannikschaelte** [comment]
closing in favor of #352
