### ISSUE TITLE
Disable progress bar in most tests

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#791]
Output tracking does not gracefully deal with line rollback apparently, and adds another line upon each update. To avoid resulting overly long logfiles, it may be preferable to disable progress bars per default / in tests.

**Comment by dilpath** [comment]
One option is the following (done before any other imports) (https://github.com/tqdm/tqdm/issues/619#issuecomment-425234504).
```python
import tqdm
def nop(it, *a, **k):
    return it
tqdm.tqdm = nop
```

There are other options from that thread, including use of an environment variable. This would be convenient for pyPESTO users too, not just test logs. Examples:
- https://github.com/miyakogi/pyppeteer/pull/153
- https://github.com/tqdm/tqdm/pull/950
