### ISSUE TITLE
parameter list in the data format (benchmark models)

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/pyPESTO#80]
The new common data format will need a full list of all parameters (with bounds etc.) which should be optimized. Therefore, some fill-in tool for models, which specify parameters elsewhere than in the SBML file (e.g., as conditions), will be needed in order to generate the parameter table.

**Comment by yannikschaelte** [comment]
I think that all models need to specify a parameters tsv file (e.g. https://github.com/LoosC/Benchmark-Models/blob/hackathon/hackathon_contributions_new_data_format/Boehm_JProteomeRes2014/parameters_Boehm_JProteomeRes2014.tsv) which will contain precisely the optimization parameters (and boundaries, scale, etc.). These parameters can theoretically also be computed from the parameters in the sbml model, the measurements file, and the conditions files (but then no boundaries, scales, etc., maybe defaults?), but I would always take the parameters file as basis.

The mapping from optimization to simulation parameters has been started already in https://github.com/ICB-DCM/PEtab, if I understand correctly.

**Comment by dweindl** [comment]
This should be addressed in https://github.com/ICB-DCM/PEtab/commit/61e2ad644866c405bdc12eaacc84e857906cde44 . If not please open a new issue at https://github.com/ICB-DCM/PEtab/issues/new.
