### ISSUE TITLE
`__getattr__`  as replacement for `get_for_key` and `as_list` in optimize result

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/pyPESTO#800]
**Feature description**
Instead of `result.optimize_result.get_for_key('fval')` use `result.optimize_result.['fval']`

Instead of `result.optimize_result.as_list()[0]` use `result.optimize_result[0]`

**Motivation/Application**
Nicer syntax, everyone likes that...

**Comment by yannikschaelte** [comment]
:+1: only thing to be careful with is how much we want to break API. If too much of a break, we could add deprecation warnings to e.g. get_for_key thingies, that should no longer be used.

**Comment by yannikschaelte** [comment]
We should also consider more consistently marking attributes and functions that are not meant for the outside world as private (`_var`).

**Comment by jvanhoefer** [comment]
And I should also change all the places, where the depreciated functions are used at the moment (including notebooks...)

**Comment by jvanhoefer** [comment]
So the PR will grow, sorry for requesting the reviews too early...
