### ISSUE TITLE
CI/notebooks fail

### ISSUE THREAD

**Issue by plakrisenko** [ICB-DCM/pyPESTO#817]
Lately, pull requests don't pass CI/notebooks tests.
`
AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'
AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'
`
This is what I've found about the issue 
https://stackoverflow.com/questions/70839312/module-numpy-distutils-config-has-no-attribute-blas-opt-info
Fixing numpy version did help (#808). 
Should we fix numpy version for now?

**Comment by dweindl** [comment]
Is there already a corresponding issue at theano? If not, I'd suggest reporting there. We are already using the latest version of it, right?

**Comment by plakrisenko** [comment]
https://github.com/numpy/numpy/issues/21079

**Comment by dilpath** [comment]
Perhaps Theano should be removed from pyPESTO altogether. It's no longer developed [1], and there is an updated fork named Aesara [2].

If NumPy is fixed to an earlier version for Theano, the `optimize` CI job fails [3]. If the NumPy version is increased, then the `optimize` CI job passes but there are errors related to Theano [4].

[1] https://github.com/Theano/Theano
[2] https://github.com/aesara-devs/aesara
[3] https://github.com/ICB-DCM/pyPESTO/runs/5717198486?check_suite_focus=true#step%3A6%3A31=
[4] https://github.com/ICB-DCM/pyPESTO/runs/5718692120?check_suite_focus=true#step%3A6%3A405=

**Comment by yannikschaelte** [comment]
@PaulJonasJost was working on replacing theano by aesara afair

**Comment by FFroehlich** [comment]
I thought I already implemented that https://github.com/ICB-DCM/pyPESTO/blob/main/pypesto/objective/aesara.py ?

**Comment by yannikschaelte** [comment]
yes basically just replace every reference in pymc3 to theano with that.

**Comment by PaulJonasJost** [comment]
> yes basically just replace every reference in pymc3 to theano with that.

Which somehow does not do the whole trick :D
