### ISSUE TITLE
Representation of replicate data in the likelihood function

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#823]
I have a question on the implementation of the likelihood function:

If I have N replicates at T different time points how would my likelihood function look like:
![grafik](https://user-images.githubusercontent.com/66028655/158429964-a7e792a1-863a-4acd-804c-794e895b2098.png)

with s being the solution of the ODE and m_j the measurement of the j-th replicate and assuming normal distributed noise.
The first likelihood function would thereby include each replicate separately, while the second would only take into account the mean of all samples.

I did not now where I should search for this so thanks in advance for any answer.

**Comment by yannikschaelte** [comment]
Hi @shoepfl , sorry for the delay. I would say that you want likelihood (60), in which case sigma would be interpreted as the actual observational noise level.

**Comment by shoepfl** [comment]
Thanks @yannikschaelte for the reply - I would also say likelihood 60 is to be preferred, however this is a part of the implementation of the PEtab parameter estimation in the toolbox. Therefore, I wanted to make if this is also the actual implementation. To not just to assume that the program does what I want it to do, but that it was actually programmed that way.

**Comment by yannikschaelte** [comment]
Ah sorry then I misunderstood your question. Yes, (60) is exactly what PEtab and AMICI implement.

**Comment by shoepfl** [comment]
Okay thanks a lot!
