### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#85]
Can we please have releases that tag version that were uploaded to pypi? Without this its pretty difficult to identify which commit `pip install pypesto` will yield.

**Comment by yannikschaelte** [comment]
true. the latest version on the master can be newer than that on pypi, if the version was not updated in the last pull request (e.g. bc it was just a minor thing updated, not qualifying for a new version yet). what exactly do you mean by "releases that tag versions"? can this be done automatically?

**Comment by dweindl** [comment]
Agreed with @FFroehlich . 

Whenever a new release is uploaded to pypi, there should also be a github release created. This will create a [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) *and* save the release on zenodo.

**Comment by dweindl** [comment]
It is true that with the current system there will be multiple versions with the same version number in master. This is not great, but we can live with it. At least one can find the exact commit of the release back from the tag.

To avoid multiple versions with the same version number in master, we change our release process:
All feature pull merge requests go to `develop`, which is the main line. From there we create release branches which get new version numbers, and only those are merged into `master`, and nothing else. As nicely illustrated [here](https://nvie.com/posts/a-successful-git-branching-model/). This is what we are currently aiming for in https://github.com/ICB-DCM/AMICI .

**Comment by yannikschaelte** [comment]
Sounds good. I agree. Should also be documented in https://pypesto.readthedocs.io/en/latest/deploy.html.

**Comment by FFroehlich** [comment]
I would rather set up an automatic deploy script. Should be really straightforward as we dont have any cpp/swig dependencies https://docs.travis-ci.com/user/deployment/pypi/

**Comment by dweindl** [comment]
Will look into 
- [ ] Updating contrib guide for github releases
- [ ] Auto-deploying version-tagged commits

**Comment by FFroehlich** [comment]
> Auto-deploying version-tagged commits

is already done.

**Comment by yannikschaelte** [comment]
The develop branch is now also monitored on readthedocs (https://pypesto.readthedocs.io/en/develop/), so that merges to develop will automatically trigger doc builds. and we will notice doc build failures and can check before releasing.
