### ISSUE TITLE
fval is not saved in hdf5 file in multistart optimization

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#860]
Hello,

when i use pypesto to estimate the parameters of my PEtab file and save my results to a hdf5 file, the optimization result only contains 'x0' and 'x', not 'fval'. Therefore, it is impossible to reconstruct the best fitting result of a multistart optimization afterwards which makes it useless for me.

Here is my code:

`importer = pypesto.petab.PetabImporter.from_yaml(yaml_file)`

`problem = importer.create_problem()`

`optimizer = optimize.ScipyDifferentialEvolutionOptimizer(options = {'strategy':'best1bin', 'maxiter':8000 ,'mutation':(0.2, 1), 
'recombination':0.7, 'popsize':70,  'init':'latinhypercube', 'polish':True, 'workers' : 4})`

`n_starts = 20`

`result = optimize.minimize(problem, optimizer=optimizer, n_starts=n_starts)`

`store.save_to_hdf5.write_result(result, Path + M + '_Pypesto_Parameters.hdf5', overwrite= True)`

file['optimization']['results']['0'].keys() only retuns ['x0', 'x'].

I can save the history information in a dataframe via

`df = result.optimize_result.as_dataframe( ['fval', 'n_fval', 'n_grad', 'n_hess', 'n_res', 'n_sres', 'time'])`
    
`df.to_csv(Path + 'Pypesto_History_' + solver + '_' + M +'.tsv', sep="\t")`

however, i think it should be also stored in the hdf5 file to have all information comprehensive.

**Comment by dilpath** [comment]
Hi @shoepfl, did you try the following?
```
file['optimization']['results']['0'].attrs['fval']
```

**Comment by shoepfl** [comment]
Indeed its an attribute - thanks @dilpath! 
I could have also checked that before sorry. I do not know if this is only confusing to me but i think it would be good to specify this also in the pyPESTO documentation.

For the sampling results the attributes are listed explicitly but for the results per optimization its not listed under attributes as far as I understand:
https://pypesto.readthedocs.io/en/latest/storage_format.html
