### ISSUE TITLE
Problems with startpoint method

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#870]
I have a problem with optimize.minimize:

`optimizer = optimize.ScipyDifferentialEvolutionOptimizer(options = {'strategy':'best1bin', 'maxiter':8000 ,'mutation':(0.5, 1), 'recombination':0.9, 'popsize':100,  'init':'latinhypercube', 'polish':True, 'workers' : 8 })`
`n_starts = 1`
`result = optimize.minimize(petab_problem,  optimizer=optimizer, n_starts=n_starts)`

Results in : AttributeError: 'Problem' object has no attribute 'x_guesses'

I thought it may be that i do not need startpoints as they are created in scypy but also `startpoint_method = False` in optimize.minimize rises an error: AttributeError: 'Problem' object has no attribute 'dim'

This problem probably occoured through updating my dependencies as this code worked before.
Can you tell me what changed and how to fix this?

Thanks! and Best,
Sebastian

**Comment by dilpath** [comment]
I guess that `petab_problem` should be switched with a `pypesto.Problem` object in your `optimize.minimize` call.

**Comment by shoepfl** [comment]
Ah thank you very much for the fast answer @dilpath  !

Of course that was my mistake - sometimes i get confused with the petab and pypesto problems.
