### ISSUE TITLE
Amici objective seems to give incorrect gradients

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/pyPESTO#88]
When running the notebooks in doc/example which use the AmiciObjective, optimization stops after the first iteration, saying that "CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL". Since this does not happen for the Rosenbrock notebook, I guess that the gradient of the Amici objective is incorrect.
Can someone have a look at this?

**Comment by yannikschaelte** [comment]
is it in the master branch / from pypi / some feature branch? and what is your scipy version?

**Comment by paulstapor** [comment]
It's in the master, my scipy version is 1.2.0

**Comment by paulstapor** [comment]
hold on, maybe I have an old pypesto version...

**Comment by paulstapor** [comment]
Well, updated all my necessary python packages...

now get an error upon import pypesto:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/amici/amici.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in module_from_spec(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in create_module(self, spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/amici/__init__.py in <module>()
     33 try:
---> 34     from . import amici
     35     from .amici import *

~/.local/lib/python3.6/site-packages/amici/amici.py in <module>()
     16             return importlib.import_module('_amici')
---> 17     _amici = swig_import_helper()
     18     del swig_import_helper

~/.local/lib/python3.6/site-packages/amici/amici.py in swig_import_helper()
     15         except ImportError:
---> 16             return importlib.import_module('_amici')
     17     _amici = swig_import_helper()

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

ModuleNotFoundError: No module named '_amici'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7c646330f756> in <module>()
      1 import amici
----> 2 import amici.plotting
      3 import pypesto

~/.local/lib/python3.6/site-packages/amici/plotting.py in <module>()
      1 """@package amici.plotting Plotting related functions"""
      2 
----> 3 import matplotlib.pyplot as plt
      4 
      5 def plotStateTrajectories(rdata, state_indices=None, ax = None):

~/.local/lib/python3.6/site-packages/matplotlib/__init__.py in <module>()
    139 # cbook must import matplotlib only within function
    140 # definitions, so it is safe to import from it here.
--> 141 from . import cbook, rcsetup
    142 from matplotlib.cbook import (
    143     MatplotlibDeprecationWarning, dedent, get_label, sanitize_sequence)

~/.local/lib/python3.6/site-packages/matplotlib/cbook/__init__.py in <module>()
     31 from weakref import WeakMethod
     32 
---> 33 import numpy as np
     34 
     35 import matplotlib

~/.local/lib/python3.6/site-packages/numpy/__init__.py in <module>()
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~/.local/lib/python3.6/site-packages/numpy/core/__init__.py in <module>()
     57 from . import numerictypes as nt
     58 multiarray.set_typeDict(nt.sctypeDict)
---> 59 from . import numeric
     60 from .numeric import *
     61 from . import fromnumeric

~/.local/lib/python3.6/site-packages/numpy/core/numeric.py in <module>()
   3091 from .umath import *
   3092 from .numerictypes import *
-> 3093 from . import fromnumeric
   3094 from .fromnumeric import *
   3095 from . import arrayprint

~/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py in <module>()
     15 from . import numerictypes as nt
     16 from .numeric import asarray, array, asanyarray, concatenate
---> 17 from . import _methods
     18 
     19 _dt_ = nt.sctype2char

~/.local/lib/python3.6/site-packages/numpy/core/_methods.py in <module>()
    156     )
    157 
--> 158 _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
    159 
    160 def _array_function(self, func, types, args, kwargs):

AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

**Comment by paulstapor** [comment]
Was indeed due to deprecated amici version. Renewing led to incompatibilities of numpy (version 1.16.0 seemed to be problematic, whereas 1.15.2 was not). Upgrading everything to python 3.7 and all related packages solved the problem.

**Comment by yannikschaelte** [comment]
officially we still want to support python 3.6, so maybe let's remember that and check back before the next merge.

**Comment by paulstapor** [comment]
I think python 3.7 was not really necessary. However, it was the easiest solution to update, since `import numpy` gave an error...

**Comment by dweindl** [comment]
But maybe a good idea to already run tests with python 3.7 as well

**Comment by yannikschaelte** [comment]
don't know if that is available on travis already ...
