### ISSUE TITLE
Travis doesn't understand xvfb for plotting any more

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#90]
During automated testing, an error of 127 (indicating the command cannot be found, see https://stackoverflow.com/questions/1763156/127-return-code-from) is thrown in
https://travis-ci.com/ICB-DCM/pyPESTO/builds/97497429?utm_medium=notification&utm_source=email.

That line https://github.com/ICB-DCM/pyPESTO/blob/master/.travis.yml#L34 had been added to enable testing plotting routines.

**Comment by paulstapor** [comment]
Fixed by changing the call of xvfb
