### ISSUE TITLE
Remove chi2, schi2 from history

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#901]
Unlike the result objects, the history/trace also knows chi2 and schi2 entries. As these are 1-1 to fval, grad, and either both or none are stored by default, this appears superfluous and a waste of storage. What are reasons against removing? If `history.get_{chi2|schi2}_trace` is needed, one could add redirecting properties I guess.

**Comment by FFroehlich** [comment]
grad (and potentially also fval) won't be computed when using least squares optimizers, so they can't be stored in history.

**Comment by FFroehlich** [comment]
after looking at #902, I realized there already are multiple conversion functions, so I would agree that these fields are no longer necessary.

**Comment by dweindl** [comment]
> these are 1-1 to fval, grad,

Ideally :sweat_smile: 

> waste of storage

At least for HDF5, when enabling compression, this shouldn't be a big deal

**Comment by yannikschaelte** [comment]
> grad (and potentially also fval) won't be computed when using least squares optimizers, so they can't be stored in history.

In https://github.com/ICB-DCM/pyPESTO/blob/e3099c0e0564e5b64e8395a2bb6568cb53a29904/pypesto/history/base.py#L339,

fval, grad, hess etc are computed from res, sres if applicable. This function is always called before storing stuff to history, so these values should then be available in history.
