### ISSUE TITLE
AMICI expects rdata not dict

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#924]
https://github.com/ICB-DCM/pyPESTO/blob/488eca74bf5b6abe0a0c60de0215997c6973c0a8/pypesto/petab/importer.py#L668
is not compatible with recently changed 

https://github.com/AMICI-dev/AMICI/blob/9c3602935973e3f33347aa116fc2b8639c8d000b/python/amici/petab_objective.py#L765

@dweindl @FFroehlich probably a simple return data view should be created here. What would be the correct AMICI conversion functions?

**Comment by FFroehlich** [comment]
I don't think there are any simple conversion functions as a `ReturnDataView` is a relatively complex class with caching an attributes that are C pointers. Wouldn't it be sufficient to create a simple dataclass (instead of the dict) that mocks `ReturnDataView` attributes?

**Comment by yannikschaelte** [comment]
> I don't think there are any simple conversion functions as a `ReturnDataView` is a relatively complex class with caching ane attributes that are C pointers. Wouldn't it be sufficient to create a simple dataclass (instead of the dict) that mocks `ReturnDataView` attributes?

Yes that is essentially what was done before. I will do a simple AttributeDict then. Works but won't be very nice, as the expected data type is ignored.

**Comment by FFroehlich** [comment]
> > I don't think there are any simple conversion functions as a `ReturnDataView` is a relatively complex class with caching ane attributes that are C pointers. Wouldn't it be sufficient to create a simple dataclass (instead of the dict) that mocks `ReturnDataView` attributes?
> 
> Yes that is essentially what was done before. I will do a simple AttributeDict then. Works but won't be very nice, as the expected data type is ignored.

Agreed. But it also shouldn't be too difficult though to simply insert those columns into a copy of the measurement_df, right?

**Comment by yannikschaelte** [comment]
> > > I don't think there are any simple conversion functions as a `ReturnDataView` is a relatively complex class with caching ane attributes that are C pointers. Wouldn't it be sufficient to create a simple dataclass (instead of the dict) that mocks `ReturnDataView` attributes?
> > 
> > 
> > Yes that is essentially what was done before. I will do a simple AttributeDict then. Works but won't be very nice, as the expected data type is ignored.
> 
> Agreed. But it also shouldn't be too difficult though to simply insert those columns into a copy of the measurement_df, right?

Should be possible, but implementing that functionality here could lead to issues, as the logic has been moved to AMICI. Long-term, either pyPESTO should keep/construct actual AMICI RData, or AMICI's function be made more generic. But fine for the moment I think.

**Comment by FFroehlich** [comment]
Yes, will have to add such a functionality for other purposes anyways.
