### ISSUE TITLE
(C)ESS optimizer: Create history for global best

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/pyPESTO#974]
So far, the ESS optimizers don't record any trace/history. It would be good to create/return a trace for the best parameters/fval in each iteration. This would be helpful for performance comparison and would leave some useful result in case optimization is canceled prematurely.

**Comment by PaulJonasJost** [comment]
Just a quick question: Do you want an ESS history for the optimizer itself? Or does the pypesto history not track this correctly?

**Comment by dweindl** [comment]
> Just a quick question: Do you want an ESS history for the optimizer itself? Or does the pypesto history not track this correctly?

It should produce a regular pypesto History. The problem is, that it needs to be assembled in a different way, as there are no distinct local optimizations to be tracked. Instead we need to track the global best value, or the best value for each worker.

**Comment by dweindl** [comment]
-> https://github.com/ICB-DCM/pyPESTO/releases/tag/v0.4.2
