### ISSUE TITLE
fval traces plot in MCMC Sampling

### ISSUE THREAD

**Issue by Zarifehhdr** [ICB-DCM/pyPESTO#978]
Hello, pyPESTO team. 
I'm using PEtab and pyPESTO for parameter estimation and MCMC sampling of a model containing 50 unknown parameters and in case of optimization I'm getting pretty good results. But, after MCMC sampling using parallel tempering, I got weird results specially in fval trace plots using "pypesto.visualize.sampling_fval_trace" function. 
As you mentioned in the documentation, it is supposed to "Plot log-posterior (=function value) over iterations", but I'm wondering if this function visualize the log-posterior or something else. 
Because in my model the "pypesto.visualize.sampling_fval_trace" depicts weird plots. It really doesn't make sense for the sign to change in the fval as you can see here.
![fvaltrace___1](https://user-images.githubusercontent.com/88561761/205080462-7ed00752-8894-4d51-9a51-2abe6ac8b10a.png)

Would you please help me find out what this function exactly depicts?

**Comment by dilpath** [comment]
Hi Zarifeh, the function should plot fvals. Could you confirm that the plot is not fvals? For example, you could look at the (negative) trace
```python
-pypesto_result.sample_result.trace_neglogpost
```

If these values do match the plot, then the objective function is producing unexpected values. Out of interest, why can't the log-posterior change sign in your setup? In general, a change in sign is possible.

**Comment by yannikschaelte** [comment]
Hi @ZarifehHeidariRarani , please further note that in this plot, the "log-posterior" is shown ("high is good"), while your function value that you optimize is the "negative log-likelihood" ("low is good"). This is intentional, as when talking about sampling, one usually considers the (non-inverted) log-likelihood, while in optimization one usually solves a minimization problem, and thus the negative log-likelihood.

**Comment by yannikschaelte** [comment]
Hi, (1) it plots the positive log-likelihood (as the y-axis label indicates), not the negative. The posterior density values are not constrained to [0,1] but rather [0, inf], as it's a density function (only discrete probabilities must sum to 1). Thus, the log-posterior can take any values in [-inf, inf].

**Comment by ZarifehHeidariRarani** [comment]
@yannikschaelte Thank you. And as a side question, is there any available method in pyPESTO for verifying MCMC convergence?

**Comment by yannikschaelte** [comment]
There are some provided, see e.g. this notebook https://pypesto.readthedocs.io/en/latest/example/sampling_diagnostics.html

**Comment by PaulJonasJost** [comment]
Closing this since question is sufficiently answered. Feel free to reopen if more questions arise.
