### ISSUE TITLE
Re-implement make amici only compute required derivatives

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#99]
While introducing the petab mapping between optimization and simulation parameters, the AmiciObjective.update_from_problem function had to be deleted, because it is not immediately clear which sensis are required for amici to simulate. Thus, this feature was deactivated, and amici computes all.

It should be easy though to check which gradient outputs are required in the back mapping, so it might be a good idea to re-implement this.

**Comment by FFroehlich** [comment]
Fixed in https://github.com/AMICI-dev/AMICI/pull/1487 / https://github.com/ICB-DCM/pyPESTO/pull/621
