### ISSUE TITLE
Simple simulation routine for PEtab file

### ISSUE THREAD

**Issue by shoepfl** [ICB-DCM/pyPESTO#992]
Is there a simple basic simulation routine?

I did not find any example in the docs but how can you create a simulationData.tsv with a
PEtab file and already estimated parameters.

The reason is that plotting with visualize_optimized_model_fit works directly after parameter estimation
but i cannot reproduce it or save the simulation data.

I tried: 
`amici_model.setTimepoints(np.linspace(0, 2, 100000))`
`rdata = amici.runAmiciSimulation(amici_model, solver)`

but rdata is non and simulate_petab also does not provide the same results as visualize_optimized_model_fit.

**Comment by FFroehlich** [comment]
Hi @shoepfl, you can check out the petab simulator class in amici https://amici.readthedocs.io/en/latest/generated/amici.petab_simulate.PetabSimulator.html#amici.petab_simulate.PetabSimulator, which can also add noise to the data and should directly return a simulation dataframe which has the same format as a measurements table and can be visualized using petab visualization routines.

For more advanced workflows you can also use https://amici.readthedocs.io/en/latest/generated/amici.petab_objective.html#amici.petab_objective.rdatas_to_measurement_df which converts amici rdata formats to simulation dataframes.

**Comment by shoepfl** [comment]
Thanks @FFroehlich something like the PEtabSimulator was what I was looking for.

**Comment by dilpath** [comment]
> The reason is that plotting with visualize_optimized_model_fit works directly after parameter estimation but i cannot reproduce it or save the simulation data.

What do you mean by "cannot reproduce it"? e.g. one can save the optimization result to disk, then read it in again, then plot with `visualize_optimized_model_fit` -- this should reproduce it without having to plot with `visualize_optimized_model_fit` directly after parameter estimation.

https://github.com/ICB-DCM/pyPESTO/blob/b3ea99cc36a361ca4014d9a7a3c9b91ee4bdf45c/pypesto/store/read_from_hdf5.py#L263-L269

https://github.com/ICB-DCM/pyPESTO/blob/b3ea99cc36a361ca4014d9a7a3c9b91ee4bdf45c/pypesto/store/save_to_hdf5.py#L252-L260

> save the simulation data

This is available with `visualize_optimized_model_fit(..., return_dict=True)`

https://github.com/ICB-DCM/pyPESTO/blob/b3ea99cc36a361ca4014d9a7a3c9b91ee4bdf45c/pypesto/visualize/model_fit.py#L94-L100

**Comment by shoepfl** [comment]
Hi @dilpath with "cannot reproduce it" I meant that I did not get the same results by
simulation with the estimated parameters only using the SBML in libroadrunner.

I now found the reason why this is the case. For my system I have only two measurement time points (which is bad
but unfortunately we only got this). For the optimization and for plotting pypesto/amici only use one integration step 
between these two time points. Therefore i always got a different behaviour with more integration steps between the two time points. Is this the expected behaviour? - In my eyes it should use more than one integration step as the soultion should not depend on how many integration steps are used.

**Comment by dilpath** [comment]
> For the optimization and for plotting pypesto/amici only use one integration step between these two time points. Therefore i always got a different behaviour with more integration steps between the two time points. Is this the expected behaviour?

Could you clarify what you mean by this? Integration steps are irrelevant to plotting, or do you mean something else than numerical integration? During optimization, AMICI would use more than 1 integration step. How do you determine the number of integration steps? Is it with e.g. `rdata.numsteps`?

If easy, could you share an example (e.g. plot) that shows how the solution changes depending on the number of integration steps?

**Comment by shoepfl** [comment]
I would also like to use more than 1 integration step. The thing is I have the strong feeling that AMICI does only use 1 integration step in the optimization. This is because I got a plot with a straight line between the two time points out of visualize_optimized_model_fit and also the simulation data only contains values for these two time points of the measurement table. When I tried to reproduce the fits by simulation of the PEtab file with more integration steps (as I was expecting it would have been done so by Amici) the simulation always fails - only when I only take 1 integration step I am able to reproduce the plot of visualize_optimized_model_fit

Sorry that I am not able to share the data publicly as they belong to a cooperation partner and they want to wait until its published.

**Comment by dilpath** [comment]
Ah, the straight line is because only simulation values at measured timepoints are plotted. If you want to plot a more densely-sampled trajectory, there are a few options. Given your setup, maybe it's simplest to create a dummy PEtab problem that generates the plot you want to see. For example, duplicate your current PEtab problem, and add measurements at timepoints that you want to see simulation values at. Then use this dummy PEtab problem in the `visualize_optimized_model_fit` call, but use the original PEtab problem for optimization/other calibration tasks.

**Comment by shoepfl** [comment]
Okay thanks I will try this out.

**Comment by shoepfl** [comment]
Dear @dilpath,

thanks again for the solution with the dummy PEtab - I totally forgot to answer but it indeed solved the problem.
